import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import mioV268Transform from './mio-v268-transform.js'
import mioV268Hotfix from './mio-v268-hotfix.js'
import mioV272DraftingFormatting from './mio-v272-drafting-formatting.js'
import mioV274DraftingLayout from './mio-v274-drafting-layout.js'
import mioV275DraftingEditor from './mio-v275-drafting-editor.js'
import mioV276AutofillPicker from './mio-v276-autofill-picker.js'
import mioV277CloudPersistence from './mio-v277-cloud-persistence.js'
import mioV279WithdrawalDashboard from './mio-v279-withdrawal-dashboard.js'
import mioV278DraftingComponents from './mio-v278-drafting-components.js'
import mioV280DraftingDocumentSetup from './mio-v280-drafting-document-setup.js'
import mioV281DraftingBlocks from './mio-v281-drafting-blocks.js'
import mioV283WithdrawalClarity from './mio-v283-withdrawal-clarity.js'
import mioV284DraftingStructuralDelete from './mio-v284-drafting-structural-delete.js'
import mioV287DraftingReadiness from './mio-v287-drafting-readiness.js'
import mioV291DraftingCleanUi from './mio-v291-drafting-clean-ui.js'
import mioV292DraftingNonblocking from './mio-v292-drafting-nonblocking.js'
import mioV293TemplateMatterTest from './mio-v293-template-matter-test.js'
import mioV294TemplateOpenDownloadFix from './mio-v294-template-open-download-fix.js'
import mioV295BindingReanchor from './mio-v295-binding-reanchor.js'
import mioV300TemplateRepair from './mio-v300-template-repair.js'
import mioV301StartupSettings from './mio-v301-startup-settings.js'
import mioV302PartyPronouns from './mio-v302-party-pronouns.js'
import mioV303WithdrawalNextAction from './mio-v303-withdrawal-next-action.js'
import mioV304WithdrawalInline from './mio-v304-withdrawal-inline.js'
import mioV3042WithdrawalSimpleComplete from './mio-v3042-withdrawal-simple-complete.js'
import mioV3043WithdrawalGlance from './mio-v3043-withdrawal-glance.js'
import mioV3044WithdrawalFlow from './mio-v3044-withdrawal-flow.js'
import mioV305WorkflowBlocks from './mio-v305-workflow-blocks.js'
import mioV306WithdrawalGraphTable from './mio-v306-withdrawal-graph-table.js'
import mioV307Compat from './mio-v307-compat.js'
import mioV307DropboxDraftSources from './mio-v307-dropbox-draft-sources.js'
import mioV308ServiceInboxFixes from './mio-v308-service-inbox-fixes.js'
import mioV309ServiceEserviceBatch from './mio-v309-service-eservice-batch.js'
import mioV309ReleaseLabel from './mio-v309-release-label.js'
import mioV310MailformSnailMail from './mio-v310-mailform-snail-mail.js'
import mioV311WithdrawalRowControls from './mio-v311-withdrawal-row-controls.js'
import nativeMatters from './mio-v312-native-matters.js'
import stickyFilters from './mio-v312-sticky-filters.js'
import discoveryCompact from './mio-v312-discovery.js'
import pncDailyTrust from './mio-v313-pnc-daily-trust.js'
import financeReview from './mio-v314-finance-review.js'
import mioBrowserSyntaxCheck from './mio-browser-syntax-check.js'

export default defineConfig({
  plugins: [mioV268Transform(), mioV268Hotfix(), mioV272DraftingFormatting(), mioV274DraftingLayout(), mioV275DraftingEditor(), mioV276AutofillPicker(), mioV277CloudPersistence(), mioV278DraftingComponents(), mioV279WithdrawalDashboard(), mioV280DraftingDocumentSetup(), mioV281DraftingBlocks(), mioV283WithdrawalClarity(), mioV284DraftingStructuralDelete(), mioV287DraftingReadiness(), mioV291DraftingCleanUi(), mioV292DraftingNonblocking(), mioV293TemplateMatterTest(), mioV294TemplateOpenDownloadFix(), mioV295BindingReanchor(), mioV300TemplateRepair(), mioV301StartupSettings(), mioV302PartyPronouns(), mioV303WithdrawalNextAction(), mioV304WithdrawalInline(), mioV3042WithdrawalSimpleComplete(), mioV3043WithdrawalGlance(), mioV3044WithdrawalFlow(), mioV305WorkflowBlocks(), mioV306WithdrawalGraphTable(), mioV307Compat(), mioV307DropboxDraftSources(), mioV308ServiceInboxFixes(), mioV309ServiceEserviceBatch(), mioV309ReleaseLabel(), mioV310MailformSnailMail(), mioV311WithdrawalRowControls(), nativeMatters(), stickyFilters(), discoveryCompact(), pncDailyTrust(), financeReview(), react(), mioBrowserSyntaxCheck()],
})
