/** Existing Mio provider clients are injected; no secrets or credentials enter definitions. */
const addresses=s=>String(s||'').split(/[;,\n]/).map(x=>x.trim()).filter(Boolean);
const validEmail=s=>/^[^\s<>@]+@[^\s<>@]+\.[^\s<>@]+$/.test(s);
function decode(data,name){const match=String(data||'').match(/^data:([^;,]+);base64,([A-Za-z0-9+/=\r\n]+)$/);if(!match)throw Error('Cannot read document '+name);const base64=match[2].replace(/[\r\n]/g,''),bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0));if(!bytes.length||bytes.length>50*1024*1024)throw Error('Document must be nonempty and smaller than 50 MB.');return {name,type:match[1],base64,bytes};}
export function actions(ctx){
 const configuration=(r,n)=>r.steps[n.id].config;
 function recipients(r,n){const c=configuration(r,n),role=c.recipientRole||'opposing_counsel';const to=addresses(c.to||((ctx.people?.(r.matterId)||[]).filter(p=>p.source===role||p.key?.startsWith(role+'::')).map(p=>p.email).join(';'))),cc=addresses(c.cc);if(!to.length||[...to,...cc].some(a=>!validEmail(a)))throw Error('Choose valid recipient email addresses for this matter.');return {to:[...new Set(to)],cc:[...new Set(cc)]};}
 async function files(r,n){const c=configuration(r,n),ids=[...new Set([...(c.documentIds||[]),...(c.inputSlots||[]).map(s=>r.documents[s]?.id).filter(Boolean)])],result=[];for(const id of ids){const d=(ctx.documents||[]).find(d=>String(d.id)===String(id)&&String(d.matter_id)===r.matterId);if(!d)throw Error('A document is missing from this matter.');result.push({...decode(await ctx.getFile(d),d.file_name||d.name||'Document'),documentId:String(d.id)});}return result;}
 async function preflight(r,n){const c=configuration(r,n),f=await files(r,n);if(['draft_email','esign_document'].includes(n.type)){recipients(r,n);if(!c.subject?.trim()||!c.body?.trim())throw Error('Enter an email subject and message.');}if(['efile_document','mailform','esign_document','save_file'].includes(n.type)&&!f.length)throw Error('Select reviewed input documents first.');if(['efile_document','mailform','esign_document'].includes(n.type)&&f.some(x=>String.fromCharCode(...x.bytes.slice(0,5))!=='%PDF-'))throw Error('This action requires reviewed PDF documents.');if(n.type==='draft_email'&&f.reduce((sum,x)=>sum+x.base64.length,0)>3500000)throw Error('Attachments are too large for inline sending. Use Outlook and record actual completion.');if(n.type==='save_file'){if(f.length!==1)throw Error('Use one Save file block per document.');if(!c.folder?.trim()||c.folder.split('/').some(s=>s==='..'))throw Error('Choose an existing OneDrive destination folder.');const name=c.filename||f[0].name;if(/[<>:"/\\|?*\x00-\x1f]/.test(name)||['.','..'].includes(name))throw Error('Choose a valid filename.');}if(n.type==='draft_document'&&!c.templateId)throw Error('Choose a drafting template.');if(n.type==='matter_status')ctx.validateStatus?.(c.statusField,c.statusValue);return f;}
 return {preflight,recipients,
 async perform(r,n){const c=configuration(r,n),f=await preflight(r,n),replace=s=>String(s||'').replaceAll('{matter}',r.matterName).replaceAll('{block}',n.name);
  if(n.type==='notification')return {reference:'Mio notification: '+replace(c.body||n.name)};
  if(n.type==='draft_email'){const {to,cc}=recipients(r,n),draft=await ctx.graph('/me/messages',{method:'POST',maxRetries:0,allowInteractive:!n.automatic,headers:{Prefer:'IdType="ImmutableId"'},body:JSON.stringify({subject:replace(c.subject),body:{contentType:'HTML',content:ctx.emailHtml(replace(c.body))},toRecipients:to.map(address=>({emailAddress:{address}})),ccRecipients:cc.map(address=>({emailAddress:{address}})),attachments:f.map(x=>({'@odata.type':'#microsoft.graph.fileAttachment',name:x.name,contentType:x.type,contentBytes:x.base64}))})});if(!draft?.id)throw Error('Outlook did not confirm the draft. Nothing was sent.');await ctx.graph('/me/messages/'+encodeURIComponent(draft.id)+'/send',{method:'POST',maxRetries:0,allowInteractive:false,headers:{Prefer:'IdType="ImmutableId"'}});return {reference:'Outlook accepted send for message '+draft.id,receipt:{messageId:draft.id,conversationId:draft.conversationId||'',recipients:to}};}
  if(n.type==='save_file'){const folder=c.folder.split('/').filter(Boolean).map(encodeURIComponent).join('/'),parent=await ctx.graph(folder?'/me/drive/root:/'+folder:'/me/drive/root',{allowInteractive:!n.automatic});if(!parent?.id||!parent.folder)throw Error('Destination is not an existing OneDrive folder.');const name=c.filename||f[0].name,session=await ctx.graph('/me/drive/items/'+encodeURIComponent(parent.id)+':/'+encodeURIComponent(name)+':/createUploadSession',{method:'POST',maxRetries:0,body:JSON.stringify({item:{'@microsoft.graph.conflictBehavior':'fail',name}})});if(!/^https:\/\//.test(session?.uploadUrl||''))throw Error('OneDrive did not supply a secure upload session.');const file=f[0],res=await(ctx.upload||fetch)(session.uploadUrl,{method:'PUT',headers:{'Content-Range':'bytes 0-'+(file.bytes.length-1)+'/'+file.bytes.length,'Content-Type':'application/octet-stream'},body:file.bytes});const item=await res.json().catch(()=>({}));if(!res.ok||![200,201].includes(res.status)||!item.id)throw Error('OneDrive did not confirm a completed file. Check the destination before retrying.');return {reference:'OneDrive file '+item.id,receipt:{id:item.id,name:item.name||name}};}
  if(n.type==='esign_document'){const {to}=recipients(r,n),data=await ctx.signature('send',{files:f.map(x=>({name:x.name,content_type:'application/pdf',base64:x.base64})),signers:to.map((email_address,order)=>({email_address,name:email_address,order})),title:n.name,subject:replace(c.subject),message:replace(c.body),test_mode:false,metadata:{matter_id:r.matterId,process_id:r.id,step_id:n.id}});const id=data.signature_request?.signature_request_id;if(!id)throw Error('Dropbox Sign did not confirm the request.');return {reference:'Dropbox Sign request '+id,receipt:{signatureRequestId:id}};}
  if(n.type==='matter_status'){await ctx.changeStatus(r.matterId,c.statusField,c.statusValue);return {reference:'Matter '+r.matterId+' '+c.statusField+' = '+c.statusValue};}
  if(['draft_document','efile_document','mailform','review_document','calendar'].includes(n.type)){const open=ctx.prepareOpen(r,n,f);if(!open)throw Error('Opening the workspace was cancelled; nothing was sent.');return {type:'handoff',reference:'Mio '+n.type+' workspace',message:'Waiting for you to complete '+n.name.toLowerCase()+' in its workspace and record the result',open};}
  throw Error('Use Record actual completion for this block.');
 },
 async check(r,n){const receipt=r.steps[n.id].receipt||{};if(n.type==='esign_document'&&receipt.signatureRequestId){const data=await ctx.signature('request',{signature_request_id:receipt.signatureRequestId});if(data.signature_request?.is_complete&&!data.signature_request?.test_mode)return {reference:'Completed Dropbox Sign request '+receipt.signatureRequestId};return null;}
 if(n.type==='draft_email'&&receipt.conversationId){let next='/me/messages?$filter='+encodeURIComponent("conversationId eq '"+receipt.conversationId.replaceAll("'","''")+"'")+'&$select=id,conversationId,receivedDateTime,from,subject&$top=100';for(let page=0;page<10&&next;page++){const data=await ctx.graph(next,{allowInteractive:true});const reply=(data.value||[]).find(x=>x.conversationId===receipt.conversationId&&Date.parse(x.receivedDateTime)>Date.parse(r.steps[n.id].performedAt)&&(receipt.recipients||[]).some(a=>a.toLowerCase()===String(x.from?.emailAddress?.address||'').toLowerCase()));if(reply)return {reference:'Outlook reply '+reply.id};next=data['@odata.nextLink']||'';}return null;}return null;
 }
 };
}
