import React,{useEffect,useRef,useState} from 'react';
import {TYPES,copy,makeBlock,uid,typeFor,validateDefinition} from './model.js';
import {Field,Check,ActionFields} from './Fields.jsx';
export default function Builder({definition,onSave,onClose,templates=[]}){
 const [draft,setDraft]=useState(()=>copy(definition)),[selected,setSelected]=useState(''),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[linkFrom,setLinkFrom]=useState(''),[chain,setChain]=useState(true);
 const canvas=useRef(null),drag=useRef(null),node=draft.nodes.find(n=>n.id===selected);
 useEffect(()=>{if(!dirty)return;const guard=e=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
 const change=fn=>{setDraft(d=>fn(copy(d)));setDirty(true);setError('');};
 const patch=p=>change(d=>({...d,nodes:d.nodes.map(n=>n.id===selected?{...n,...p}:n)}));
 const point=e=>{const el=canvas.current,r=el.getBoundingClientRect(),scale=r.width/el.offsetWidth||1;return {x:Math.max(0,(e.clientX-r.left)/scale),y:Math.max(0,(e.clientY-r.top)/scale)};};
 function add(type,x,y){const parent=draft.nodes.find(n=>n.id===selected),n=makeBlock(type,x??(parent?parent.x+270:40),y??(parent?parent.y:40));if(chain&&parent)n.dependsOn=[parent.id];change(d=>({...d,nodes:[...d.nodes,n]}));setSelected(n.id);}
 function connect(to,from=linkFrom){if(!from||from===to){setLinkFrom('');return;}try{const d=copy(draft),n=d.nodes.find(n=>n.id===to);n.dependsOn=[...new Set([...n.dependsOn,from])];validateDefinition(d);change(()=>d);setLinkFrom('');}catch(e){setError(e.message);}}
 function drop(e){e.preventDefault();const kind=e.dataTransfer.getData('application/x-mio-block');if(!kind)return;const p=point(e);if(kind.startsWith('move:')){const id=kind.slice(5);change(d=>({...d,nodes:d.nodes.map(n=>n.id===id?{...n,x:Math.max(0,p.x-40),y:Math.max(0,p.y-20)}:n)}));}else add(kind,p.x,p.y);}
 const width=Math.max(1000,...draft.nodes.map(n=>n.x+300)),height=Math.max(580,...draft.nodes.map(n=>n.y+210));
 const close=()=>{if(!dirty||window.confirm('Discard unsaved process edits?'))onClose();};
 return <section className="proc-builder">
 <header className="proc-toolbar"><div><h2>Process designer</h2><p>Drag blocks onto the canvas. Connect their ports to create serial or parallel paths.</p></div><div className="proc-actions"><button onClick={close} disabled={busy}>Close designer</button><button className="proc-primary" disabled={busy||!dirty} onClick={async()=>{setBusy(true);setError('');try{validateDefinition(draft);const saved=await onSave(draft);setDraft(saved);setDirty(false);}catch(e){setError(e.message);}finally{setBusy(false);}}}>{busy?'Saving...':'Save process'}</button></div></header>
 <div className="proc-actions"><Field label="Process name" value={draft.name} onChange={name=>change(d=>({...d,name}))}/><span className="proc-muted">{dirty?'Unsaved changes':'Saved definition'} · New runs use this version. Existing runs keep their own version.</span></div>
 {error&&<p role="alert" className="proc-error">{error}</p>}
 <div className="proc-designer-grid"><aside className="proc-palette"><h3>Block library</h3><small>Drag or click to add</small>{TYPES.map(t=><button key={t.id} draggable onDragStart={e=>e.dataTransfer.setData('application/x-mio-block',t.id)} onClick={()=>add(t.id)} data-block-type={t.id}><span>{t.icon}</span>{t.label}</button>)}<Check label="Link new block after selected" checked={chain} onChange={setChain}/></aside>
 <div className="proc-canvas-wrap"><div className="proc-canvas-help">{linkFrom?'Choose an input port to finish the connection.':'One output to multiple inputs = parallel branches. Connections, not card positions, determine execution.'}<button onClick={()=>{setSelected('');setLinkFrom('');}}>Clear selection</button></div><div className="proc-canvas-scroll"><div className="proc-canvas" ref={canvas} onDragOver={e=>e.preventDefault()} onDrop={drop} style={{width,height}} onPointerMove={e=>{if(!drag.current)return;const p=point(e),a=drag.current;change(d=>({...d,nodes:d.nodes.map(n=>n.id===a.id?{...n,x:Math.max(0,p.x-a.dx),y:Math.max(0,p.y-a.dy)}:n)}));}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
 <svg className="proc-edges" width={width} height={height}><defs><marker id="process-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z"/></marker></defs>{draft.nodes.flatMap(n=>n.dependsOn.map(id=>{const p=draft.nodes.find(x=>x.id===id);if(!p)return null;const x=p.x+220,y=p.y+64,tx=n.x,ty=n.y+64,delta=Math.max(60,Math.abs(tx-x)/2);return <path key={id+n.id} data-edge={id+'-'+n.id} d={`M ${x} ${y} C ${x+delta} ${y} ${tx-delta} ${ty} ${tx} ${ty}`} markerEnd="url(#process-arrow)"/>;}))}</svg>
 {draft.nodes.map(n=><article key={n.id} className={'proc-node '+(selected===n.id?'selected':'')} style={{left:n.x,top:n.y}} data-node-id={n.id} onClick={()=>setSelected(n.id)}><button className="proc-port input" aria-label={'Connect to '+n.name} title="Input: connect a preceding block" onClick={e=>{e.stopPropagation();connect(n.id);}}>●</button><div className="proc-grip" role="button" tabIndex={0} aria-label={'Move '+n.name} onPointerDown={e=>{if(e.button!==0)return;const p=point(e);drag.current={id:n.id,dx:p.x-n.x,dy:p.y-n.y};setSelected(n.id);canvas.current.setPointerCapture(e.pointerId);e.preventDefault();}} onKeyDown={e=>{const moves={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]};if(moves[e.key]){e.preventDefault();const [dx,dy]=moves[e.key];change(d=>({...d,nodes:d.nodes.map(x=>x.id===n.id?{...x,x:Math.max(0,x.x+dx),y:Math.max(0,x.y+dy)}:x)}));}}}><span className="proc-node-icon">{n.icon}</span><strong>{n.name}</strong><span>⠿</span></div><small>{typeFor(n.type).label} · {n.dependsOn.length>1?n.join==='all'?'All inputs':'Any input':n.trigger==='completion'?'After previous block':n.trigger}</small><div className="proc-badges"><span>{n.approval?'Approval required':'No approval'}</span>{n.billing.enabled&&<span>{n.billing.minutes} min</span>}{n.automatic&&<span>Automatic</span>}</div><button className="proc-port output" aria-label={'Connect from '+n.name} title="Output: click, then choose an input" onClick={e=>{e.stopPropagation();setLinkFrom(n.id);}}>●</button></article>)}
 {!draft.nodes.length&&<div className="proc-empty">Drop your first block here<br/><small>Start with Email, Draft document, or any other action.</small></div>}
 </div></div></div>
 <aside className="proc-properties"><h3>{node?'Block settings':'Select a block'}</h3>{node?<>
 <Field label="Block name" value={node.name} onChange={name=>patch({name})}/><Field label="Activity icon" value={node.icon} onChange={icon=>patch({icon})}/>
 <Field label="Start trigger" value={node.trigger} options={[{value:'completion',label:'When predecessors complete'},{value:'manual',label:'Manual start'},{value:'date',label:'On or after date/time'},{value:'event',label:'Named event'}]} onChange={trigger=>patch({trigger})}/>
 {node.trigger==='date'&&<Field label="Start date/time (local)" type="datetime-local" value={node.startAt} onChange={startAt=>patch({startAt})}/>}{node.trigger==='event'&&<Field label="Trigger event name" value={node.eventName} onChange={eventName=>patch({eventName})}/>}
 <Field label="Incoming branches" value={node.join} options={[{value:'all',label:'Wait for all predecessors'},{value:'any',label:'Wait for any predecessor'}]} onChange={join=>patch({join})}/>
 <details><summary>Connections ({node.dependsOn.length})</summary>{draft.nodes.filter(n=>n.id!==selected).map(n=><Check key={n.id} label={n.name} checked={node.dependsOn.includes(n.id)} onChange={on=>{if(on)connect(selected,n.id);else patch({dependsOn:node.dependsOn.filter(id=>id!==n.id)});}}/>)}</details>
 <Check label="Require approval before this action" checked={node.approval} onChange={approval=>patch({approval})}/>{typeFor(node.type).automatic&&<Check label="Run automatically once ready / approved" checked={node.automatic} onChange={automatic=>patch({automatic})}/>}
 <Field label="Block completes" value={node.completion} options={[{value:'action',label:'After successful action'},{value:'response',label:'After response / result is reviewed'}]} onChange={completion=>patch({completion})}/>
 <Field label="Who / what are we waiting on?" value={node.waitingOn} onChange={waitingOn=>patch({waitingOn})}/>
 <details open><summary>Status messages</summary>{[['ready','Before action'],['approval','Awaiting your approval'],['waiting','After action / waiting'],['complete','Completed notification']].map(([key,label])=><Field key={key} label={label} value={node.messages[key]} placeholder="Use default message" rows={2} onChange={v=>patch({messages:{...node.messages,[key]:v}})}/>)}<small>{'{who}'}, {'{matter}'}, and {'{block}'} are supported.</small></details>
 <details open><summary>Action configuration</summary><ActionFields node={node} config={node.config} change={config=>patch({config})} templates={templates}/></details>
 <details><summary>Input / output document slots</summary>{['inputSlots','outputSlots'].map(key=><fieldset key={key}><legend>{key==='inputSlots'?'Required inputs':'Required outputs'}</legend>{draft.slots.map(s=><Check key={s.id} label={s.name} checked={(node.config[key]||[]).includes(s.id)} onChange={on=>patch({config:{...node.config,[key]:on?[...(node.config[key]||[]),s.id]:(node.config[key]||[]).filter(id=>id!==s.id)}})}/>)}</fieldset>)}<button onClick={()=>{const name=window.prompt('Document slot name (for example: File-stamped motion)');if(name?.trim())change(d=>({...d,slots:[...d.slots,{id:uid(),name:name.trim()}]}));}}>Add shared document slot</button></details>
 <fieldset><legend>Automatic billing</legend><Check label="Bill once when this action actually occurs" checked={node.billing.enabled} onChange={enabled=>patch({billing:{...node.billing,enabled}})}/>{node.billing.enabled&&<><Field label="Billing minutes" type="number" min="1" max="1440" value={node.billing.minutes} onChange={minutes=>patch({billing:{...node.billing,minutes:Number(minutes)}})}/><Field label="Billing description" value={node.billing.description} rows={3} onChange={description=>patch({billing:{...node.billing,description}})}/><small>Uses Mio's matter/user rate. No billing for merely activating a step or opening its workspace.</small></>}</fieldset>
 <button className="proc-danger" onClick={()=>{if(window.confirm('Remove this block and its connections?')){change(d=>({...d,nodes:d.nodes.filter(n=>n.id!==selected).map(n=>({...n,dependsOn:n.dependsOn.filter(id=>id!==selected)}))}));setSelected('');}}}>Remove block</button>
 </>:<p>Each block owns its action, approval, waiting messages, documents, and billing rule. Click a card to inspect them.</p>}</aside></div>
 </section>;
}
