import React from 'react';
export function Check({label,checked,onChange,disabled=false}){return <label className="proc-check"><input type="checkbox" checked={!!checked} disabled={disabled} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>;}
export function Field({label,value,onChange,options,rows,type='text',...rest}){return <label className="proc-field"><span>{label}</span>{options?<select aria-label={label} value={value??''} onChange={e=>onChange(e.target.value)} {...rest}>{options.map(o=><option key={o.value??o} value={o.value??o}>{o.label??o}</option>)}</select>:rows?<textarea aria-label={label} value={value??''} rows={rows} onChange={e=>onChange(e.target.value)} {...rest}/>:<input aria-label={label} type={type} value={value??''} onChange={e=>onChange(e.target.value)} {...rest}/>}</label>;}
export function ActionFields({node,config,change,documents=[],templates=[],runtime=false}){
 const patch=(k,v)=>change({...config,[k]:v});
 return <>
 {['draft_email','esign_document'].includes(node.type)&&<><Field label="Recipient role" value={config.recipientRole} onChange={v=>patch('recipientRole',v)} options={['opposing_counsel','client','opposing_party','court','custom']}/><Field label="To (explicit email addresses override role)" value={config.to} onChange={v=>patch('to',v)}/>{node.type==='draft_email'&&<Field label="Cc" value={config.cc} onChange={v=>patch('cc',v)}/>}<Field label="Email subject" value={config.subject} onChange={v=>patch('subject',v)}/><Field label="Email draft" value={config.body} rows={7} onChange={v=>patch('body',v)}/><small>Use {'{matter}'} for the matter name. Drafts remain editable before sending.</small></>}
 {node.type==='draft_document'&&<Field label="Drafting template" value={config.templateId} onChange={v=>patch('templateId',v)} options={[{value:'',label:'Choose template'},...templates.map(t=>({value:t.id,label:t.name||t.title||t.id}))]}/>}
 {node.type==='save_file'&&<><Field label="Destination OneDrive folder" value={config.folder} onChange={v=>patch('folder',v)} placeholder="/Client files/Drafts"/><Field label="Saved filename (optional)" value={config.filename} onChange={v=>patch('filename',v)}/><small>The folder must exist. Existing files are not silently overwritten.</small></>}
 {node.type==='matter_status'&&<><Field label="Status field" value={config.statusField} onChange={v=>patch('statusField',v)} options={['matter_status','case_status']}/><Field label="New status (must match Settings)" value={config.statusValue} onChange={v=>patch('statusValue',v)}/></>}
 {node.type==='notification'&&<Field label="Notification text" value={config.body} rows={3} onChange={v=>patch('body',v)}/>}
 {runtime&&!['notification','wait','approve'].includes(node.type)&&<fieldset><legend>Reviewed matter documents</legend>{documents.length?documents.map(d=><Check key={d.id} label={d.file_name||d.name||d.title||d.id} checked={(config.documentIds||[]).includes(String(d.id))} onChange={on=>patch('documentIds',on?[...(config.documentIds||[]),String(d.id)]:(config.documentIds||[]).filter(id=>id!==String(d.id)))}/>):<small>No documents loaded for this matter. Refresh the document list in Mio before selecting a file.</small>}<small>Selecting a file confirms it is intended for this block.</small></fieldset>}
 </>;
}
