import React,{useEffect,useMemo,useRef,useState} from 'react';
import {makeDefinition,makeBlock,uid,copy,fromWithdrawal,startRun,attention,reduceRun,prerequisites} from './model.js';
import {repository} from './repository.js';
import Builder from './Builder.jsx';import RunPanel,{History} from './RunPanel.jsx';import {Field} from './Fields.jsx';
import './processes.css';
export default function Processes({client,owner,context}){
 const ctx=useRef(context);ctx.current=context;
 const repo=useMemo(()=>repository(client,owner,id=>ctx.current.billingContext(id)),[client,owner]);
 const[templates,setTemplates]=useState([]),[runs,setRuns]=useState([]),[designer,setDesigner]=useState(null),[tab,setTab]=useState('library'),[selectedDef,setSelectedDef]=useState(''),[matter,setMatter]=useState(''),[expanded,setExpanded]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[filter,setFilter]=useState('active'),[recoveries,setRecoveries]=useState({}),[notice,setNotice]=useState('');
 const lock=useRef(false),attempted=useRef(new Set()),alive=useRef(true),runsRef=useRef(runs);runsRef.current=runs;
 useEffect(()=>{alive.current=true;load();return()=>{alive.current=false;};},[repo]);
 async function load(){try{const all=await repo.list();if(!alive.current)return;setTemplates(all.templates);setRuns(all.runs);setError('');}catch(e){if(alive.current)setError(e.message+' Process data was not overwritten.');}}
 const replace=r=>{if(alive.current)setRuns(old=>[r,...old.filter(x=>x.id!==r.id)]);return r;};
 async function work(fn){if(lock.current)throw Error('Another process action is still saving.');lock.current=true;setBusy(true);setError('');try{return await fn();}catch(e){setError(e.message);throw e;}finally{lock.current=false;if(alive.current)setBusy(false);}}
 async function event(r,e){return work(async()=>{const next=await repo.dispatch(r,e);replace(next);attempted.current.delete(r.id+':'+e.nodeId);if(e.nodeId&&next.steps[e.nodeId]?.billingId!==r.steps[e.nodeId]?.billingId)ctx.current.billingRefresh?.();return next;});}
 async function execute(r,n){return work(async()=>{
  const key=r.id+':'+n.id;repo.preflight(r,n.id);await ctx.current.preflight(r,n);const claimed=replace(await repo.dispatch(r,{type:'claim',nodeId:n.id}));let result;
  try{result=await ctx.current.perform(claimed,n);}catch(e){try{replace(await repo.dispatch(claimed,{type:'failure',nodeId:n.id,message:e.message}));}catch{}throw Error(e.message+' Check the provider before retrying.');}
  const outcome={id:uid(),type:result.type||'success',nodeId:n.id,reference:result.reference,message:result.message,receipt:result.receipt};
  try{const saved=replace(await repo.dispatch(claimed,outcome));if(saved.steps[n.id].billingId)ctx.current.billingRefresh?.();if(result.type!=='handoff')setNotice(saved.steps[n.id].status==='complete'?(n.messages?.complete||result.reference):result.reference);result.open?.();}
  catch(e){setRecoveries(x=>({...x,[key]:{runId:r.id,event:outcome,open:result.open}}));throw Error('The action may have succeeded but its result was not saved. Use Retry saving result; do not repeat the action. '+e.message);}
 });}
 async function check(r,n){return work(async()=>{const signal=await ctx.current.check(r,n);if(!signal){setError('No new matching response or completed signature request was found.');return;}replace(await repo.dispatch(r,{type:'signal',nodeId:n.id,confirmed:true,reference:signal.reference}));});}
 // This is an open-page runner, not a background scheduler. Each effect first claims the run in Supabase.
 useEffect(()=>{if(busy)return;const candidates=runs.filter(r=>r.status==='active');for(const r of candidates){const due=r.definition.nodes.some(n=>r.steps[n.id].status==='blocked'&&n.trigger==='date'&&Date.parse(n.startAt)<=Date.now()&&prerequisites(r,n));if(due){event(r,{type:'tick'}).catch(()=>{});return;}const n=r.definition.nodes.find(n=>n.automatic&&!r.steps[n.id].performedAt&&!r.steps[n.id].responseReference&&r.steps[n.id].status==='ready'&&!attempted.current.has(r.id+':'+n.id));if(n){attempted.current.add(r.id+':'+n.id);execute(r,n).catch(()=>{});return;}}},[runs,busy]);
 useEffect(()=>{const timer=setInterval(()=>{if(!lock.current)setRuns(x=>[...x]);},30000);return()=>clearInterval(timer);},[]);
 const control={busy,event:(...a)=>event(...a).catch(()=>null),execute:(...a)=>execute(...a).catch(()=>null),check:(...a)=>check(...a).catch(()=>null)};
 const visible=runs.filter(r=>[r.name,r.matterName].join(' ').toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='active'&&['active','paused'].includes(r.status)||filter==='needs'&&attention(r).some(a=>a.needsMe)||filter==='waiting'&&attention(r).length&&!attention(r).some(a=>a.needsMe))).sort((a,b)=>{const aa=attention(a),bb=attention(b);return Number(bb.some(x=>x.needsMe))-Number(aa.some(x=>x.needsMe))||Date.parse(aa[0]?.since||a.startedAt)-Date.parse(bb[0]?.since||b.startedAt);});
 function example(){const d=makeDefinition('Order approval and court dates');const a=makeBlock('draft_document',40,210);a.name='Draft order';const b=makeBlock('draft_email',330,80);b.name='Email order to counsel';b.dependsOn=[a.id];b.waitingOn='opposing counsel';const c=makeBlock('draft_email',330,360);c.name='Request court dates';c.dependsOn=[a.id];c.config.recipientRole='court';c.waitingOn='court coordinator';c.messages.waiting='Waiting for the court to send available dates';const end=makeBlock('review_document',640,210);end.name='Review responses';end.dependsOn=[b.id,c.id];d.nodes=[a,b,c,end];return d;}
 return <div className="proc-page"><header className="proc-page-head"><div><h1>Processes</h1><p>Build from reusable blocks. Run per matter. See exactly what is waiting.</p></div><button disabled={busy} onClick={()=>{attempted.current.clear();load();}}>Refresh processes</button></header>
 <div className="proc-tabs"><button className={tab==='library'?'active':''} onClick={()=>setTab('library')}>Process library</button><button className={tab==='runs'?'active':''} onClick={()=>setTab('runs')}>Matter processes ({runs.filter(r=>r.status==='active').length} active)</button></div>
 <p className="proc-muted">Automatic actions and date checks run while this Processes page is open. External workspace actions retain their own final approval. Opening a workspace is not completion.</p>
 {notice&&<div role="status" className="proc-warning">{notice} <button onClick={()=>setNotice('')}>Dismiss notification</button></div>}
 {error&&<div role="alert" className="proc-error">{error}</div>}
 {Object.entries(recoveries).map(([key,x])=><div key={key} className="proc-warning">An action result needs saving. <button disabled={busy} onClick={()=>work(async()=>{const current=await repo.read(x.runId);replace(await repo.dispatch(current,x.event));setRecoveries(old=>{const v={...old};delete v[key];return v;});ctx.current.billingRefresh?.();x.open?.();}).catch(()=>{})}>Retry saving result</button></div>)}
 {designer?<Builder key={designer.id} definition={designer} templates={context.templates} onClose={()=>setDesigner(null)} onSave={d=>work(async()=>{const saved=await repo.save('template',d);setTemplates(old=>[saved,...old.filter(x=>x.id!==saved.id)]);return saved;})}/>:<>
 {tab==='library'&&<><div className="proc-actions"><button className="proc-primary" onClick={()=>setDesigner(makeDefinition())}>New process</button><button onClick={()=>{try{setDesigner(fromWithdrawal(context.withdrawalDefinition()));}catch(e){setError(e.message);}}}>Copy Withdrawal workflow</button><button onClick={()=>setDesigner(example())}>Example: parallel order process</button></div><div className="proc-library">{templates.map(d=><article key={d.id}><h3>{d.name}</h3><p>{d.nodes.length} blocks / Version {d.revision}</p><div className="proc-preview-icons">{d.nodes.map(n=><span key={n.id} title={n.name}>{n.icon}</span>)}</div><div className="proc-actions"><button onClick={()=>setDesigner(d)}>Edit process</button><button onClick={()=>{setDesigner({...copy(d),id:uid(),revision:0,name:d.name+' - copy'});}}>Duplicate</button><button onClick={()=>{setSelectedDef(d.id);setTab('runs');}}>Use for a matter</button></div></article>)}</div>{!templates.length&&<p className="proc-empty-inline">Create a process or copy your Withdrawal definition to inspect and arrange its blocks. Existing withdrawal cases are not altered.</p>}</>}
 {tab==='runs'&&<><section className="proc-start"><h2>Start a matter process</h2><div className="proc-actions"><Field label="Saved process" value={selectedDef} onChange={setSelectedDef} options={[{value:'',label:'Choose a process'},...templates.map(d=>({value:d.id,label:d.name}))]}/><Field label="Matter" value={matter} onChange={setMatter} options={[{value:'',label:'Choose a matter'},...context.matters.map(m=>({value:String(m.id),label:m.name+(m.cause_number?' / '+m.cause_number:'')}))]}/><button className="proc-primary" disabled={busy||!selectedDef||!matter} onClick={()=>{const def=templates.find(d=>d.id===selectedDef),m=context.matters.find(m=>String(m.id)===matter);if(window.confirm('Start '+def.name+' for '+m.name+'? Configured automatic actions may run on this page.'))work(async()=>{const s=await repo.save('run',startRun(def,m));replace(s);setExpanded(s.id);}).catch(()=>{});}}>Start process</button></div></section>
 <div className="proc-actions"><Field label="Find processes" value={query} onChange={setQuery}/><Field label="Show" value={filter} onChange={setFilter} options={[{value:'active',label:'Active / paused'},{value:'needs',label:'Needs my action'},{value:'waiting',label:'Waiting on others'},{value:'all',label:'All, including completed'}]}/></div>
 <div className="proc-runs">{visible.map(r=>{const pending=attention(r);return <article className="proc-run" key={r.id}><button className="proc-run-heading" onClick={()=>setExpanded(expanded===r.id?'':r.id)} aria-expanded={expanded===r.id}><div><strong>{r.matterName}</strong><span>{r.name}</span></div><span className={'proc-status '+r.status}>{r.status}</span></button><div className="proc-wait-list">{pending.map(a=><div key={a.nodeId} className={a.needsMe?'needs':''}><span>{a.icon}</span><strong>{a.message}</strong><small>Since {new Date(a.since).toLocaleDateString()} / {Math.floor(Math.max(0,Date.now()-Date.parse(a.since))/86400000)} days</small></div>)}{!pending.length&&<p>Process {r.status}. History retained below.</p>}</div>{expanded===r.id?<RunPanel run={r} control={control} context={context}/>:<History run={r}/>}</article>;})}</div>{!visible.length&&<p className="proc-empty-inline">No processes match this view.</p>}</>}
 </>}
 </div>;
}

// V314 successful-action review and input guards
