import {uid,reduceRun,billingIntent,validateDefinition} from './model.js';
export const texasDate=at=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(at));
export function repository(client,owner,billingContext=()=>null){
 const requireOwner=()=>{if(!owner)throw Error('Sign in before saving a process.');};
 const unwrap=data=>({...data.state,revision:Number(data.revision)});
 async function save(kind,state,revision=state.revision||0,billing=null){requireOwner();if(kind==='template')validateDefinition(state);const {data,error}=await client.rpc('mio_save_process_v314',{p_kind:kind,p_id:state.id,p_revision:revision,p_state:state,p_billing:billing});if(error)throw Error(error.code==='PT409'?'Changed in another window. Refresh before trying again.':error.message||String(error));if(!data?.state)throw Error('The database did not confirm the save.');return unwrap(data);}
 function bill(r,nid){const intent=billingIntent(r,nid);if(!intent)return null;const context=billingContext(r.matterId);if(!context||!context.user_member_id||context.rate==null||!Number.isFinite(Number(context.rate))||Number(context.rate)<0)throw Error('Choose a billing user and valid rate before this billed action.');const n=r.definition.nodes.find(n=>n.id===nid),hours=Math.round(intent.minutes/60*1e6)/1e6,rate=Number(context.rate),amount=Math.round(hours*rate*100)/100;const description=intent.description.replaceAll('{matter}',r.matterName).replaceAll('{block}',n.name);const payload={id:intent.id,entry_type:'time',matter_id:r.matterId,client_id:context.client_id||'',user_id:context.user_member_id,date:texasDate(intent.at),description,billing_time:hours,rate,amount,matter_step:r.name+' / '+n.name,matter_status:context.matter_status||'',process_id:r.id,process_node_id:nid,created_at:intent.at,non_billable:false,do_not_bill:false};return {...context,user_id:owner,id:intent.id,matter_id:r.matterId,entry_date:payload.date,description,billing_time:hours,rate,amount,matter_step:payload.matter_step,payload,do_not_bill:false};}
 return {save,
 async list(){requireOwner();const all=[];for(let offset=0;;offset+=200){const {data,error}=await client.from('mio_process_records').select('kind,id,state,revision').eq('owner_id',owner).order('id').range(offset,offset+199);if(error)throw Error(error.message);all.push(...(data||[]));if((data||[]).length<200)break;}return {templates:all.filter(x=>x.kind==='template').map(unwrap),runs:all.filter(x=>x.kind==='run').map(unwrap)};},
 async read(id){requireOwner();const {data,error}=await client.from('mio_process_records').select('state,revision').eq('owner_id',owner).eq('kind','run').eq('id',id).single();if(error)throw Error(error.message);return unwrap(data);},
 preflight(r,nid){const n=r.definition.nodes.find(n=>n.id===nid);if(n?.billing?.enabled)bill({...r,steps:{...r.steps,[nid]:{...r.steps[nid],performedAt:new Date().toISOString()}}},nid);},
 async dispatch(current,event){const at=new Date().toISOString();let next=reduceRun(current,{id:uid(),...event},at);if(next===current)return current;const billing=event.nodeId?bill(next,event.nodeId):null;if(billing)next=reduceRun(next,{id:uid(),type:'billed',nodeId:event.nodeId,billingId:billing.id},at);for(let i=current.history.length;i<next.history.length;i++){next.history[i].actor=owner;if(next.history[i].type==='billed'&&billing)next.history[i].amount=billing.amount;}return save('run',next,current.revision||0,billing);}
 };
}
