import React,{useEffect,useState} from 'react';
import {typeFor,messageFor,attention,prerequisites,copy} from './model.js';
import {ActionFields,Field} from './Fields.jsx';
export function History({run}){const[all,setAll]=useState(false);const history=run.history.filter(h=>all||!['activated','configured','action_started'].includes(h.type));return <section className="proc-history"><div className="proc-actions"><strong>Activity history</strong><label><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>Full audit trail</label></div><div className="proc-history-chain">{history.map(h=><div key={h.id} className={'proc-history-item '+(h.type==='billed'?'billed':'')} title={[h.message,h.description,h.reference,h.actor].filter(Boolean).join('\n')}><span className="proc-history-icon">{h.icon}</span><strong>{h.name}</strong><small>{h.type.replaceAll('_',' ')}</small><time dateTime={h.at}>{new Date(h.at).toLocaleString('en-US',{timeZone:'America/Chicago',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})} CT</time>{h.minutes&&<b>{h.minutes} min{h.amount!=null?' / $'+Number(h.amount).toFixed(2):''}</b>}</div>)}</div></section>;}
function Step({run,node,control,context}){
 const s=run.steps[node.id],[config,setConfig]=useState(()=>copy(s.config)),[dirty,setDirty]=useState(false),[reference,setReference]=useState(''),[note,setNote]=useState(''),[slot,setSlot]=useState(''),[document,setDocument]=useState('');
 const documents=context.documents.filter(d=>String(d.matter_id)===run.matterId),change=c=>{setConfig(c);setDirty(true);},send=(type,extra={})=>control.event(run,{type,nodeId:node.id,...extra});
 useEffect(()=>{if(!dirty)setConfig(copy(s.config));},[s.config,dirty]);
 const canEdit=!s.performedAt&&!s.responseReference&&['blocked','approval','ready','error'].includes(s.status),active=run.status==='active';
 return <section className="proc-step"><header><h3>{node.icon} {node.name}</h3><span className={'proc-status '+s.status}>{s.status}</span></header><p className={'proc-wait-message '+(s.status==='approval'?'needs':'')}>{messageFor(run,node)}</p>
 <div className="proc-step-grid"><div><fieldset disabled={!canEdit||!active||control.busy}><legend>Action details</legend>{['draft_email','esign_document'].includes(node.type)&&<p>Recipient: <strong>{context.recipientPreview(run,node,config)}</strong></p>}<ActionFields node={node} config={config} change={change} runtime documents={documents} templates={context.templates}/>{canEdit&&<button disabled={!dirty||control.busy} onClick={async()=>{const saved=await send('configure',{config});if(saved)setDirty(false);}}>Save action details</button>}</fieldset>
 {(node.config.inputSlots?.length||node.config.outputSlots?.length)>0&&<fieldset><legend>Shared documents</legend>{[...new Set([...(node.config.inputSlots||[]),...(node.config.outputSlots||[])])].map(id=><p key={id}>{run.definition.slots.find(x=>x.id===id)?.name}: <b>{run.documents[id]?.name||'Not attached / reviewed'}</b></p>)}<Field label="Document slot" value={slot} onChange={setSlot} options={[{value:'',label:'Choose slot'},...run.definition.slots.map(x=>({value:x.id,label:x.name}))]}/><Field label="Actual matter document" value={document} onChange={setDocument} options={[{value:'',label:'Choose document'},...documents.map(x=>({value:String(x.id),label:x.file_name||x.name||x.id}))]}/><button disabled={!slot||!document||control.busy||!active} onClick={()=>{const doc=documents.find(d=>String(d.id)===document);if(window.confirm('Confirm you reviewed '+(doc.file_name||doc.name)+' and it belongs in this slot?'))send('document',{slotId:slot,document:doc,confirmed:true});}}>Attach reviewed document</button></fieldset>}
 </div><div className="proc-step-actions"><h4>Next action</h4>{dirty&&<p className="proc-warning">Save the edited details before approving or performing this action.</p>}
 <fieldset disabled={control.busy||!active||dirty}>
 {s.status==='blocked'&&node.trigger==='manual'&&<button disabled={!prerequisites(run,node)} onClick={()=>send('start')}>Start this block</button>}
 {s.status==='approval'&&<button className="proc-primary" onClick={()=>send('approve')}>Approve action</button>}
 {s.status==='ready'&&!s.performedAt&&!s.responseReference&&!['manual','wait','approve'].includes(node.type)&&<button className="proc-primary" onClick={()=>control.execute(run,node)}>{typeFor(node.type).action}</button>}
 {s.status==='waiting'&&['draft_email','esign_document'].includes(node.type)&&<button onClick={()=>control.check(run,node)}>Check for response / signatures</button>}
 {node.billing.enabled&&<p>When the action occurs: <b>{node.billing.minutes} minutes</b><br/>{node.billing.description}</p>}
 <Field label="Actual completion / response reference" value={reference} onChange={setReference} placeholder="Sent email, filed envelope, document, or work performed"/>
 {['ready','waiting','error','running'].includes(s.status)&&<button disabled={!reference.trim()} onClick={()=>{if(window.confirm('Confirm this work was actually completed? This records completion and any configured billing; it does not send or file anything.'))send('complete',{confirmed:true,reference});}}>Record actual completion</button>}
 {s.status==='waiting'&&<button disabled={!reference.trim()} onClick={()=>send('signal',{confirmed:true,reference})}>Response received - needs my review</button>}
 {s.status==='blocked'&&node.trigger==='event'&&<button disabled={!reference.trim()} onClick={()=>send('signal',{signal:node.eventName,reference})}>Record event: {node.eventName}</button>}
 {['running','error'].includes(s.status)&&<><p className="proc-warning">Check the provider before retrying. The action may already have happened.</p><button disabled={!reference.trim()} onClick={()=>{if(window.confirm('Confirm you checked the provider and this action did NOT happen. Authorize another attempt?'))send('retry',{confirmed:true,reference});}}>Authorize retry after checking</button></>}
 </fieldset><Field label="Note / waiting message" value={note} onChange={setNote} rows={3}/><div className="proc-actions"><button disabled={!note.trim()||control.busy} onClick={()=>send('note',{message:note})}>Add note</button>{['ready','waiting'].includes(s.status)&&<button disabled={!note.trim()||control.busy||!active} onClick={()=>send('wait',{message:note})}>Set waiting message</button>}</div>
 </div></div></section>;
}
export default function RunPanel({run,control,context}){const [selected,setSelected]=useState(()=>attention(run)[0]?.nodeId||run.definition.nodes[0]?.id);const n=run.definition.nodes.find(n=>n.id===selected);return <div className="proc-run-panel"><div className="proc-actions"><span>Started {new Date(run.startedAt).toLocaleString()}</span><button disabled={control.busy||!['active','paused'].includes(run.status)} onClick={()=>control.event(run,{type:run.status==='paused'?'resume':'pause'})}>{run.status==='paused'?'Resume process':'Pause process'}</button><button className="proc-danger" disabled={control.busy||!['active','paused'].includes(run.status)} onClick={()=>{if(window.confirm('Cancel this process? Documents, billing and history will be retained.'))control.event(run,{type:'cancel',confirmed:true});}}>Cancel process</button></div><div className="proc-step-strip">{run.definition.nodes.map(n=><button key={n.id} className={'proc-mini '+run.steps[n.id].status+(selected===n.id?' selected':'')} onClick={()=>setSelected(n.id)}><span>{n.icon}</span><strong>{n.name}</strong><small>{run.steps[n.id].status}</small></button>)}</div>{n&&<Step key={run.id+':'+n.id} run={run} node={n} context={context} control={control}/>}<History run={run}/></div>;}

// V314 successful-action review and input guards

// V314 stable step editor
