import test from 'node:test'
import assert from 'node:assert/strict'
import {createWorkspaceService,revisionOf} from '../lib/ads/service.js'
const original={headlines:[{text:'Custody Lawyer'},{text:'Brazoria County'},{text:'Speak With The Firm'}],descriptions:[{text:'Discuss your family law matter.'},{text:'Contact the firm for next steps.'}],finalUrls:['https://beveridgelawfirm.com/contact'],path1:'',path2:''}
function fixture(options={}){
 let content=original, negatives=[],applied=false;const calls=[],entries=new Map();
 const db={byRequest:async id=>entries.get(id),history:async()=>[...entries.values()],get:async id=>[...entries.values()].find(e=>e.id===id),reserve:async e=>{if(entries.has(e.request_key))return{fresh:false,entry:entries.get(e.request_key)};entries.set(e.request_key,e);return{fresh:true,entry:e}},update:async(id,p)=>Object.assign([...entries.values()].find(e=>e.id===id),p)}
 const deps={accountId:'123',account:{id:'123',timeZone:'America/Chicago'},actor:{id:'u',email:'ben@beveridgelawfirm.com'},canWrite:options.canWrite!==false,db,
  query:async q=>{calls.push({kind:'query',q});if(options.queryFail&&q.includes(options.queryFail))throw new Error('Unavailable inventory');if(q.includes('FROM ad_group_ad'))return[{campaign:{id:'12',name:'Custody',status:'ENABLED'},adGroup:{id:'4',name:'Custody',status:'ENABLED'},adGroupAd:{status:'ENABLED',ad:{id:'5',type:'RESPONSIVE_SEARCH_AD',finalUrls:content.finalUrls,responsiveSearchAd:content},policySummary:{approvalStatus:'APPROVED'}}}];if(q.includes('FROM campaign_criterion'))return negatives;return[]},
  post:async(path,body)=>{calls.push({kind:'post',path,body});if(body.validateOnly){if(options.validationError)throw Object.assign(new Error('Invalid text'),{googlePayload:{error:{}}});return{payload:{},requestId:'valid'}}applied=true;if(options.uncertain)throw new Error('Network disconnected');if(path.endsWith('/ads:mutate')){if(!options.staleRead)content={...body.operations[0].update.responsiveSearchAd,finalUrls:body.operations[0].update.finalUrls};return{payload:{results:[{resourceName:'customers/123/ads/5'}]},requestId:'applied'}}negatives=body.operations.map(op=>({campaign:{id:op.create.campaign.split('/').pop()},campaignCriterion:{status:'ENABLED',keyword:op.create.keyword}}));return{payload:options.partial?{results:[{resourceName:'customers/123/campaignCriteria/12~1'},{}],partialFailureError:{details:[{errors:[{message:'Rejected item',location:{fieldPathElements:[{fieldName:'operations',index:1}]}}]}]}}:{results:negatives.map((_,i)=>({resourceName:`customers/123/campaignCriteria/12~${i+1}`}))},requestId:'applied'}},
  ai:async()=>({summary:'Suggested wording',headlines:original.headlines.map(a=>a.text),descriptions:original.descriptions.map(a=>a.text),evidence:[{term:'invented term',reason:'unsupported'}],warnings:[]})};
 const service=createWorkspaceService(deps);return{service,calls,entries,get applied(){return applied}}
}
const update=()=>({kind:'rsa_update',confirmation:'APPLY',requestId:'11111111-1111-4111-8111-111111111111',adId:'5',adGroupId:'4',expectedRevision:revisionOf(original),references:[{campaignId:'12',adGroupId:'4'}],draft:{...original,headlines:[{text:'Custody Help In Brazoria'},...original.headlines.slice(1)]}})
test('authorization and explicit APPLY are checked before requests',async()=>{for(const [opts,request]of[[{canWrite:false},update()],[{}, {...update(),confirmation:''}]]){const f=fixture(opts);await assert.rejects(f.service.apply(request));assert.equal(f.calls.length,0)}})
test('RSA validation precedes mutation and fresh read back verifies',async()=>{const f=fixture(),r=await f.service.apply(update()),p=f.calls.filter(c=>c.kind==='post');assert.equal(p[0].body.validateOnly,true);assert.equal(p[1].body.validateOnly,false);assert.equal(r.results[0].state,'verified');assert.equal(p[1].body.operations[0].update.status,undefined);assert.match(p[1].body.operations[0].updateMask,/responsiveSearchAd.headlines/);assert.equal([...f.entries.values()][0].before_snapshot.ad.headlines[0].text,'Custody Lawyer')})
test('stale draft and changed ad references cannot publish',async()=>{for(const patch of[{expectedRevision:'stale'},{references:[]}]){const f=fixture();await assert.rejects(f.service.apply({...update(),...patch}),/changed|Refresh|refresh/);assert.equal(f.applied,false)}})
test('validation error prevents any live write',async()=>{const f=fixture({validationError:true});const r=await f.service.apply(update());assert.equal(r.results[0].state,'failed');assert.equal(f.applied,false)})
test('same approval cannot mutate twice even after network uncertainty',async()=>{for(const uncertain of[false,true]){const f=fixture({uncertain});const r=await f.service.apply(update());await f.service.apply(update());assert.equal(f.calls.filter(c=>c.kind==='post').length,2);if(uncertain)assert.equal(r.results[0].state,'unverified')}})
test('read back mismatch never displays verified',async()=>{const f=fixture({staleRead:true});const r=await f.service.apply(update());assert.equal(r.results[0].state,'unverified')})
test('bulk dedup is campaign-specific and partial results mapped',async()=>{const f=fixture({partial:true});const item={campaignId:'12',keyword:'other lawyer'};const r=await f.service.apply({kind:'campaign_negatives',confirmation:'APPLY',requestId:'22222222-2222-4222-8222-222222222222',items:[item,item,{...item,campaignId:'13'}]});assert.equal(r.results.filter(r=>r.state==='skipped').length,1);assert.equal(r.results.filter(r=>r.state==='verified').length,1);assert.equal(r.results.filter(r=>r.state==='failed').length,1);assert.equal(f.calls.filter(c=>c.kind==='post')[1].body.operations[1].create.campaign,'customers/123/campaigns/13')})
test('incomplete inventory blocks campaign negative mutation',async()=>{const f=fixture({queryFail:'FROM campaign_criterion'});await assert.rejects(f.service.apply({kind:'campaign_negatives',confirmation:'APPLY',requestId:'22222222-2222-4222-8222-222222222222',items:[{campaignId:'12',keyword:'other lawyer'}]}));assert.equal(f.applied,false)})
test('AI cannot mutate and unsupported evidence is not used',async()=>{const f=fixture();const r=await f.service.suggest({adId:'5',adGroupId:'4'});assert.equal(f.calls.filter(c=>c.kind==='post').length,0);assert.equal(r.evidence.length,0);assert.ok(r.warnings.length)})
