import test from 'node:test'
import assert from 'node:assert/strict'
import * as m from '../lib/ads/model.js'
const draft={headlines:[{text:'Custody Lawyer',pinnedField:'HEADLINE_1'},{text:'Brazoria County'},{text:'Speak With The Firm'}],descriptions:[{text:'Discuss your family law matter with the firm.'},{text:'Get help understanding your next steps.'}],finalUrls:['https://beveridgelawfirm.com/contact'],path1:'custody',path2:''}
const item={campaignId:'12',searchTerm:'shane kersh attorney',keyword:'shane kersh attorney',matchType:'EXACT'}
test('RSA preserves allowed fields and validates bounds',()=>{assert.deepEqual(m.normalizeAdDraft(draft),draft);for(const patch of [{headlines:draft.headlines.slice(0,2)},{headlines:[{text:'x'.repeat(31)},...draft.headlines.slice(1)]},{finalUrls:['javascript:alert(1)']},{headlines:[{text:'Test',pinnedField:'DESCRIPTION_1'},...draft.headlines.slice(1)]},{path1:'',path2:'test'}])assert.throws(()=>m.normalizeAdDraft({...draft,...patch}))})
test('bulk is exact by default, campaign separated and deduplicated',()=>{const p=m.prepareNegatives([{...item,matchType:undefined},item,{...item,campaignId:'13'}],[]);assert.equal(p.ready.length,2);assert.equal(p.skipped.length,1);assert.equal(p.ready[0].matchType,'EXACT')})
test('campaign phrase covers exact but exact cannot cover proposed phrase',()=>{assert.equal(m.prepareNegatives([item],[{scope:'campaign',campaignId:'12',keyword:'shane kersh',matchType:'PHRASE'}]).ready.length,0);assert.equal(m.prepareNegatives([{...item,keyword:'shane kersh',matchType:'PHRASE'}],[{scope:'campaign',campaignId:'12',keyword:'shane kersh',matchType:'EXACT'}]).ready.length,1)})
test('negative match is literal exact/phrase/broad, never guessed variants',()=>{assert.equal(m.negativeMatches('lawyer shane kersh',{keyword:'shane kersh',matchType:'PHRASE'}),true);assert.equal(m.negativeMatches('shane lawyer kersh',{keyword:'shane kersh',matchType:'PHRASE'}),false);assert.equal(m.negativeMatches('lawyers',{keyword:'lawyer',matchType:'BROAD'}),false)})
test('ad-group negative is not campaign coverage and paused exact is not active',()=>{assert.equal(m.prepareNegatives([item],[{scope:'ad_group',campaignId:'12',keyword:item.keyword,matchType:'EXACT'}]).ready.length,1);const row={...item,adGroupId:'4'};assert.equal(m.termStatus(row,{keywords:[{...row,negative:false,status:'PAUSED'}]}).kind,'exact_paused')})
test('column preferences keep required term and ignore unknown fields',()=>{assert.deepEqual(m.sanitizeColumns(['cost','wrong']),['searchTerm','cost']);assert.ok(m.sanitizeColumns(null).includes('intent'))})
test('aggregate computes weighted rates',()=>{const r=m.aggregateMetrics([{impressions:100,clicks:2,cost:10,conversions:0},{impressions:900,clicks:18,cost:90,conversions:2}]);assert.equal(r.ctr,.02);assert.equal(r.averageCpc,5);assert.equal(r.costPerConversion,50)})
test('row identity is not shared between different campaigns',()=>assert.notEqual(m.termKey(item),m.termKey({...item,campaignId:'13'})))
