import React,{useState} from 'react'
import{createRoot}from'react-dom/client'
import MioAdsWorkspace from '../src/ads/Workspace.jsx'
const ad={id:'5',adGroupId:'4',adGroupName:'Custody',campaignId:'12',campaignName:'Child Custody',type:'RESPONSIVE_SEARCH_AD',status:'ENABLED',campaignStatus:'PAUSED',adGroupStatus:'ENABLED',approvalStatus:'APPROVED',reviewStatus:'REVIEWED',adStrength:'GOOD',primaryStatus:'CAMPAIGN_PAUSED',headlines:[{text:'Custody Lawyer',pinnedField:'HEADLINE_1'},{text:'Brazoria County'},{text:'Talk With The Firm'}],descriptions:[{text:'Discuss your family law matter with our firm.'},{text:'Contact us to learn about your next steps.'}],path1:'custody',path2:'',finalUrls:['https://beveridgelawfirm.com/contact'],revision:'test-revision',metrics:{clicks:5,cost:25,impressions:100,ctr:.05,conversions:0}}
const mk=(searchTerm,campaignId='12')=>({searchTerm,campaignId,campaignName:campaignId==='12'?'Child Custody':'Divorce',adGroupId:campaignId==='12'?'4':'8',adGroupName:campaignId==='12'?'Custody':'Divorce',clicks:1,impressions:10,cost:5,conversions:0,device:'MOBILE',triggeringKeyword:'custody lawyer',matchType:'PHRASE',keywordMatchType:'PHRASE'})
const data={ok:true,ads:[ad],searchTerms:[mk('other law firm'),mk('custody attorney'),mk('already blocked'),mk('other law firm','13')],negativeKeywords:[{scope:'campaign',campaignId:'12',keyword:'already blocked',matchType:'EXACT'}],keywords:[],coverageComplete:true,range:{days:30,start:'2026-08-14',end:'2026-09-12'},warnings:[],fetchedAt:'2026-09-12T12:00:00Z'}
window.__calls=[];window.__saved=[];window.__failNext=false
const api=async(action,opts={})=>{window.__calls.push({action,...opts});if(action==='workspace_snapshot')return structuredClone(data);if(action==='workspace_apply'){if(window.__failNext){window.__failNext=false;throw new Error('Simulated network failure')}if(opts.body.kind==='campaign_negatives'){data.negativeKeywords.push(...opts.body.items.map(i=>({...i,scope:'campaign'})));return{ok:true,results:opts.body.items.map(i=>({...i,state:'verified',message:'Confirmed by Google'}))}}Object.assign(ad,opts.body.draft);return{ok:true,results:[{state:'verified',message:'Confirmed by Google'}]}}if(action==='workspace_history')return{entries:[]};if(action==='workspace_suggest')return{draft:{...ad,headlines:[{text:'New Suggested Custody Help'},...ad.headlines.slice(1)]},summary:'Test suggestion',evidence:[{term:'custody attorney',reason:'Relevant same-group query'}],warnings:[]};if(action==='workspace_audience')return{ok:true,age:[{label:'35-44',clicks:2,cost:10,impressions:50,conversions:0}],gender:[{label:'UNKNOWN',clicks:2,cost:10,impressions:50,conversions:0}],locations:[{label:'Pearland, Texas',locationType:'LOCATION_OF_PRESENCE',clicks:2,cost:10,impressions:50,conversions:0}],warnings:[]};return{}}
const preferences={load:async()=>null,save:async columns=>{window.__saved.push(columns)}}
function Harness(){const[mode,setMode]=useState('search_terms');return<><button onClick={()=>setMode('search_terms')}>Test Search</button><button onClick={()=>setMode('ads')}>Test Ads</button><MioAdsWorkspace mode={mode} report={data} api={api} onRefresh={async()=>{}} writeMode={{ready:true}} queueMutation={m=>window.__calls.push({action:'queue',mutation:m})} classify={t=>({label:t.includes('attorney')?'High hiring intent':'Needs review',kind:t.includes('attorney')?'hire':'review'})} preferences={preferences}/></>}
createRoot(document.getElementById('root')).render(<Harness/> )
