import test from 'node:test'
import assert from 'node:assert/strict'
import {normalizeSubmission,submissionIdentity,leadDraft} from '../supabase/functions/formspree-webhook/model.js'
const payload={form:'xljrjjog',submission:{name:'Example Person',email:'person@example.com',phone:'22577314442','family-type':'Protective Order',matter:'family',message:'Need help',_date:'2026-09-16T16:19:47Z','opposing-party':'Other Person',deadline:'09/29/2026','preferred-contact':'Phone'}}
test('real nested payload preserves contact and hyphenated fields',()=>{const n=normalizeSubmission(payload);assert.equal(n.full_name,'Example Person');assert.equal(n.phone,'22577314442');assert.equal(n.family_type,'Protective Order');assert.equal(n.opposing_party,'Other Person');assert.equal(n.deadline,'09/29/2026');assert.equal(n.form_id,'xljrjjog');assert.equal(n.submitted_at,'2026-09-16T16:19:47Z')})
test('repeat webhook identity is stable, distinct dated submissions remain distinct',()=>{assert.equal(submissionIdentity(payload),submissionIdentity(JSON.parse(JSON.stringify(payload))));assert.notEqual(submissionIdentity(payload),submissionIdentity({...payload,submission:{...payload.submission,_date:'2026-09-17T16:19:47Z'}}));assert.equal(submissionIdentity({data:{name:'A',email:'a@example.com'}}),submissionIdentity({data:{email:'a@example.com',name:'A'}}))})
test('spam nested in submission is excluded',()=>{assert.equal(normalizeSubmission({...payload,submission:{...payload.submission,_spam:true}}).is_spam,true)})
test('preview proposes only available case types and fixed PNC status',()=>{const d=leadDraft({raw_submission:payload},[{name:'Other'},{name:'SAPCR/Modification'}]);assert.equal(d.first_name,'Example');assert.equal(d.last_name,'Person');assert.equal(d.case_type,'Other');assert.equal(d.matter_status,'PNC- Need to Consult');assert.equal(d.matter_name,'Example Person - Protective Order');assert.match(d.notes,/Other Person/);assert.match(d.notes,/09\/29\/2026/)})
test('single names and incomplete contacts are preserved for review',()=>{const d=leadDraft({raw_submission:{submission:{name:'Christopher',phone:'5551234'}}},[{name:'Other'}]);assert.equal(d.first_name,'Christopher');assert.equal(d.last_name,'');assert.equal(d.email,'');assert.equal(d.phone,'5551234')})
test('sending an agreement first locks its retainer amount before a payment link exists',async()=>{const {retainerAmountLocked}=await import('../src/mioPncModel.js');assert.equal(retainerAmountLocked({signature:{id:'sent-agreement'}}),true);assert.equal(retainerAmountLocked({signature_sending:'pending'}),true);assert.equal(retainerAmountLocked({retainer_request:{id:'request'}}),true);assert.equal(retainerAmountLocked({signature:{status:'not_sent'}}),false)})
