import React from 'react'
import {createRoot} from 'react-dom/client'
import KeywordLab from '../src/ads/KeywordLab.jsx'
const make=(id,keyword,matchType,impressions,clicks,cost)=>({criterionId:id,criterionResourceName:`customers/123/adGroupCriteria/4~${id}`,campaignId:'12',campaignName:'Custody',adGroupId:'4',adGroupName:'Lawyers',keyword,matchType,status:'ENABLED',revision:`revision-${id}`,impressions,clicks,cost,conversions:0,ctr:clicks/impressions,averageCpc:cost/clicks,impressionsPerDay:impressions/30,clicksPerDay:clicks/30,costPerDay:cost/30,searchTermCount:1,classifiedSpendCoverage:1,relevantClickRate:1,relevantSpendRate:1,wasteRate:0})
const keywords=[make('7','custody lawyer','PHRASE',300,30,60),make('8','family attorney','EXACT',100,2,10)]
const term={campaignId:'12',campaignName:'Custody',adGroupId:'4',adGroupName:'Lawyers',searchTerm:'custody lawyer near me',triggeringKeyword:'custody lawyer',triggeringKeywordMatchType:'PHRASE',triggeringKeywordResourceName:keywords[0].criterionResourceName,triggeringCriterionId:'7',matchType:'PHRASE',device:'MOBILE',impressions:100,clicks:10,cost:20,ctr:.1,averageCpc:2,impressionsPerDay:100/30,clicksPerDay:10/30,costPerDay:20/30,conversions:0,classification:'observe',negativeCoverage:null,keywordCoverage:null}
const experiment={...keywords[0],id:'exp-1',state:'active',source:'planner',hypothesis:'Relevant traffic test',experimentStartedAt:'2026-09-01T12:00:00Z',effectiveStartDate:'2026-09-01',days:13,approvedBy:'reviewer',updatedAt:'2026-09-01T12:00:00Z',impressions:130,impressionsPerDay:10}
window.__calls=[];window.__saved=[];window.__failApply=false;window.__snapshotFail=false
const api=async(action,options={})=>{window.__calls.push({action,...options});if(action==='keyword_lab_snapshot'){if(window.__snapshotFail)throw Error('Snapshot unavailable');return structuredClone({ok:true,keywords,searchTerms:[term],negativeKeywords:[],liveActionsEnabled:true,inventoryComplete:true,coverageComplete:true,writeMode:{ready:true},account:{currencyCode:'USD'},range:{startDate:options.params?.startDate||'2026-08-15',endDate:options.params?.endDate||'2026-09-13',days:30,timeZone:'America/Chicago'}})}if(action==='keyword_experiments')return{experiments:[structuredClone(experiment)]};if(action==='workspace_history')return{entries:[]};if(action==='keyword_classify_term'){term.classification=options.body.classification;return{ok:true}}if(action==='keyword_candidates')return{planner:{available:true},candidates:[{phrase:'custody help',source:'planner',avgMonthlySearches:100,monthlyVolumes:[{year:2026,month:'AUGUST',searches:100}],competition:'HIGH',competitionIndex:75,lowBid:2,highBid:7}]};if(action==='keyword_review')return{reviewId:'review-1',requestId:options.body.requestId,fingerprint:'reviewed',items:options.body.items.map(i=>({...i,campaignName:'Custody',adGroupName:'Lawyers',original:i.criterionResourceName?keywords.find(k=>k.criterionResourceName===i.criterionResourceName):null}))};if(action==='keyword_apply'){if(window.__failApply)throw Error('Simulated uncertain network result');return{eventId:'apply-1',status:'verified',results:options.body.items.map(item=>({id:item.id,item,state:'verified',message:'Confirmed in fixture'}))}}if(action==='keyword_verify')return{eventId:'apply-1',status:'verified',results:[]};if(action==='keyword_experiment_update'){if(options.body.action==='promote_to_core')experiment.state='promoted_to_core';return{ok:true}}throw Error(`Unexpected fixture action ${action}`)}
const preferences={load:async()=>({}),save:async value=>window.__saved.push(value)}
createRoot(document.getElementById('root')).render(<KeywordLab api={api} preferences={preferences} writeMode={{ready:true}}/>)
