import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import {dailyTrustSummary,entryCents,firmDate} from '../src/mioDailyTrust.js'
import {paymentEvidence,signatureEvidence,readyToClient,zonedDateTime,DEFAULT_INTAKES,PNC_DEFAULTS,templateText} from '../src/mioPncModel.js'
const day='2026-09-09',entry=(id,amount,matter_id='a',extra={})=>({id,amount,matter_id,date:day,...extra}),matter=id=>({id,name:id,matter_type:'Divorce'})
const summary=(entries,finances={},matters=[matter('a'),matter('b')])=>dailyTrustSummary({date:day,entries,matters,financeFor:m=>({trust:0,wip:0,outstanding:0,uninvoicedEntries:entries.filter(e=>e.matter_id===m.id&&!e.invoice_id),financialSnapshotResolved:true,...finances[m.id]})})
test('trust is allocated once per matter and not pooled across clients',()=>{const s=summary([entry('1',300),entry('2',300),entry('3',500,'b')],{a:{trust:400,wip:600},b:{trust:9000,wip:500}});assert.equal(s.covered,90000);assert.equal(s.uncovered,20000);assert.equal(s.total,110000)})
test('DFPS classified by type, separately from available trust',()=>{const s=summary([entry('1',200),entry('2',250,'b')],{a:{trust:9999},b:{trust:100,wip:250}},[{...matter('a'),matter_type:'Dfps'},matter('b')]);assert.equal(s.dfps,20000);assert.equal(s.nonDfps,25000);assert.equal(s.covered,10000)})
test('older fees reserve trust before the selected day',()=>{const s=summary([entry('1',300)],{a:{trust:500,wip:400,outstanding:250}});assert.equal(s.covered,15000);assert.equal(s.rows[0].reserved,35000)})
test('pending deposits are not added to trust',()=>{const s=dailyTrustSummary({date:day,entries:[entry('1',200)],matters:[matter('a')],pendingFor:()=>5000,financeFor:()=>({trust:0,wip:200,uninvoicedEntries:[{id:'1'}],financialSnapshotResolved:true})});assert.equal(s.covered,0);assert.equal(s.rows[0].pending,500000)})
test('explicit zero, do not bill, deleted and duplicated entries',()=>{assert.equal(entryCents({amount:0,billing_time:1,rate:300}),0);const s=summary([entry('1',50),entry('1',50),entry('2',30,'a',{do_not_bill:true}),entry('3',80,'a',{deleted_at:day}),entry('4',100,'a',{date:'2026-09-08'})],{a:{trust:100,wip:50}});assert.equal(s.total,5000)})
test('a partially paid invoice never counts the paid portion again',()=>{const entries=[entry('1',300,'a',{invoice_id:'i'})];const s=summary(entries,{a:{trust:1000,wip:0,outstanding:300,serviceInvoices:[{id:'i',status:'outstanding',total:500,balance:300,line_items:[{date:'2026-09-08',amount:200,billing_entry_id:'old'},{date:day,amount:300,billing_entry_id:'1'}]}]}});assert.equal(s.covered,30000);assert.equal(s.paid,0)})
test('a fully paid invoice is not available for another transfer',()=>{const s=summary([entry('1',300,'a',{invoice_id:'i'})],{a:{trust:9000,serviceInvoices:[{id:'i',status:'paid',total:300,balance:0,line_items:[{date:day,amount:300,billing_entry_id:'1'}]}]}});assert.equal(s.covered,0);assert.equal(s.paid,30000)})
test('missing case, finance or invoice allocation remains unknown',()=>{for(const f of [{financialSnapshotResolved:false},{uninvoicedEntries:[]}])assert.equal(summary([entry('1',100)],{a:{trust:500,...f}}).unknown,10000);assert.equal(summary([entry('1',100,'missing')]).unknown,10000)})
test('draft invoices reserve funds and opening AR is not lost',()=>{const s=summary([entry('1',100)],{a:{trust:200,wip:100,openingOutstanding:50,outstanding:50,serviceInvoices:[{id:'old',total:100,balance:100,status:'draft',line_items:[]}]}});assert.equal(s.covered,5000)})
test('firm date uses Texas time rather than UTC',()=>assert.equal(firmDate(new Date('2026-09-10T01:00:00Z')),day))
const req={id:'request',account_key:'trust',amount_cents:500000,reference:'PNC-retainer-unique',invoice_number:'PNC-retainer-unique'}
const tx=(id,status,amount=500000,extra={})=>({gateway_transaction_id:id,status,amount_cents:amount,reference:req.reference,account_key:'trust',currency:'USD',...extra})
test('retainer processing satisfies onboarding, not merely visiting a link',()=>{assert.equal(paymentEvidence([],req).status,'not_paid');assert.equal(paymentEvidence([tx('t','processing')],req).status,'processing');assert.equal(paymentEvidence([tx('t','COMPLETED')],req).status,'paid');assert.equal(paymentEvidence([tx('t','authorized',10000)],req).status,'partial')})
test('payment correlation excludes wrong matter, account, failed and unknown statuses',()=>{for(const bad of [tx('t','completed',500000,{reference:'other'}),tx('t','completed',500000,{account_key:'operating'}),tx('t','not_paid'),tx('t','failed'),tx('t','')])assert.equal(paymentEvidence([bad],req).status,'not_paid')})
test('echeck trust can satisfy the trust retainer, never operating',()=>{assert.equal(paymentEvidence([tx('t','pending',500000,{account_key:'echeck_trust'})],req).status,'processing');assert.equal(paymentEvidence([tx('t','completed',500000,{account_key:'echeck_operating'})],req).status,'not_paid')})
test('partial payments combine; duplicates and refunds do not inflate receipt',()=>{assert.equal(paymentEvidence([tx('a','paid',200000),tx('b','processing',300000),tx('b','processing',300000)],req).status,'processing');assert.equal(paymentEvidence([tx('a','paid',500000,{amount_refunded_cents:1000})],req).status,'partial');assert.equal(paymentEvidence([tx('a','paid'),tx('b','completed',1000,{transaction_type:'refund'})],req).status,'needs_review')})
test('test signatures and incomplete signatures cannot advance',()=>{assert.equal(signatureEvidence({is_complete:true,test_mode:true}).status,'test');assert.equal(readyToClient({signature:{status:'signed'},retainer:{status:'partial'}}),false);assert.equal(readyToClient({signature:{status:'signed'},retainer:{status:'processing'}}),true)})
test('four editable intake types, retainer default and email variables',()=>{assert.equal(DEFAULT_INTAKES.length,4);assert.equal(PNC_DEFAULTS.retainer,5000);assert.equal(PNC_DEFAULTS.consult_fee,'');assert.equal(templateText('Hello {{client_name}}',{client_name:'Example'}),'Hello Example');assert.ok(DEFAULT_INTAKES.every(t=>t.questions.length&&new Set(t.questions.map(q=>q.key)).size===t.questions.length))})
test('calendar converts Central time, rejects invalid or ambiguous DST times',()=>{assert.equal(zonedDateTime('2026-09-15T09:30').toISOString(),'2026-09-15T14:30:00.000Z');assert.throws(()=>zonedDateTime('2026-03-08T02:30'));assert.throws(()=>zonedDateTime('2026-11-01T01:30'));assert.throws(()=>zonedDateTime('invalid'))})
test('source contains no manual paid/signed override and retains server gate',()=>{const api=fs.readFileSync('lib/pnc.js','utf8');assert.ok(api.includes('if(!readyToClient(state))'));assert.ok(api.includes('test_mode:false'));assert.ok(!api.includes('SERVICE_ROLE_KEY'));assert.ok(api.includes("account=purpose==='consult'?'operating':'trust'"));assert.ok(api.includes("u.searchParams.set('amount',(Number(r.amount_cents)/100).toFixed(2))"))})
