// Execute the real server handler with mocked Supabase/provider boundaries.
import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import * as crypto from 'node:crypto'
import * as model from '../src/mioPncModel.js'
import * as config from '../src/mioSupabasePublic.js'
const raw=fs.readFileSync('lib/pnc.js','utf8').replace(/^import .*\n/gm,'').replace('export default async function','async function')
const mid='00000000-0000-4000-8000-000000000001',uid='owner',clone=x=>JSON.parse(JSON.stringify(x))
function fixture(){
 const f={user:{id:uid,email:'test@beveridgelawfirm.com',email_confirmed_at:'2026-01-01'},transactions:[],requests:[],providerCalls:[],failProvider:false,signComplete:false,testMode:false}
 const w={matter_id:mid,user_id:uid,client_id:'client',creation_key:'key',config:{consult_fee:125,retainer:5000,signature_template_id:'template',signer_role:'Client'},state:{},revision:0}
 const m={id:mid,client_id:'client',name:'Example PNC',matter_type:'Divorce',matter_status:model.PNC_STATUS,clients:{id:'client',first_name:'Example',last_name:'Person',email:'example@invalid.test'}}
 const tables={mio_pnc_workflows:[w],matters:[m],lawpay_payment_requests:f.requests,lawpay_transactions:[],lawpay_settings:[{id:1,operating_page_url:'https://secure.lawpay.com/operating',trust_page_url:'https://secure.lawpay.com/trust'}],mio_client_intake_requests:[]}
 function from(table){let filters=[],mutation=null,max=Infinity;const q={select(){return q},eq(k,v){filters.push(r=>r[k]===v);return q},in(k,v){filters.push(r=>v.includes(r[k]));return q},or(){return q},order(){return q},limit(n){max=n;return q},update(v){mutation={type:'update',v};return q},insert(v){mutation={type:'insert',v};return q},async single(){return execute(true,true)},async maybeSingle(){return execute(true,false)},then(resolve,reject){return Promise.resolve(execute(false,false)).then(resolve,reject)}}
  function execute(single,required){let rows=(tables[table]||[]).filter(r=>filters.every(fn=>fn(r))).slice(0,max);if(mutation?.type==='update'){rows.forEach(r=>Object.assign(r,clone(mutation.v)))}if(mutation?.type==='insert'){rows=[clone(mutation.v)];(tables[table]||=[]).push(...rows)}if(single&&required&&!rows[0])return {data:null,error:{message:'No matching row'}};return {data:clone(single?rows[0]||null:rows),error:null}}
  return q
 }
 const db={from,auth:{getUser:async()=>({data:{user:f.user},error:null})},functions:{async invoke(name,{body}){if(name==='pnc-payment-status')return {data:{ok:true,transactions:f.transactions},error:null};assert.equal(name,'lawpay-gateway');assert.equal(body.action,'create_link');f.requests.push({...body,id:'request-'+f.requests.length,created_by:uid,payment_url:body.payment_page_url+'?amount='+body.amount_cents,created_at:'2026-01-01'});return {data:{url:f.requests.at(-1).payment_url},error:null}}}}
 const provider=async(url,options)=>{f.providerCalls.push({url,options});if(f.failProvider)throw Error('Synthetic provider outage');if(url.includes('/template/'))return {ok:true,json:async()=>({template:{signer_roles:[{name:'Client'}],cc_roles:[],documents:[{custom_fields:[{name:'client_name'},{name:'retainer'}]}]}})};return {ok:true,json:async()=>({signature_request:{signature_request_id:'sign',is_complete:f.signComplete,test_mode:f.testMode,signing_url:'https://example.invalid/sign',metadata:{mio_pnc_matter_id:mid,mio_pnc_user_id:uid}}})}}
 const args={createClient:()=>db,randomBytes:crypto.randomBytes,randomUUID:crypto.randomUUID,createHash:crypto.createHash,...model,...config,fetch:provider,process:{env:{SUPABASE_URL:'https://db.invalid',SUPABASE_ANON_KEY:'public-test-only',DROPBOX_SIGN_API_KEY:'test-only'}}}
 const handler=new Function(...Object.keys(args),raw+'\nreturn pncHandler')(...Object.values(args))
 f.w=w;f.m=m;f.tables=tables;f.call=async(action,body={},headers={authorization:'Bearer test-only',host:'example.invalid'})=>{let response;const res={setHeader(){},status(n){res.code=n;return res},json(data){response={code:res.code,body:data};return response}};await handler({method:'POST',query:{integration:'pnc'},body:{action,matter_id:mid,...body},headers},res);return response};return f
}
test('server denies anonymous and client-portal users',async()=>{const f=fixture();assert.equal((await f.call('list',{},{})).code,401);f.user.email='client@example.invalid';assert.equal((await f.call('list')).code,403)})
test('create consult link is operating, correctly denominated and reusable',async()=>{const f=fixture();const a=await f.call('prepare_consult');assert.equal(a.code,200);assert.equal(f.requests[0].account_key,'operating');assert.equal(f.requests[0].amount_cents,12500);assert.equal(new URL(a.body.workflow.state.consult_request.url).searchParams.get('amount'),'125.00');assert.equal((await f.call('prepare_consult')).code,200);assert.equal(f.requests.length,1);assert.equal(f.providerCalls.length,0)})
test('stale settings and post-link amount edits are rejected',async()=>{const f=fixture();assert.equal((await f.call('save',{revision:9,config:{consult_fee:1}})).code,409);await f.call('prepare_consult');assert.equal((await f.call('save',{revision:f.w.revision,config:{consult_fee:250}})).code,409);assert.equal(f.w.config.consult_fee,125)})
test('signature needs confirmation, is idempotent and merges actual template fields',async()=>{const f=fixture();f.m.matter_status=model.CONSULT_STATUS;assert.equal((await f.call('prepare_engagement')).code,200);assert.equal(f.requests[0].account_key,'trust');assert.equal((await f.call('send_signature')).code,400);assert.equal(f.w.state.signature_sending,undefined);assert.equal((await f.call('send_signature',{confirmed:true})).code,200);assert.equal((await f.call('send_signature',{confirmed:true})).code,200);const calls=f.providerCalls.filter(x=>x.url.includes('send_with_template'));assert.equal(calls.length,1);const b=JSON.parse(calls[0].options.body);assert.equal(b.test_mode,false);assert.equal(b.custom_fields.find(x=>x.name==='retainer').value,'$5,000.00');assert.equal(b.signers[0].email_address,'example@invalid.test')})
test('partial and absent provider receipts cannot advance, even with stale paid badge',async()=>{const f=fixture();f.m.matter_status=model.CONSULT_STATUS;await f.call('prepare_engagement');await f.call('send_signature',{confirmed:true});f.signComplete=true;f.w.state.retainer={status:'paid'};assert.equal((await f.call('advance',{confirmed:true})).code,409);assert.equal(f.m.matter_status,model.CONSULT_STATUS);const r=f.requests[0];f.transactions=[{gateway_transaction_id:'tx',reference:r.reference,account_key:'trust',currency:'USD',amount_cents:100000,status:'processing'}];assert.equal((await f.call('advance',{confirmed:true})).code,409);f.transactions[0].amount_cents=500000;assert.equal((await f.call('advance',{confirmed:true})).code,200);assert.equal(f.m.matter_status,model.CLIENT_STATUS)})
test('missing request and changed amount fail closed',async()=>{const f=fixture();f.m.matter_status=model.CONSULT_STATUS;f.w.state={signature:{id:'sign',status:'signed'},retainer:{status:'paid'}};f.signComplete=true;assert.equal((await f.call('advance',{confirmed:true})).code,409);await f.call('prepare_engagement');f.requests[0].amount_cents=100;f.transactions=[{gateway_transaction_id:'tx',reference:f.requests[0].reference,account_key:'trust',currency:'USD',amount_cents:100,status:'paid'}];assert.equal((await f.call('advance',{confirmed:true})).code,409)})
test('provider outage and test-mode signatures cannot satisfy final gate',async()=>{const f=fixture();f.m.matter_status=model.CONSULT_STATUS;await f.call('prepare_engagement');f.w.state.signature={id:'sign',status:'signed'};const r=f.requests[0];f.transactions=[{gateway_transaction_id:'tx',reference:r.reference,account_key:'trust',currency:'USD',amount_cents:500000,status:'paid'}];f.failProvider=true;assert.equal((await f.call('advance',{confirmed:true})).code,409);assert.equal(f.w.state.signature.status,'unverified');f.failProvider=false;f.signComplete=true;f.testMode=true;assert.equal((await f.call('advance',{confirmed:true})).code,409)})
test('email retries need review and calendar retries reuse transaction ID',async()=>{const f=fixture();const a=await f.call('claim_delivery',{kind:'calendar'}),b=await f.call('claim_delivery',{kind:'calendar'});assert.equal(a.body.workflow.state.calendar_delivery.reference,b.body.workflow.state.calendar_delivery.reference);assert.equal((await f.call('claim_delivery',{kind:'consult'})).code,200);assert.equal((await f.call('claim_delivery',{kind:'consult'})).code,409);assert.equal((await f.call('reset_delivery',{kind:'consult',confirmed:true})).code,200);assert.equal((await f.call('claim_delivery',{kind:'consult'})).code,200)})
test('outbound credit never counts as incoming retainer',()=>{const r={id:'r',reference:'ref',amount_cents:500000,account_key:'trust'};const t={gateway_transaction_id:'credit',reference:'ref',amount_cents:500000,account_key:'trust',currency:'USD',transaction_type:'CREDIT',status:'COMPLETED'};assert.notEqual(model.paymentEvidence([t],r).status,'paid')})
