import test from 'node:test';import assert from 'node:assert/strict';import {makeDefinition,makeBlock,startRun} from '../src/processes/model.js';
const m=await import('../src/processes/repository.js').catch(()=>({}));
test('repository exists',()=>assert.equal(typeof m.repository,'function'));
if(m.repository){
 test('conflicting save never returns a local success',async()=>{let calls=0;const c={rpc:async()=>{calls++;return {error:{code:'PT409',message:'Changed in another window'}}}};const r=m.repository(c,'owner');await assert.rejects(()=>r.save('template',{...makeDefinition(),nodes:[makeBlock()]},0),/another window/);assert.equal(calls,1)});
 test('one completion sends billing and history in same RPC',async()=>{const requests=[];const c={rpc:async(name,body)=>{requests.push(body);return {data:{state:body.p_state,revision:2}}}};const r=m.repository(c,'owner',()=>({user_id:'owner',user_member_id:'member',rate:300}));const d={...makeDefinition(),nodes:[{...makeBlock(),id:'a',billing:{enabled:true,minutes:6,description:'Review'}}]};let s=startRun(d,{id:'m'});s.revision=1;s=await r.dispatch(s,{type:'complete',nodeId:'a',confirmed:true,reference:'actual work'});assert.equal(requests.length,1);assert.equal(requests[0].p_billing.amount,30);assert.equal(requests[0].p_billing.billing_time,0.1);assert.equal(s.steps.a.billingId,requests[0].p_billing.id);assert.equal(s.history.at(-1).type,'billed')});
 test('a failed save retains original run and history',async()=>{const c={rpc:async()=>({error:{message:'Offline'}})};const r=m.repository(c,'owner');const d={...makeDefinition(),nodes:[{...makeBlock(),id:'a'}]};const s=startRun(d,{id:'m'}),original=JSON.stringify(s);await assert.rejects(()=>r.dispatch(s,{type:'complete',nodeId:'a',confirmed:true,reference:'done'}),/Offline/);assert.equal(JSON.stringify(s),original)});
 test('local date at midnight UTC uses Texas billing date',()=>assert.equal(m.texasDate('2026-09-11T02:00:00Z'),'2026-09-10'));
}
test('fractional hours use six decimal places for the database boundary',async()=>{let sent;const c={rpc:async(_,b)=>{sent=b;return {data:{state:b.p_state,revision:2}}}};const repo=m.repository(c,'owner',()=>({user_member_id:'member',rate:300}));const n={...makeBlock(),id:'one',billing:{enabled:true,minutes:1,description:'One minute'}};const r=startRun({...makeDefinition(),nodes:[n]},{id:'m'});await repo.dispatch(r,{type:'complete',nodeId:n.id,confirmed:true,reference:'Completed work'});assert.equal(sent.p_billing.billing_time,0.016667);assert.equal(sent.p_billing.amount,5);});
