import test from 'node:test';
import assert from 'node:assert/strict';
const path='../src/processes/model.js';
// Missing implementation is reported as a feature assertion, not an import crash.
const m=await import(path).catch(()=>({}));
test('process model exists',()=>assert.equal(typeof m.startRun,'function'));
const at='2026-09-10T18:00:00Z',later='2026-09-12T18:00:00Z';
const b=(id,type='manual',p={})=>({...m.makeBlock(type),id,...p});
const d=nodes=>({...m.makeDefinition('Test'),nodes});
const run=nodes=>m.startRun(d(nodes),{id:'matter-a',name:'Sample matter'},at);
const e=(s,type,nodeId,p={})=>m.reduceRun(s,{id:crypto.randomUUID(),type,nodeId,...p},at);
const done=(s,id)=>e(s,'complete',id,{confirmed:true,reference:'Reviewed actual work'});
if(m.startRun){
 test('serial completion activates next step',()=>{let s=run([b('a'),b('b','manual',{dependsOn:['a']})]);assert.equal(s.steps.b.status,'blocked');s=done(s,'a');assert.equal(s.steps.b.status,'ready')});
 test('parallel successors with all-join wait for both',()=>{let s=run([b('a'),b('b','manual',{dependsOn:['a']}),b('c','manual',{dependsOn:['a']}),b('d','manual',{dependsOn:['b','c']})]);s=done(s,'a');assert.equal(s.steps.b.status,'ready');assert.equal(s.steps.c.status,'ready');s=done(s,'b');assert.equal(s.steps.d.status,'blocked');s=done(s,'c');assert.equal(s.steps.d.status,'ready')});
 test('any-join does not need all predecessors',()=>{let s=run([b('a'),b('b'),b('c','manual',{dependsOn:['a','b'],join:'any'})]);s=done(s,'a');assert.equal(s.steps.c.status,'ready')});
 test('cycles and missing dependencies are rejected',()=>{assert.throws(()=>m.validateDefinition(d([b('a','manual',{dependsOn:['b']}),b('b','manual',{dependsOn:['a']})])),/cycle/);assert.throws(()=>m.validateDefinition(d([b('a','manual',{dependsOn:['missing']})])),/prerequisite/)});
 test('manual and date triggers respect dependencies',()=>{let s=run([b('a'),b('b','manual',{dependsOn:['a'],trigger:'manual'}),b('c','manual',{trigger:'date',startAt:later})]);assert.throws(()=>e(s,'start','b'),/prerequisites/);s=done(s,'a');assert.equal(s.steps.b.status,'blocked');s=e(s,'start','b');assert.equal(s.steps.b.status,'ready');assert.equal(s.steps.c.status,'blocked');s=m.reduceRun(s,{type:'tick',id:'tick'},later);assert.equal(s.steps.c.status,'ready')});
 test('event names are matched exactly',()=>{let s=run([b('a','manual',{trigger:'event',eventName:'court_dates'})]);s=e(s,'signal','a',{signal:'unrelated',reference:'message1'});assert.equal(s.steps.a.status,'blocked');s=e(s,'signal','a',{signal:'court_dates',reference:'message2'});assert.equal(s.steps.a.status,'ready')});
 test('email approval required and edit revokes approval',()=>{let s=run([b('a','draft_email')]);assert.equal(s.steps.a.status,'approval');assert.throws(()=>e(s,'claim','a'),/ready/);s=e(s,'approve','a');s=e(s,'configure','a',{config:{body:'changed'}});assert.equal(s.steps.a.status,'approval')});
 test('claim is exclusive and ambiguous failure is not auto-retried',()=>{let s=run([b('a')]);s=e(s,'claim','a');assert.throws(()=>e(s,'claim','a'),/ready/);s=e(s,'failure','a',{message:'Network result uncertain'});assert.equal(s.steps.a.status,'error');assert.throws(()=>e(s,'claim','a'),/ready/)});
 test('handoff does not bill or complete',()=>{let s=run([b('a','efile_document',{approval:false,billing:{enabled:true,minutes:6,description:'Filing'}})]);s=e(s,'claim','a');s=e(s,'handoff','a',{reference:'workspace',message:'Waiting for filing result'});assert.equal(s.steps.a.status,'waiting');assert.equal(m.billingIntent(s,'a'),null)});
 test('sent email bills once then waits for response',()=>{let s=run([b('a','draft_email',{approval:false,billing:{enabled:true,minutes:6,description:'Correspondence'}})]);s=e(s,'claim','a');s=e(s,'success','a',{reference:'message-receipt'});assert.equal(s.steps.a.status,'waiting');assert.equal(m.billingIntent(s,'a').minutes,6);s=e(s,'billed','a',{billingId:'bill1'});s=done(s,'a');assert.equal(m.billingIntent(s,'a'),null)});
 test('completed and duplicate events never add duplicate history',()=>{let s=run([b('a')]);const event={id:'same',type:'complete',nodeId:'a',confirmed:true,reference:'receipt'};s=m.reduceRun(s,event,at);assert.equal(m.reduceRun(s,event,at),s);assert.equal(m.reduceRun(s,{...event,id:'second'},at),s)});
 test('all parallel blockers visible, attorney approvals first',()=>{const s=run([b('a','wait',{waitingOn:'Court',messages:{waiting:'Waiting for court dates'}}),b('b','draft_email')]);const x=m.attention(s);assert.equal(x.length,2);assert.equal(x[0].needsMe,true);assert.match(x[1].message,/court dates/)});
 test('pausing prevents action but accepts recorded results without activating next',()=>{let s=run([b('a'),b('b','manual',{dependsOn:['a']})]);s=e(s,'claim','a');s=e(s,'pause');assert.throws(()=>e(s,'claim','b'),/paused/);s=e(s,'success','a',{reference:'receipt'});assert.equal(s.steps.b.status,'blocked');s=e(s,'resume');assert.equal(s.steps.b.status,'ready')});
 test('templates are immutable snapshots for active runs',()=>{const def=d([b('a')]);const s=m.startRun(def,{id:'m'},at);def.nodes[0].name='changed';assert.notEqual(s.definition.nodes[0].name,'changed')});
 test('input and output slots require same-matter verified documents',()=>{const def=d([b('a','manual',{config:{inputSlots:['input'],outputSlots:['output']}})]);def.slots=[{id:'input',name:'Input'},{id:'output',name:'Output'}];let s=m.startRun(def,{id:'m'},at);assert.throws(()=>done(s,'a'),/document/);assert.throws(()=>e(s,'document','a',{slotId:'input',document:{id:'x',matter_id:'other'},confirmed:true}),/matter/);for(const slotId of ['input','output'])s=e(s,'document','a',{slotId,document:{id:slotId,matter_id:'m'},confirmed:true});assert.equal(done(s,'a').status,'complete')});
 test('billing validation rejects zero, NaN and missing description',()=>{for(const billing of [{enabled:true,minutes:0,description:'x'},{enabled:true,minutes:6,description:''},{enabled:true,minutes:'bad',description:'x'}])assert.throws(()=>m.validateDefinition(d([b('a','manual',{billing})])),/Billing/)});
 test('withdrawal import preserves dependencies and slots without historic execution',()=>{const x=m.fromWithdrawal({name:'Withdrawal',slots:[{id:'draft',name:'Draft'}],steps:[{id:'a',action:'draft_document',name:'Draft',depends_on:[],output_slots:['draft']},{id:'b',name:'File',action:'efile_document',depends_on:['a'],input_slots:['draft']}]});assert.deepEqual(x.nodes[1].dependsOn,['a']);assert.deepEqual(x.nodes[1].config.inputSlots,['draft']);assert.equal(m.startRun(x,{id:'m'},at).history.some(e=>e.type==='completed'),false)});
 test('wait blocks cannot bill on mere activation',()=>{const s=run([b('a','wait',{billing:{enabled:true,minutes:6,description:'Review response'}})]);assert.equal(m.billingIntent(s,'a'),null)});
 test('layout move does not rewire dependencies',()=>{const def=d([b('a'),b('b','manual',{dependsOn:['a']})]);def.nodes[1].x=0;def.nodes[1].y=999;assert.equal(m.startRun(def,{id:'m'},at).steps.b.status,'blocked')});
}
