import test from 'node:test';import assert from 'node:assert/strict';import {makeBlock,makeDefinition,startRun} from '../src/processes/model.js';
const m=await import('../src/processes/actions.js').catch(()=>({}));test('provider adapters exist',()=>assert.equal(typeof m.actions,'function'));
if(m.actions){const node=type=>({...makeBlock(type),id:'a'});const run=n=>startRun({...makeDefinition(),nodes:[n]},{id:'m',name:'Test'});const pdf='data:application/pdf;base64,JVBERi0xLjQK';
 test('cross-matter file rejected before any provider call',async()=>{let called=0;const n=node('efile_document');n.config.documentIds=['doc'];const a=m.actions({documents:[{id:'doc',matter_id:'other'}],getFile:async()=>pdf,graph:async()=>{called++}});await assert.rejects(()=>a.preflight(run(n),n),/matter/);assert.equal(called,0)});
 test('email drafts then sends once with no mutation retry',async()=>{const calls=[];const n=node('draft_email');n.config={...n.config,to:'counsel@example.invalid',subject:'Order',body:'Please review {matter}'};const a=m.actions({documents:[],people:()=>[],graph:async(path,options)=>{calls.push({path,options});return path==='/me/messages'?{id:'draft-id',conversationId:'thread'}:null;},emailHtml:s=>s});const r=run(n);await a.preflight(r,n);const result=await a.perform(r,n);assert.equal(calls.length,2);assert.equal(calls[1].path,'/me/messages/draft-id/send');assert.equal(calls[1].options.maxRetries,0);assert.equal(result.receipt.conversationId,'thread')});
 test('empty email never invokes Graph',async()=>{let count=0;const n=node('draft_email');const a=m.actions({documents:[],people:()=>[],graph:async()=>count++});await assert.rejects(()=>a.preflight(run(n),n),/recipient|subject|message/i);assert.equal(count,0)});
 test('save uses conflict-fail upload and does not pass auth to upload URL',async()=>{const calls=[];const n=node('save_file');n.config={...n.config,documentIds:['doc'],folder:'/Drafts'};const a=m.actions({documents:[{id:'doc',matter_id:'m',file_name:'a.pdf'}],getFile:async()=>pdf,graph:async(path,options)=>{calls.push({path,options});return path.includes('createUploadSession')?{uploadUrl:'https://upload.example.invalid/one'}:{id:'folder',folder:{}};},upload:async(url,options)=>{assert.equal(options.headers.Authorization,undefined);return {ok:true,status:201,json:async()=>({id:'saved'})};}});const result=await a.perform(run(n),n);assert.equal(JSON.parse(calls[1].options.body).item['@microsoft.graph.conflictBehavior'],'fail');assert.match(result.reference,/saved/)});
 test('unrelated or old messages cannot be treated as a response',async()=>{const n=node('draft_email');n.config.to='counsel@example.invalid';const r=run(n);r.steps.a.receipt={conversationId:'thread',recipients:['counsel@example.invalid']};r.steps.a.performedAt='2026-09-10T18:00:00Z';const a=m.actions({graph:async()=>({value:[{id:'wrong',conversationId:'other',receivedDateTime:'2026-09-11T00:00:00Z',from:{emailAddress:{address:'counsel@example.invalid'}}}]})});assert.equal(await a.check(r,n),null)});
}
