import test from 'node:test'
import assert from 'node:assert/strict'
import {blockKey,fieldKey,validFieldSource,locateBinding,paragraphFields,replaceInParagraph,bindingSignature} from '../src/mioTemplateFields.js'
import {captionModel} from '../src/mioCaptionTable.js'
const file={id:'a',name:'A.docx'},document={paragraphs:[{index:0,text:'Alex asked Alex to call.'},{index:1,text:'Mail: 101 Sample Street'},{index:2,text:'Alex replied.'}]}
const binding={id:'b',kind:'field',file_id:'a',source_text:'Alex',field_key:'client_name',paragraph_start:0,paragraph_end:0,start_offset:11,end_offset:15}
test('marker detection cannot compile malformed dynamically generated regex',()=>{for(const key of ['caption','signature','certificate_detailed'])assert.equal(blockKey('[[MIO_BLOCK:'+key+']]'),key);assert.equal(blockKey('[[MIO_BLOCK:caption]] extra'),'');assert.equal(blockKey('{{case_caption_text}}'),'caption');assert.equal(blockKey('[MIO_BLOCK:caption]'),'')})
test('selected repeated occurrence and source positions survive JSON save/reload',()=>{const saved=JSON.parse(JSON.stringify({bindings:[binding]}));const ranges=paragraphFields(document.paragraphs[0],saved,file,document);assert.equal(ranges[0].start,11);assert.equal(replaceInParagraph(document.paragraphs[0].text,ranges,()=> '[Client name]'),'Alex asked [Client name] to call.')})
test('file scoping, inactive fields, and explicit replace-all have distinct semantics',()=>{assert.equal(paragraphFields(document.paragraphs[0],{bindings:[binding]},{id:'b'},document).length,0);assert.equal(paragraphFields(document.paragraphs[0],{bindings:[{...binding,is_active:false}]},file,document).length,0);assert.equal(paragraphFields(document.paragraphs[0],{bindings:[{...binding,replace_all:true}]},file,document).length,2);assert.equal(paragraphFields(document.paragraphs[2],{bindings:[binding]},file,document).length,0)})
test('ambiguous drift does not overwrite another client name',()=>{assert.equal(locateBinding({...binding,paragraph_start:1,paragraph_end:1},document),null);assert.equal(locateBinding({...binding,source_text:'101 Sample Street',paragraph_start:99,paragraph_end:99},document).paragraph_start,1)})
test('field identity includes occurrence offsets and source prefixes',()=>{assert.notEqual(bindingSignature(binding),bindingSignature({...binding,start_offset:0,end_offset:4}));assert.notEqual(fieldKey('attorney.name'),fieldKey('firm.name'));assert.notEqual(fieldKey('court.phone'),fieldKey('attorney.phone'));assert.equal(fieldKey('matter.client_address'),'client_address_inline');assert.equal(validFieldSource('firm.address_line_1'),true);assert.equal(validFieldSource('javascript:alert(1)'),false)})
test('caption model includes court and county and preserves supplied left wording',()=>{const m=captionModel({case_caption_text:'ALPHA\nAND\nBETA',court_name:'300th Judicial District Court',county:'Brazoria County, Texas'});assert.deepEqual(m.left,['ALPHA','AND','BETA']);assert.equal(m.right[2],'300TH JUDICIAL DISTRICT');assert.equal(m.right[4],'BRAZORIA COUNTY, TEXAS');assert.ok(m.marks>=8);assert.equal(captionModel({county:'Brazoria'}).right[4],'BRAZORIA COUNTY, TEXAS')})
