import test from 'node:test'
import assert from 'node:assert/strict'
import {newWithdrawal,applyWithdrawalEvent as apply,workflowAttention,sortWithdrawalRows} from '../src/mioWithdrawalWorkflow.js'
import {createWithdrawalRepository} from '../src/mioWithdrawalRepository.js'
import {transformAll} from './transform-all.mjs'
import {transformWithdrawalDashboard} from '../mio-v279-withdrawal-dashboard.js'
const t='2026-09-05T12:00:00Z',later='2026-09-06T12:00:00Z',mid='2026-09-05T14:00:00Z',id='00000000-0000-4000-8000-000000000279'
const fresh=()=>newWithdrawal(id,'2026-08-01T12:00:00Z',t)
const complete=(s,step,extra={})=>apply(s,{type:'step_update',step_id:step,status:'complete',note:'Reviewed synthetic evidence',confirmed:true,evidence:{reference:'test-reference'},...extra},t)
const ready=()=>['decision','drafting','filing','service'].reduce((s,id)=>complete(s,id),fresh())
test('legacy date stays unknown and navigation alone does not advance',()=>{const s=newWithdrawal(id,null,t),n=apply(s,{type:'module_opened',step_id:'drafting'},t);assert.equal(n.started_at,null);assert.equal(n.steps.drafting.status,'not_started')})
test('parallel waiting does not hide another route requiring action',()=>{let s=ready();for(const id of ['client_signature','opposing_signature'])s=apply(s,{type:'email_sent',step_id:id,email_id:id},t);assert.equal(workflowAttention(s,Date.parse(t)).step_id,'setting');s=apply(s,{type:'email_sent',step_id:'setting',email_id:'setting'},t);assert.equal(workflowAttention(s,Date.parse(t)).needsMe,false)})
test('reply promotes waiting to approval; repeated and old messages do not reset clocks',()=>{let s=apply(ready(),{type:'email_sent',step_id:'client_signature',email_id:'e'},t);const e={type:'email_received',step_id:'client_signature',message_id:'m',received_at:mid,source_key:'e',source_version:'m'};s=apply(s,e,later);assert.equal(s.steps.client_signature.attention_since,mid);assert.equal(s.steps.client_signature.status,'needs_approval');assert.equal(apply(s,e,later),s);assert.equal(apply(s,{...e,source_version:'old',received_at:t},later),s)})
test('follow-up deadline converts waiting into actionable work at the due time',()=>{let s=ready();for(const id of ['client_signature','opposing_signature','setting'])s=apply(s,{type:'step_update',step_id:id,status:'waiting',note:'Waiting',waiting_on:'Recipient',due_at:later},t);assert.equal(workflowAttention(s,Date.parse(t)).needsMe,false);assert.equal(workflowAttention(s,Date.parse(later)).since,Date.parse(later))})
test('attention and entry-age sorting are independent, unknown dates sort last',()=>{const a=fresh(),b=fresh();b.started_at='2026-08-15T00:00:00Z';b.steps.decision.attention_since='2026-09-01T00:00:00Z';const rows=[{matter_id:'a',state:a},{matter_id:'b',state:b},{matter_id:'c',state:newWithdrawal('c',null,t)}];assert.deepEqual(sortWithdrawalRows(rows,'attention',Date.parse(t)).map(r=>r.matter_id),['b','a','c']);assert.deepEqual(sortWithdrawalRows(rows,'oldest').map(r=>r.matter_id),['a','b','c']);assert.deepEqual(sortWithdrawalRows(rows,'newest').map(r=>r.matter_id),['b','a','c'])})
test('completion requires evidence and actual signed-order reference',()=>{assert.throws(()=>apply(fresh(),{type:'step_update',step_id:'decision',status:'complete',note:'yes'},t),/evidence/);assert.throws(()=>complete(ready(),'signed_order',{historical_confirmed:true}),/actual signed-order/);assert.throws(()=>complete(fresh(),'close_workflow',{historical_confirmed:true}),/first/)})
test('signed order converges routes without silently cancelling actual settings',()=>{let s=apply(ready(),{type:'email_sent',step_id:'setting',email_id:'setting'},t);s=complete(s,'signed_order',{historical_confirmed:true,evidence:{reference:'signed.pdf',document_id:'synthetic-doc'}});assert.equal(s.steps.status_update.status,'needs_approval');assert.equal(s.steps.closeout_email.status,'needs_action');assert.equal(s.steps.setting_cleanup.status,'needs_action');assert.match(s.steps.setting.note,/NOT automatically cancelled/)})
test('client closeout needs verified links, sending and separately confirmed delivery',()=>{let s=complete(ready(),'signed_order',{historical_confirmed:true,evidence:{reference:'signed.pdf',document_id:'synthetic-doc'}});assert.throws(()=>complete(s,'closeout_email'),/Verify/);const links={invoices:'https://example.invalid/i',efilings:'https://example.invalid/e',documents:'https://example.invalid/d'};s=apply(s,{type:'closeout_details',links,links_verified:true,subject:'Synthetic',body:Object.values(links).join('\n')},t);s=apply(s,{type:'email_sent',step_id:'closeout_email',email_id:'sent'},t);assert.equal(s.steps.closeout_email.status,'waiting');s=complete(s,'closeout_email',{delivery_confirmed:true});assert.equal(s.closeout.delivery_confirmed,true);assert.throws(()=>complete(s,'status_update'),/approval button/)})
test('partial service emailing stays actionable, not falsely complete or waiting',()=>{const s=apply(ready(),{type:'email_sent',step_id:'service',email_id:'service-client'},t);assert.equal(s.steps.service.status,'needs_approval')})
test('store rejects account crossover and failed CAS never stages local success',async()=>{const client={rpc:async()=>({error:{code:'40001',message:'conflict'}}),from:()=>({select(){return this},eq(){return this},maybeSingle:async()=>({data:{matter_id:id,revision:1,state:fresh()}})})};const repo=createWithdrawalRepository(client);repo.account('owner');await assert.rejects(()=>repo.apply('other',id,{type:'module_opened'}),/Account changed/);await assert.rejects(()=>repo.apply('owner',id,{type:'module_opened'}));assert.deepEqual(repo.getSnapshot().rows,{});assert.match(repo.getSnapshot().error,/Another window/)})
test('all integration layers compose and preserve legacy and provider approval gates',async()=>{const code=await transformAll();assert.match(code,/function renderWithdrawalsPageLegacy/);assert.match(code,/WithdrawalDashboard rows=/);assert.match(code,/context.type==='withdrawal'\)return list/);assert.match(code,/mioWithdrawalSendAttachments\(context,email\)/);assert.throws(()=>transformWithdrawalDashboard(code))})
