import test from 'node:test'
import assert from 'node:assert/strict'
import {newWithdrawal} from '../src/mioWithdrawalWorkspaceState.js'
import {defaultWithdrawalDefinition,configureWorkflow,applyWorkflowBlockEvent,validateWorkflowDefinition,removeWorkflowSteps,resolveWorkflowSlot,workflowBlockReason,normalizeWithdrawalView,matchesWithdrawalView} from '../src/mioWorkflowBlocks.js'
import {graphValue,clipGraphPoints,workflowFlowHtml} from '../src/mioWithdrawalBlockHelpers.js'
const at='2026-09-07T12:00:00.000Z',make=()=>configureWorkflow(newWithdrawal('matter-a',at,at),defaultWithdrawalDefinition(),at)
const apply=(s,e)=>applyWorkflowBlockEvent(s,e,at),finish=(s,id,extra={})=>apply(s,{type:'step_update',step_id:id,status:'complete',confirmed:true,evidence:{reference:'Attorney confirmation'},...extra})
test('five graph types calculate independently without double subtracting WIP or OB',()=>{const r={trust:5000,wip:800,outstanding:700,minimum:1000};assert.equal(graphValue(r,'matter_trust_funds'),5000);assert.equal(graphValue(r,'trust_minus_minimum'),4000);assert.equal(graphValue(r,'trust_minus_minimum_minus_wip'),3200);assert.equal(graphValue(r,'trust_minus_wip_minus_outstanding_minus_minimum'),2500);assert.equal(graphValue(r,'trust_minus_outstanding'),4300)})
test('date clipping carries only a known prior sample; no initial zero fabricated',()=>{const now=Date.parse(at),prior={date:'2026-01-01',balance:100},later={date:'2026-09-02',balance:45};assert.equal(clipGraphPoints([prior,later],'30',now)[0].balance,100);assert.deepEqual(clipGraphPoints([later],'30',now),[later]);assert.deepEqual(clipGraphPoints([],'all',now),[])})
test('saved categorical filters remain distinct and do not invent case type names',()=>{const v=normalizeWithdrawalView({matter_status:['Served'],case_status:['Open'],case_type:['SAPCR/Modification'],days:'180'});assert.equal(matchesWithdrawalView({matter_status:'Served',case_status:'Open',case_type:'SAPCR/Modification'},v),true);assert.equal(matchesWithdrawalView({matter_status:'Served',case_status:'Open',case_type:'Modification'},v),false);assert.deepEqual(normalizeWithdrawalView(JSON.parse(JSON.stringify(v))),v)})
test('four lanes, typed actions and stable document slots are valid and configurable',()=>{const d=defaultWithdrawalDefinition();assert.equal(d.rows.length,4);assert.equal(d.slots.length,9);assert.equal(validateWorkflowDefinition(d),d);const old=make();old.steps.service.note='Retained history';const next=configureWorkflow(old,removeWorkflowSteps(d,['service']),at);assert.equal(next.definition.steps.some(s=>s.id==='service'),false);assert.ok(next.definition.steps.find(s=>s.id==='client_signature').depends_on.includes('filing'));assert.equal(next.steps.service.note,'Retained history');assert.ok(next.document_slots.motion_filed)})
test('loops and dangling slots rejected without mutating valid definition',()=>{const d=defaultWithdrawalDefinition();d.steps[0].depends_on=['drafting'];assert.throws(()=>validateWorkflowDefinition(d),/loop/);const x=defaultWithdrawalDefinition();x.steps[1].output_slots=['bogus'];assert.throws(()=>validateWorkflowDefinition(x),/reference/)})
test('drafts auto-populate only mapped outputs and require review before completion',()=>{let s=finish(make(),'decision');s.steps.drafting.output_files={motion_draft:'Motion.docx',order_draft:'Order.docx'};s=apply(s,{type:'documents_saved',step_id:'drafting',document_ids:['motion','order'],documents:[{id:'motion',source_file_name:'Motion.docx',name:'Motion.docx'},{id:'order',source_file_name:'Order.docx',name:'Order.docx'}]});assert.equal(resolveWorkflowSlot(s,'motion_draft').document_id,'motion');assert.equal(resolveWorkflowSlot(s,'motion_draft').verified,false);assert.throws(()=>finish(s,'drafting'),/verify/);s=apply(s,{type:'slot_verify',slot_id:'motion_draft',confirmed:true});s=apply(s,{type:'slot_verify',slot_id:'order_draft',confirmed:true});s=finish(s,'drafting');assert.equal(s.steps.filing.status,'needs_action');assert.equal(workflowBlockReason(s,s.definition.steps.find(s=>s.id==='filing')),'')})
test('same-matter documents, append-only versions, historical bypass and final signed-order protection',()=>{let s=make();assert.throws(()=>apply(s,{type:'slot_attach',slot_id:'motion_draft',document_id:'other',matter_id:'matter-b'}),/this matter/);s=apply(s,{type:'slot_attach',slot_id:'motion_draft',document_id:'draft1',matter_id:s.matter_id,verified:true,confirmed:true});const old=resolveWorkflowSlot(s,'motion_draft');s=apply(s,{type:'slot_attach',slot_id:'motion_draft',document_id:'draft2',matter_id:s.matter_id,verified:true,confirmed:true});assert.equal(s.document_slots.motion_draft.versions.length,2);assert.equal(s.document_slots.motion_draft.versions[0].id,old.id);s=finish(s,'filing',{historical_confirmed:true});assert.equal(s.steps.filing.status,'complete');assert.equal(resolveWorkflowSlot(s,'motion_filed'),null);assert.throws(()=>finish(s,'signed_order',{historical_confirmed:true}),/output/);assert.throws(()=>finish(s,'close_workflow',{historical_confirmed:true}),/judge-signed/)})
test('efile acceptance and email replies require review; they never invent signed or stamped files',()=>{let s=make();s=apply(s,{type:'efile_update',step_id:'filing',status:'accepted',reference:'synthetic'});assert.equal(s.steps.filing.status,'needs_approval');assert.equal(resolveWorkflowSlot(s,'motion_filed'),null);s=apply(s,{type:'email_sent',step_id:'client_signature',email_id:'mail1'});assert.equal(s.steps.client_signature.status,'waiting');s=apply(s,{type:'email_received',step_id:'client_signature',message_id:'reply1',received_at:at});assert.equal(s.steps.client_signature.status,'needs_approval');assert.equal(resolveWorkflowSlot(s,'order_client_signed'),null)})
test('repeated provider signals do not reset clocks or create duplicate versions',()=>{let s=make();const e={type:'efile_update',step_id:'filing',status:'submitted',source_key:'job:a',source_version:'submitted'};s=apply(s,e);assert.equal(apply(s,e),s)})
test('flow sheet is generated from edited definitions and escapes arbitrary text',()=>{const d=defaultWithdrawalDefinition();d.rows[0].name='<script>alert(1)</script>';const html=workflowFlowHtml(d);assert.ok(html.includes('&lt;script&gt;'));assert.ok(html.includes('File-stamped motion'));assert.ok(html.includes('approval handoffs'));assert.equal(html.includes('<script>'),false)})
test('pause blocks completion and notes never advance steps',()=>{let s=make();s=apply(s,{type:'workspace_pause',paused:true});assert.throws(()=>finish(s,'decision'),/Resume/);s=apply(s,{type:'step_note',step_id:'drafting',note:'Call client'});assert.equal(s.steps.drafting.status,'not_started')})
