// Shared validation and scope logic. No network access or browser persistence.
export const COLUMN_LABELS={searchTerm:'Search term',intent:'Intent',status:'Status',campaignName:'Campaign',adGroupName:'Ad group',triggeringKeyword:'Triggering keyword',keywordMatchType:'Keyword match',matchType:'Search match',device:'Device',impressions:'Impressions',clicks:'Clicks',ctr:'CTR',cost:'Cost',averageCpc:'Avg. CPC',conversions:'Conversions',costPerConversion:'Cost / conv.'}
export const DEFAULT_COLUMNS=['searchTerm','intent','status','campaignName','adGroupName','triggeringKeyword','clicks','cost','conversions']
export const text=v=>String(v??'').trim().toLowerCase().replace(/\s+/g,' ')
export function requireId(v,label='ID'){const s=String(v??'');if(!/^\d{1,20}$/.test(s))throw new Error(`${label} is invalid.`);return s}
export function adChars(v=''){return Array.from(v).reduce((n,c)=>n+(/[\u1100-\u115f\u2e80-\ua4cf\uac00-\ud7a3\uf900-\ufaff\ufe10-\ufe6f\uff01-\uff60\uffe0-\uffe6]/u.test(c)?2:1),0)}
export function adDraft(ad={}){const r=ad.responsiveSearchAd||ad;const assets=a=>(a||[]).map(x=>({text:x.text||'',...(x.pinnedField&&!['UNKNOWN','UNSPECIFIED'].includes(x.pinnedField)?{pinnedField:x.pinnedField}:{})}));return{headlines:assets(r.headlines),descriptions:assets(r.descriptions),finalUrls:[...(ad.finalUrls||[])],path1:r.path1||'',path2:r.path2||''}}
export function normalizeAdDraft(input={}){
 const clean=(key,min,max,limit,prefix,positions)=>{const a=input[key];if(!Array.isArray(a)||a.length<min||a.length>max)throw new Error(`Use ${min}-${max} ${key}.`);const seen=new Set();return a.map((r,i)=>{const value=String(r?.text??'').trim(),pin=String(r?.pinnedField||'');if(!value||adChars(value)>limit)throw new Error(`${key} ${i+1} requires 1-${limit} characters.`);if(seen.has(text(value)))throw new Error(`${key} must not repeat the same text.`);seen.add(text(value));if(pin&&!positions.map(p=>`${prefix}_${p}`).includes(pin))throw new Error(`Invalid pin for ${key} ${i+1}.`);return{text:value,...(pin?{pinnedField:pin}:{})}})}
 const headlines=clean('headlines',3,15,30,'HEADLINE',[1,2,3]),descriptions=clean('descriptions',2,4,90,'DESCRIPTION',[1,2]);
 if(!Array.isArray(input.finalUrls)||!input.finalUrls.length||input.finalUrls.length>10)throw new Error('Provide 1-10 final URLs.')
 const finalUrls=input.finalUrls.map(v=>{const s=String(v).trim();let u;try{u=new URL(s)}catch{throw new Error('Final URL must be a complete HTTP(S) address.')}if(!['http:','https:'].includes(u.protocol)||!u.hostname||u.username||u.password||s.length>2048)throw new Error('Final URL must be HTTP(S), without credentials.');return s})
 const path1=String(input.path1||'').trim(),path2=String(input.path2||'').trim();if(adChars(path1)>15||adChars(path2)>15||/[\s/?#]/.test(path1+path2))throw new Error('Display paths: maximum 15 characters each; no spaces or slashes.');if(path2&&!path1)throw new Error('Path 1 is required when Path 2 is used.');return{headlines,descriptions,finalUrls,path1,path2}
}
export function negativeMatches(term,n){const s=text(term),k=text(n.keyword);if(!s||!k)return false;switch(n.matchType){case'EXACT':return s===k;case'PHRASE':return` ${s} `.includes(` ${k} `);case'BROAD':{const words=new Set(s.split(' '));return k.split(' ').every(w=>words.has(w))}default:return false}}
export function coveringNegative(row,negatives=[],campaignOnly=false){return negatives.find(n=>!['REMOVED','PAUSED'].includes(n.status)&&(n.scope==='account'||String(n.campaignId)===String(row.campaignId)&&(n.scope==='campaign'||n.scope==='shared'||!campaignOnly&&n.scope==='ad_group'&&String(n.adGroupId)===String(row.adGroupId)))&&negativeMatches(row.searchTerm||row.keyword,n))}
export function termStatus(row,report={}){const n=coveringNegative(row,report.negativeKeywords||[]);if(n){const kind=n.scope==='ad_group'?'ad_group_negative':n.scope==='account'?'account_negative':'campaign_negative';return{kind,resolved:true,label:kind==='campaign_negative'?'Campaign negative':kind==='account_negative'?'Account negative':'Ad-group negative',detail:`Blocked by ${n.matchType} negative "${n.keyword}"${n.listName?` in ${n.listName}`:''}`}}const k=(report.keywords||[]).find(k=>!k.negative&&k.status!=='REMOVED'&&k.matchType==='EXACT'&&String(k.campaignId)===String(row.campaignId)&&String(k.adGroupId)===String(row.adGroupId)&&text(k.keyword)===text(row.searchTerm));if(k)return{kind:k.status==='ENABLED'?'exact_keyword':'exact_paused',resolved:k.status==='ENABLED',label:k.status==='ENABLED'?'Exact keyword added':'Exact keyword paused',detail:`${k.status} exact keyword "${k.keyword}"`};return{kind:'unresolved',resolved:false,label:'Needs review',detail:report.coverageComplete===false?'Some account data is unavailable.':''}}
export function prepareNegatives(items,negatives=[]){if(!Array.isArray(items)||items.length<1||items.length>100)throw new Error('Select between 1 and 100 terms per approval.');const ready=[],skipped=[],seen=new Set();for(const r of items){const campaignId=requireId(r.campaignId,'Campaign ID'),keyword=String(r.keyword??r.searchTerm??'').trim().replace(/\s+/g,' '),matchType=String(r.matchType||'EXACT').toUpperCase();if(!['EXACT','PHRASE'].includes(matchType))throw new Error('Choose EXACT or PHRASE explicitly in review.');if(!keyword||adChars(keyword)>80||keyword.split(' ').length>10)throw new Error('Negative keywords require 1-80 characters and at most 10 words.');const item={campaignId,campaignName:String(r.campaignName||campaignId),keyword,searchTerm:keyword,matchType},key=JSON.stringify([campaignId,matchType,text(keyword)]);const cover=coveringNegative(item,negatives.filter(n=>matchType==='EXACT'||n.matchType!=='EXACT'),true);if(seen.has(key)||cover)skipped.push({...item,state:'skipped',message:cover?`Already blocked by ${cover.matchType} "${cover.keyword}"`:'Duplicate selection'});else ready.push(item);seen.add(key)}return{ready,skipped}}
export const termKey=r=>JSON.stringify([r.campaignId||'',r.adGroupId||'',text(r.searchTerm)])
export function sanitizeColumns(v){return['searchTerm',...new Set((Array.isArray(v)?v:DEFAULT_COLUMNS).filter(k=>k!=='searchTerm'&&Object.hasOwn(COLUMN_LABELS,k)))]}
export function aggregateMetrics(rows=[]){const a=rows.reduce((a,r)=>{for(const k of['impressions','clicks','cost','conversions'])a[k]+=Number(r[k])||0;return a},{impressions:0,clicks:0,cost:0,conversions:0});return{...a,ctr:a.impressions?a.clicks/a.impressions:0,averageCpc:a.clicks?a.cost/a.clicks:0,costPerConversion:a.conversions?a.cost/a.conversions:0}}
export function groupedTerms(rows=[]){const m=new Map();for(const r of rows){const key=termKey(r);if(!m.has(key))m.set(key,[]);m.get(key).push(r)}return[...m.values()].map(items=>{const r={...items[0],...aggregateMetrics(items)};for(const k of['triggeringKeyword','device','keywordMatchType','matchType'])r[k]=[...new Set(items.map(x=>x[k]).filter(Boolean))].join(', ');return r})}
export function previewAssets(assets=[],prefix,max,offset=0){const free=assets.filter(a=>!a.pinnedField),used=new Set(),out=[];for(let p=1;p<=max;p++){const pins=assets.filter(a=>a.pinnedField===`${prefix}_${p}`),remaining=free.filter(a=>!used.has(a)),options=pins.length?pins:remaining;const a=options[offset%Math.max(1,options.length)];if(a){used.add(a);out.push(a.text)}}return out}
