// Same credentials and firm/approver gates as the existing Google Ads API route.
import crypto from 'node:crypto'
const VERSION='v25'
const customerId=()=>String(process.env.GOOGLE_ADS_CUSTOMER_ID||'').replace(/\D/g,'')
const enabled=v=>['1','true','yes','on'].includes(String(v||'').trim().toLowerCase())
function serviceAccount(){let value;try{value=JSON.parse(process.env.GOOGLE_ADS_SERVICE_ACCOUNT_JSON||'{}')}catch{throw new Error('Google service-account configuration is invalid.')}if(!value.client_email||!value.private_key)throw new Error('Google service-account configuration is incomplete.');return value}
export async function requireFirmUser(req){
 const authorization=String(req.headers.authorization||''),token=authorization.replace(/^Bearer\s+/i,'').trim();if(!token)throw Object.assign(new Error('Missing Mio session token.'),{statusCode:401})
 const url=String(process.env.SUPABASE_URL||process.env.VITE_SUPABASE_URL||'').replace(/\/$/,''),key=process.env.SUPABASE_ANON_KEY||process.env.VITE_SUPABASE_ANON_KEY||'';if(!url||!key)throw Object.assign(new Error('Supabase auth is not configured on the server.'),{statusCode:503})
 const r=await fetch(`${url}/auth/v1/user`,{headers:{Authorization:`Bearer ${token}`,apikey:key},signal:AbortSignal.timeout(15000)});if(!r.ok)throw Object.assign(new Error('Your Mio session could not be verified.'),{statusCode:401});const user=await r.json();if(!String(user.email||'').trim().toLowerCase().endsWith('@beveridgelawfirm.com'))throw Object.assign(new Error('Google Ads is restricted to firm staff accounts.'),{statusCode:403});return user
}
export function writeModeForUser(user,connected=true){const actorEmail=String(user?.email||'').trim().toLowerCase(),serverEnabled=enabled(process.env.GOOGLE_ADS_WRITES_ENABLED),approvers=String(process.env.GOOGLE_ADS_WRITE_APPROVER_EMAILS||'ben@beveridgelawfirm.com').split(',').map(x=>x.trim().toLowerCase()),userAuthorized=!!actorEmail&&approvers.includes(actorEmail);return{serverEnabled,userAuthorized,actorEmail,ready:!!(connected&&serverEnabled&&userAuthorized&&customerId()&&process.env.GOOGLE_ADS_SERVICE_ACCOUNT_JSON&&process.env.GOOGLE_ADS_DEVELOPER_TOKEN)}}
export async function googleAccessToken(){const account=serviceAccount(),now=Math.floor(Date.now()/1000),encode=x=>Buffer.from(JSON.stringify(x)).toString('base64url');const unsigned=`${encode({alg:'RS256',typ:'JWT'})}.${encode({iss:account.client_email,scope:'https://www.googleapis.com/auth/adwords',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600})}`,assertion=`${unsigned}.${crypto.sign('RSA-SHA256',Buffer.from(unsigned),account.private_key).toString('base64url')}`;const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion}),signal:AbortSignal.timeout(20000)}),data=await r.json().catch(()=>({}));if(!r.ok||!data.access_token)throw new Error(data.error_description||data.error||'Google did not issue an access token.');return data.access_token}
export async function googleAdsPost(token,path,body){const login=String(process.env.GOOGLE_ADS_LOGIN_CUSTOMER_ID||'').replace(/\D/g,''),headers={'Content-Type':'application/json',Authorization:`Bearer ${token}`,'developer-token':process.env.GOOGLE_ADS_DEVELOPER_TOKEN||''};if(login)headers['login-customer-id']=login;const r=await fetch(`https://googleads.googleapis.com/${VERSION}/${path}`,{method:'POST',headers,body:JSON.stringify(body),signal:AbortSignal.timeout(20000)}),raw=await r.text();let payload;try{payload=raw?JSON.parse(raw):{}}catch{throw new Error('Google returned an unreadable response. Verify current account state before retrying a write.')}const requestId=r.headers.get('request-id')||r.headers.get('x-request-id')||'';if(!r.ok)throw Object.assign(new Error(payload.error?.details?.[0]?.errors?.[0]?.message||payload.error?.message||`Google Ads returned ${r.status}.`),{requestId,googlePayload:payload});return{payload,requestId}}
export async function googleAdsSearch(token,query){const id=customerId();if(!id)throw new Error('Google Ads customer ID is not configured.');const{payload}=await googleAdsPost(token,`customers/${id}/googleAds:searchStream`,{query});return(Array.isArray(payload)?payload:[payload]).flatMap(b=>Array.isArray(b.results)?b.results:[])}
export async function accountInfo(token){const rows=await googleAdsSearch(token,'SELECT customer.id, customer.descriptive_name, customer.currency_code, customer.time_zone FROM customer LIMIT 1'),c=rows[0]?.customer||{};return{id:String(c.id||customerId()),descriptiveName:c.descriptiveName||'',currencyCode:c.currencyCode||'',timeZone:c.timeZone||'UTC'}}
