import React,{useEffect,useState,useCallback} from 'react'
import {supabase} from './supabaseClient.js'
import {leadDraft,normalizedLead,submissionFields} from '../supabase/functions/formspree-webhook/model.js'
import './mioLeadAlerts.css'

export function notifyLeadChange(converted=false){
 window.dispatchEvent(new Event(converted?'mio-lead-converted':'mio-leads-refresh'))
 try{const channel=new BroadcastChannel('mio-leads');channel.postMessage({type:converted?'converted':'refresh'});channel.close()}catch{}
}
export function SubmissionDetails({lead}){
 const n=normalizedLead(lead),fields=submissionFields(lead.raw_submission||{})
 return <div className="mio-lead-details"><h3>{n.full_name||'Website inquiry'}</h3><div className="mio-lead-contact">{n.email&&<a href={'mailto:'+n.email}>{n.email}</a>}{n.phone&&<a href={'tel:'+n.phone}>{n.phone}</a>}<span>{new Date(n.submitted_at).toLocaleString()}</span></div>{n.message&&<p style={{whiteSpace:'pre-wrap'}}>{n.message}</p>}<details><summary>All submitted fields</summary><dl>{Object.entries(fields).map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{typeof v==='object'?JSON.stringify(v):String(v??'')}</dd></React.Fragment>)}</dl></details></div>
}
export function LeadReview({lead,onSaved}){
 const [types,setTypes]=useState([]),[draft,setDraft]=useState(null),[matches,setMatches]=useState([]),[matchError,setMatchError]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{let active=true;supabase.from('setting_options').select('name').eq('category','matter_type').eq('is_active',true).order('sort_order').then(({data,error})=>{if(!active)return;if(error){setError(error.message);return}setTypes(data||[]);setDraft(leadDraft(lead,data||[]))});return()=>{active=false}},[lead.id])
 useEffect(()=>{let active=true;setMatches([]);setMatchError('');if(!draft?.email?.trim())return;const timer=setTimeout(async()=>{const {data,error}=await supabase.from('clients').select('id,first_name,last_name,email,phone').ilike('email',draft.email.trim().replace(/[\\%_]/g,'\\$&'));if(active){setMatches(data||[]);setMatchError(error?.message||'')}},250);return()=>{active=false;clearTimeout(timer)}},[draft?.email])
 if(lead.matter_id)return <p role="status">Client/matter already created. <a href="#matters" onClick={e=>{e.preventDefault();window.dispatchEvent(new CustomEvent('mio-open-matter',{detail:lead.matter_id}))}}>Open matter</a></p>
 if(lead.status==='spam')return <p>This submission is marked spam. Reopen it to review for creation.</p>
 const set=(key,value)=>setDraft(d=>({...d,[key]:value,...(key==='email'?{existing_client_id:''}:{})}))
 async function approve(e){e.preventDefault();if(busy)return;setBusy(true);setError('');try{
  const {data,error}=await supabase.rpc('mio_approve_formspree_lead',{p_lead_id:lead.id,p_first:draft.first_name,p_last:draft.last_name,p_email:draft.email,p_phone:draft.phone,p_case_type:draft.case_type,p_matter_name:draft.matter_name,p_notes:draft.notes,p_existing_client:draft.existing_client_id||null})
  if(error)throw error
  notifyLeadChange(true);onSaved?.(data)
 }catch(e){setError(e.message)}finally{setBusy(false)}}
 const existing=matches.find(c=>c.id===draft?.existing_client_id)
 return <form className="mio-lead-review" onSubmit={approve}><h3>Review client and matter before creating</h3><p>Nothing is created until you approve these fields.</p>{draft&&<><fieldset disabled={busy}><div className="mio-pnc-grid">{[['first_name','Client first name','text'],['last_name','Client last name','text'],['phone','Client phone','tel'],['email','Client email','email'],['matter_name','Matter name','text']].map(([key,label,type])=><label className="mio-pnc-field" key={key}>{label}<input type={type} required={['first_name','matter_name'].includes(key)} value={draft[key]} onChange={e=>set(key,e.target.value)}/></label>)}<label className="mio-pnc-field">Case type<select required value={draft.case_type} onChange={e=>set('case_type',e.target.value)}><option value="">Choose case type</option>{types.map(t=><option key={t.name}>{t.name}</option>)}</select></label><label className="mio-pnc-field">Matter status<input readOnly value="PNC- Need to Consult"/></label><label className="mio-pnc-field">Case status<input readOnly value="Open"/></label></div><label className="mio-pnc-field">Matter notes<textarea rows={5} value={draft.notes} onChange={e=>set('notes',e.target.value)}/></label>{!!matches.length&&<label className="mio-pnc-field">This email already exists — select the client to use<select required value={draft.existing_client_id} onChange={e=>set('existing_client_id',e.target.value)}><option value="">Choose existing client</option>{matches.map(c=><option key={c.id} value={c.id}>{[c.first_name,c.last_name].filter(Boolean).join(' ')} — {c.email}</option>)}</select></label>}{existing&&<p>Use existing client: <b>{existing.first_name} {existing.last_name}</b>, {existing.email}, {existing.phone||'no phone saved'}. Its contact details will stay unchanged. The matter will link to this client.</p>}<p>The phone and email are stored on the client and displayed through the linked matter.</p></fieldset><button className="primary" disabled={busy||!!matchError||!!matches.length&&!draft.existing_client_id}>{busy?'Creating…':existing?'Approve & create matter for existing client':'Approve & create client/matter'}</button></>}{(error||matchError)&&<p role="alert" className="mio-pnc-error">{error||matchError}</p>}</form>
}
export default function MioFormspree(){
 const [leads,setLeads]=useState([]),[selected,setSelected]=useState(null),[filter,setFilter]=useState('all'),[page,setPage]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{setLoading(true);let q=supabase.from('mio_formspree_leads').select('*').order('submitted_at',{ascending:false}).order('id').range(page*50,page*50+49);if(filter!=='all')q=q.eq('status',filter);const {data,error}=await q;if(error)setError(error.message);else{setError('');setLeads(data||[]);setSelected(old=>old?(data||[]).find(l=>l.id===old.id)||null:null)}setLoading(false)},[page,filter])
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),30000);window.addEventListener('mio-leads-refresh',load);return()=>{clearInterval(timer);window.removeEventListener('mio-leads-refresh',load)}},[load])
 async function status(value){setBusy(true);const {error}=await supabase.from('mio_formspree_leads').update({status:value}).eq('id',selected.id);if(error)setError(error.message);else{notifyLeadChange();await load()}setBusy(false)}
 return <section className="mio-formspree"><h1>Formspree</h1><p>Website submissions and client/matter review.</p><div className="mio-pnc-actions"><label>Status <select value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);setSelected(null)}}>{['all','new','acknowledged','contacted','converted','declined','spam'].map(v=><option key={v} value={v}>{v}</option>)}</select></label><button disabled={loading} onClick={load}>Refresh submissions</button></div>{error&&<p role="alert">{error}</p>}{loading&&!leads.length?<p>Loading submissions…</p>:!leads.length?<p>No submissions in this view.</p>:<div className="mio-formspree-layout"><div className="mio-formspree-list">{leads.map(l=>{const n=normalizedLead(l);return <button key={l.id} aria-pressed={selected?.id===l.id} onClick={()=>setSelected(l)}><strong>{n.full_name||n.email||'Website inquiry'}</strong><span>{n.email} {n.phone}</span><small>{new Date(n.submitted_at).toLocaleString()} · {l.status}{l.matter_id?' · Matter created':''}</small></button>})}</div><article>{selected?<><SubmissionDetails lead={selected}/><div className="mio-pnc-actions"><button disabled={busy} onClick={()=>status('contacted')}>Mark contacted</button><button disabled={busy} onClick={()=>status('declined')}>Decline lead</button><button disabled={busy} onClick={()=>status('spam')}>Mark spam</button><button disabled={busy} onClick={()=>status('acknowledged')}>Reopen for review</button></div><LeadReview key={selected.id} lead={selected} onSaved={load}/></>:<p>Select a submission to see all its fields and review the proposed client and matter.</p>}</article></div>}<div className="mio-pnc-actions"><button disabled={page===0||loading} onClick={()=>{setPage(p=>p-1);setSelected(null)}}>Previous</button><span>Page {page+1}</span><button disabled={leads.length<50||loading} onClick={()=>{setPage(p=>p+1);setSelected(null)}}>Next</button></div></section>
}
