import React,{useEffect,useState} from 'react'
const cleanPath=value=>{const text=String(value||'').trim();if(!text)return '';return ('/'+text.replace(/^\/+|\/+$/g,'')).replace(/\/+/g,'/')}
const parentPath=value=>{const path=cleanPath(value);if(!path||path==='/')return '/';const parts=path.split('/').filter(Boolean);parts.pop();return '/'+parts.join('/')||'/'}
export default function MioMatterDocumentSources({matterId,getSources,onSaveDraftFolder,onBrowseOneDrive}){
 const sources=getSources?.(matterId)||{},draft=sources.draft||{},efile=sources.efile||{}
 const[path,setPath]=useState(draft.path||''),[browser,setBrowser]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 useEffect(()=>{setPath(draft.path||'');setBrowser(null);setError('');setMessage('')},[matterId,draft.path])
 async function save(value=path){if(!onSaveDraftFolder)return;setBusy(true);setError('');setMessage('');try{const saved=await onSaveDraftFolder(matterId,cleanPath(value));setPath(saved?.path||cleanPath(value));setMessage(saved?.path?'Draft folder saved to Supabase.':'Draft folder cleared.')}catch(e){setError(e.message||String(e))}finally{setBusy(false)}}
 async function browse(value){if(!onBrowseOneDrive)return;setBusy(true);setError('');try{const result=await onBrowseOneDrive({matterId,path:cleanPath(value)||'/'});setBrowser(result)}catch(e){setError(e.message||String(e))}finally{setBusy(false)}}
 const start=draft.path||parentPath(efile.path)||'/All Matters/1. Open Cases'
 return <section className="mio-block-box mio-document-sources" style={{marginTop:9}}><header><div><h3>Matter document sources</h3><span className="mio-block-note">These folders belong to this matter. Workflow steps can use Matter Documents, the OneDrive Draft folder, or the OneDrive E-file folder.</span></div></header>
 <div className="mio-block-layout"><div><strong>Matter Documents</strong><p className="mio-block-note">{Number(sources.matter_documents?.count||0)} saved document(s) currently associated with this matter.</p></div><div><strong>OneDrive E-file folder</strong><p className="mio-block-note">{efile.path||'No E-file folder is assigned to this matter yet.'}</p></div></div>
 <label>OneDrive Draft folder<input value={path} onChange={e=>setPath(e.target.value)} placeholder="/All Matters/1. Open Cases/Matter Name/Drafts"/></label>
 <div className="mio-block-tools"><button type="button" disabled={busy||path===String(draft.path||'')} onClick={()=>save()}>{busy?'Working...':'Save Draft folder'}</button><button type="button" disabled={busy||!onBrowseOneDrive} onClick={()=>browse(path||start)}>Browse OneDrive folders</button>{draft.path&&<button type="button" disabled={busy} onClick={()=>save('')}>Clear Draft folder</button>}</div>
 {error&&<p className="mio-block-error" role="alert">{error}</p>}{message&&<p className="mio-block-success" role="status">{message}</p>}
 {browser&&<div className="mio-block-panel" style={{marginTop:10}}><header><div><strong>Choose Draft folder</strong><p className="mio-block-note">{browser.path||'/'}</p></div><button type="button" onClick={()=>setBrowser(null)}>Close browser</button></header><div className="mio-block-tools"><button type="button" disabled={busy||(browser.path||'/')==='/'} onClick={()=>browse(parentPath(browser.path))}>Up one folder</button><button type="button" className="mio-block-primary" disabled={busy} onClick={async()=>{await save(browser.path||'/');setBrowser(null)}}>Use this folder</button></div><div className="mio-block-slots">{(browser.folders||[]).map(folder=><button type="button" className="mio-block-slot" key={folder.id||folder.path} disabled={busy} onClick={()=>browse(folder.path)}><strong>{folder.name}</strong><span>{folder.path}</span><span>Open folder</span></button>)}</div>{!(browser.folders||[]).length&&<p className="mio-block-note">No subfolders here.</p>}</div>}
 </section>
}
