import React,{useEffect,useRef,useState} from 'react'
import {mioCloudStore,mioStorage} from './mioCloudRuntime.js'
import {PNC_DEFAULTS,DEFAULT_INTAKES,pncStage,readyToClient,templateText,emailOK,zonedDateTime} from './mioPncModel.js'
import './mioPnc.css'
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0))
const label=s=>String(s||'not_sent').replaceAll('_',' ')
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const settingKey='caseMioPncSettingsV313'
const settings=()=>{try{return {...PNC_DEFAULTS,intakes:DEFAULT_INTAKES,...JSON.parse(mioStorage.getItem(settingKey)||'{}')}}catch{return {...PNC_DEFAULTS,intakes:DEFAULT_INTAKES}}}
export function useMioPnc({session,enabled,matters,clients,refreshMatters,refreshClients,graphFetch,supabase,onCalendarSaved,onFinanceRefresh,intakeTemplates=[]}){
 const [rows,setRows]=useState({}),[modal,setModal]=useState(null),[error,setError]=useState(''),[defaults,setDefaults]=useState(settings),[loading,setLoading]=useState(false)
 const latest=useRef();latest.current={session,matters,clients,refreshMatters,refreshClients,graphFetch,supabase,onCalendarSaved,onFinanceRefresh,rows,modal}
 async function api(action,body={}){const token=latest.current.session?.access_token;if(!token)throw Error('Sign in to Mio first.');const response=await fetch('/api/pnc',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({action,...body})});const data=await response.json().catch(()=>({error:'The PNC service did not return JSON. Check the deployment.'}));if(!response.ok||data.error)throw Error(data.error||'PNC request failed.');return data}
 function remember(data){if(data.workflow)setRows(old=>({...old,[data.workflow.matter_id]:data.workflow}));return data}
 async function load(){setLoading(true);try{const data=await api('list');setRows(Object.fromEntries((data.rows||[]).map(w=>[w.matter_id,w])));setError('')}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{setDefaults(settings());setRows({});setModal(null);setError('')},[session?.user?.id])
 useEffect(()=>{if(session?.user?.id&&enabled)void load()},[session?.user?.id,enabled])
 useEffect(()=>{if(!enabled||!session?.user?.id)return;const timer=setInterval(async()=>{if(document.hidden||latest.current.modal)return;for(const w of Object.values(latest.current.rows)){if(!pncStage(latest.current.matters.find(m=>m.id===w.matter_id)))continue;try{remember(await api('refresh',{matter_id:w.matter_id,sync:false}))}catch{}}},120000);return()=>clearInterval(timer)},[enabled,session?.user?.id])
 async function run(action,body){const data=remember(await api(action,body));if(data.matter)await latest.current.refreshMatters();if(['refresh','advance'].includes(action)&&latest.current.onFinanceRefresh)await latest.current.onFinanceRefresh();return data}
 async function create(form){const data=remember(await api('create',form));await Promise.all([latest.current.refreshClients(),latest.current.refreshMatters()]);setModal({id:data.workflow.matter_id});return data}
 async function saveSettings(value){await mioCloudStore.saveNow(settingKey,JSON.stringify(value),{throwOnError:true});setDefaults(value)}
 async function sendMessage(w,kind){
  const c=w.config,m=latest.current.matters.find(x=>x.id===w.matter_id);if(!m||!emailOK(m.clients?.email))throw Error('A valid client email is required.')
  if(c.include_date&&kind==='consult'&&w.state.calendar_delivery?.status!=='sent'){
   const start=zonedDateTime(c.consultation_start,c.time_zone||'America/Chicago'),duration=Number(c.duration||60);if(duration<5||duration>480)throw Error('Consultation duration must be 5 to 480 minutes.')
   const end=new Date(start.getTime()+duration*60000)
   if(!w.state.calendar_delivery||w.state.calendar_delivery.status==='failed'){
    const overlap=await latest.current.graphFetch('/me/calendarView?startDateTime='+encodeURIComponent(start.toISOString())+'&endDateTime='+encodeURIComponent(end.toISOString())+'&$select=subject,start,end,showAs,isCancelled',{allowInteractive:true})
    const conflicts=(overlap?.value||[]).filter(x=>!x.isCancelled&&x.showAs!=='free')
    if(conflicts.length&&!window.confirm('Your calendar has '+conflicts.length+' overlapping event(s). Schedule this consultation anyway?'))throw Error('Scheduling cancelled. No invitation was sent.')
   }
   w=(await run('claim_delivery',{matter_id:w.matter_id,kind:'calendar'})).workflow
   const requestId=w.state.calendar_delivery.reference
   let event
   try{event=await latest.current.graphFetch('/me/events',{method:'POST',allowInteractive:true,maxRetries:0,body:JSON.stringify({transactionId:requestId,subject:'Consultation - '+m.name,body:{contentType:'Text',content:templateText(c.consultation_body,values(w,m))},start:{dateTime:start.toISOString(),timeZone:'UTC'},end:{dateTime:end.toISOString(),timeZone:'UTC'},location:{displayName:c.location||''},attendees:[{emailAddress:{address:m.clients.email,name:[m.clients.first_name,m.clients.last_name].join(' ')},type:'required'}]})});if(!event?.id)throw Error('Calendar did not return an event ID.')
    w=(await run('record_delivery',{matter_id:w.matter_id,kind:'calendar',status:'sent',reference:event.id,local_id:requestId})).workflow
   }catch(e){throw Error('Calendar outcome needs review. Retry uses the same calendar transaction ID; do not create a separate event. '+e.message)}
  }
  // Save a separate calendar record only after Microsoft confirms the invitation.
  if(kind==='consult'&&c.include_date&&w.state.calendar_delivery?.status==='sent'&&!w.state.calendar_delivery.local_saved){
   const start=c.consultation_start,endLocal=new Date(new Date(start+'Z').getTime()+Number(c.duration||60)*60000).toISOString()
   const event={id:w.state.calendar_delivery.local_id,matter_id:m.id,title:'Consultation - '+m.name,event_category:'Consultation',start_date:start.slice(0,10),start_time:start.slice(11,16),end_date:endLocal.slice(0,10),end_time:endLocal.slice(11,16),description:(c.location||'')+' / '+(c.time_zone||'America/Chicago')+' / Microsoft calendar event: '+w.state.calendar_delivery.reference,is_active:true}
   const {error}=await latest.current.supabase.from('calendar_events').upsert(event,{onConflict:'id'});if(error)throw Error('Invitation was sent, but the Mio calendar copy failed. Retry will save the copy without sending another invitation. '+error.message)
   latest.current.onCalendarSaved(event);w=(await run('record_delivery',{matter_id:w.matter_id,kind:'calendar',status:'sent',reference:w.state.calendar_delivery.reference,local_id:event.id,local_saved:true})).workflow
  }
  if(w.state[kind+'_delivery']?.status==='sent')return {workflow:w}
  w=(await run('claim_delivery',{matter_id:w.matter_id,kind})).workflow
  const v=values(w,m),subject=templateText(c[kind+'_subject'],v),text=templateText(c[kind+'_body'],v)
  try{await latest.current.graphFetch('/me/sendMail',{method:'POST',allowInteractive:true,maxRetries:0,body:JSON.stringify({message:{subject,body:{contentType:'HTML',content:'<div style="white-space:pre-wrap">'+esc(text).replace(/https:\/\/[^\s<>]+/g,u=>'<a href="'+u+'">'+u+'</a>')+'</div>'},toRecipients:[{emailAddress:{address:m.clients.email}}]},saveToSentItems:true})})}catch(e){throw Error('Email delivery is uncertain. Check Sent Items before using the retry control; the payment and signature requests have been preserved. '+e.message)}
  return run('record_delivery',{matter_id:w.matter_id,kind,status:'sent',reference:w.state[kind+'_delivery'].reference})
 }
 return {rows,modal,setModal,error,loading,defaults,run,load,create,saveSettings,sendMessage,clients,matters,intakeTemplates,openNew:()=>setModal({new:true,key:crypto.randomUUID()}),open:m=>setModal({id:m.id})}
}
function values(w,m){const c=w.config||{},s=w.state||{},v={client_name:[m?.clients?.first_name,m?.clients?.last_name].filter(Boolean).join(' ')||m?.name,consult_fee:money(c.consult_fee),retainer:money(c.retainer),payment_link:s[pncStage(m)==='consult'?'consult_request':'retainer_request']?.url||'[Prepare payment link]',signature_link:s.signature?.url||'[Dropbox Sign will send the secure signing link in a separate email]',intake_link:s.intake?.url||'[Prepare intake link]',consultation_date:c.consultation_start?c.consultation_start.replace('T',' ')+' ('+(c.time_zone||'America/Chicago')+')':'',location:c.location||''};v.intake_section=c.include_intake?templateText(c.intake_body,v):'';v.consultation_section=c.include_date?templateText(c.consultation_body,v):'';return v}
function Field({name,children}){return <label className="mio-pnc-field"><span>{name}</span>{React.isValidElement(children)?React.cloneElement(children,{'aria-label':name}):children}</label>}
function Dialog({title,children,onClose,busy}){return <div className="mio-pnc-overlay"><section role="dialog" aria-modal="true" aria-label={title} className="mio-pnc-dialog"><header><h2>{title}</h2><button type="button" onClick={onClose} disabled={busy}>Close</button></header>{children}</section></div>}
function Status({title,value}){return <span className="mio-pnc-badge" data-state={value||'not_sent'}>{title}: <b>{label(value)}</b></span>}
export function MioPncRow({matter,workflow,control,colSpan}){const stage=pncStage(matter),s=workflow?.state||{};return <tr className="mio-pnc-row"><td colSpan={colSpan}><div className="mio-pnc-row-head"><div><strong>{matter.name}</strong><div>{matter.matter_type} / {matter.matter_status}</div><small>{matter.clients?.email} {matter.clients?.phone}</small></div><button onClick={()=>control.open(matter)}>{stage==='consult'?'Send consult fee / intake':'Fee agreement / retainer'}</button></div><div className="mio-pnc-actions">{stage==='consult'?<><Status title="Consult email" value={s.consult_delivery?.status}/><Status title="Consult fee" value={s.consult?.status}/><Status title="Intake" value={s.intake?.status||'not_requested'}/><Status title="Calendar invite" value={s.calendar_delivery?.status}/></>:<><Status title="Agreement" value={s.signature?.status}/><Status title="Retainer" value={s.retainer?.status}/><Status title="Intake" value={s.intake?.status||'not_requested'}/>{readyToClient(s)&&<b>Ready for your approval to become a client</b>}</>}</div>{s.checked_at&&<small>Payment/signature checked {new Date(s.checked_at).toLocaleString()}</small>}</td></tr>}
export function MioPncModal({control:ctrl,caseTypes}){
 const modal=ctrl.modal;if(!modal)return null
 if(modal.new)return <NewPnc key={modal.key} ctrl={ctrl} caseTypes={caseTypes}/>
 const m=ctrl.matters.find(x=>x.id===modal.id),w=ctrl.rows[modal.id]
 if(!m||!w)return <Dialog title="PNC workflow" onClose={()=>ctrl.setModal(null)}><p role="alert">{ctrl.error||'The PNC record is not loaded. Reload it, or initialize this existing PNC matter.'}</p><button onClick={()=>ctrl.load()}>Reload PNC records</button>{m&&!w&&<button onClick={async()=>{try{await ctrl.run('initialize',{matter_id:m.id})}catch(e){window.alert(e.message)}}}>Initialize existing PNC</button>}</Dialog>
 if(!pncStage(m))return <Dialog title="Client ready to draft" onClose={()=>ctrl.setModal(null)}><p>The matter is now {m.matter_status} and appears as a regular matter row.</p></Dialog>
 return <Editor key={m.id} ctrl={ctrl} matter={m} initial={w}/>
}
function NewPnc({ctrl,caseTypes}){
 const [form,setForm]=useState({first_name:'',last_name:'',email:'',phone:'',case_type:caseTypes?.[0]?.name||'SAPCR/Modification',existing_client_id:''}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const duplicates=ctrl.clients.filter(c=>c.email&&c.email.trim().toLowerCase()===form.email.trim().toLowerCase())
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{await ctrl.create({...form,key:ctrl.modal.key})}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <Dialog title="Add potential new client" busy={busy} onClose={()=>ctrl.setModal(null)}><form onSubmit={submit}><div className="mio-pnc-grid">{[['first_name','First name','text'],['last_name','Last name','text'],['email','Email address','email'],['phone','Phone number','tel']].map(([key,name,type])=><Field key={key} name={name}><input required={key!=='phone'} type={type} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value,existing_client_id:key==='email'?'':form.existing_client_id})}/></Field>)}<Field name="Case type"><select value={form.case_type} onChange={e=>setForm({...form,case_type:e.target.value})}>{caseTypes.map(t=><option key={t.name}>{t.name}</option>)}</select></Field></div>{!!duplicates.length&&<Field name="This email already exists. Select the client to reuse"><select required value={form.existing_client_id} onChange={e=>setForm({...form,existing_client_id:e.target.value})}><option value="">Choose existing client</option>{duplicates.map(c=><option key={c.id} value={c.id}>{c.first_name} {c.last_name}</option>)}</select></Field>}<p>Creates a client and an open matter with status PNC- Need to Consult. It does not send anything yet.</p>{error&&<p role="alert" className="mio-pnc-error">{error}</p>}<button disabled={busy}>{busy?'Saving...':'Create PNC'}</button></form></Dialog>
}
function Editor({ctrl,matter:m,initial}){
 const configBaseline=useRef(initial.config)
 const [c,setC]=useState(()=>({...ctrl.defaults,...initial.config})),[revision,setRevision]=useState(initial.revision),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const w=ctrl.rows[m.id]||initial,s=w.state||{},stage=pncStage(m),templates=[...(ctrl.defaults.intakes||DEFAULT_INTAKES),...ctrl.intakeTemplates.filter(t=>t.is_active!==false)],kind=stage==='consult'?'consult':'engage'
 const set=(k,v)=>setC(x=>({...x,[k]:v}));const input=(key,name,type='text',disabled=false)=><Field name={name}><input type={type} value={c[key]??''} disabled={disabled} onChange={e=>set(key,e.target.value)}/></Field>
 async function action(fn){if(busy)return;setBusy(true);setError('');setNotice('');try{const r=await fn();if(r?.workflow)setRevision(r.workflow.revision);return r}catch(e){setError(e.message);await ctrl.load()}finally{setBusy(false)}}
 async function save(){if(w.revision!==revision&&JSON.stringify(w.config)!==JSON.stringify(configBaseline.current))throw Error('This draft changed in another window. Close and reopen it before saving.');const r=await ctrl.run('save',{matter_id:m.id,revision:w.revision,config:c});configBaseline.current=r.workflow.config;setRevision(r.workflow.revision);return r.workflow}
 async function prepare(){await save();const r=await ctrl.run(stage==='consult'?'prepare_consult':'prepare_engagement',{matter_id:m.id});setRevision(r.workflow.revision);setNotice('Links prepared. Review the message below before sending.');return r}
 async function send(){const r=await prepare();if(!window.confirm('Send '+(stage==='consult'?'this consultation email'+(c.include_date?' and calendar invitation':''):'the fee agreement through Dropbox Sign and this retainer email')+' to '+m.clients.email+'?'))return r
  let sendW=r.workflow
  if(stage==='engage'){const signed=await ctrl.run('send_signature',{matter_id:m.id,confirmed:true});sendW=signed.workflow;setRevision(sendW.revision)}
  const sent=await ctrl.sendMessage(sendW,kind);setNotice('Sent. This row will show provider payment and signature status after Refresh status.');return sent
 }
 const reset=async kind=>{if(!window.confirm('Check Sent Items / Dropbox Sign first. Confirm no '+kind+' email was sent and allow another attempt?'))return;return ctrl.run('reset_delivery',{matter_id:m.id,kind,confirmed:true})}
 return <Dialog title={stage==='consult'?'Consultation - '+m.name:'Fee agreement and retainer - '+m.name} busy={busy} onClose={()=>ctrl.setModal(null)}>
  <p><b>{m.matter_status}</b> / {m.clients?.email}</p><fieldset disabled={busy}><div className="mio-pnc-grid">
  {stage==='consult'?<>{input('consult_fee','Consultation fee (operating account)','number',!!s.consult_request)}<Field name="Include intake form"><input type="checkbox" checked={!!c.include_intake} onChange={e=>set('include_intake',e.target.checked)} disabled={!!s.intake}/></Field>{c.include_intake&&<Field name="Intake form"><select disabled={!!s.intake} value={c.intake_template?.id||''} onChange={e=>set('intake_template',templates.find(t=>t.id===e.target.value))}><option value="">Select form</option>{templates.map((t,i)=><option key={t.id+':'+i} value={t.id}>{t.name}</option>)}</select></Field>}<Field name="Add consultation to calendar and invite client"><input type="checkbox" checked={!!c.include_date} disabled={!!s.calendar_delivery} onChange={e=>set('include_date',e.target.checked)}/></Field>{c.include_date&&<>{input('consultation_start','Consultation date and time','datetime-local',!!s.calendar_delivery)}{input('duration','Duration (minutes)','number',!!s.calendar_delivery)}{input('time_zone','Time zone (IANA, e.g. America/Chicago)','text',!!s.calendar_delivery)}{input('location','Location or video meeting link','text',!!s.calendar_delivery)}</>}</>:<>{input('retainer','Retainer amount (trust account)','number',!!s.retainer_request)}{input('signature_template_id','Dropbox Sign fee-agreement template ID','text',!!s.signature?.id)}{input('signer_role','Client signer role (exact template role)','text',!!s.signature?.id)}<Field name="Additional agreement merge fields (JSON)"><textarea disabled={!!s.signature?.id} rows={3} value={c.signature_fields||'{}'} onChange={e=>set('signature_fields',e.target.value)}/></Field><p>Use a Dropbox Sign template configured with the client as the only signer. Edit default template and retainer in PNC Settings.</p></>}
  {input(kind+'_subject','Email subject')}<Field name="Email template"><textarea rows={7} value={c[kind+'_body']||''} onChange={e=>set(kind+'_body',e.target.value)}/></Field>{stage==='consult'&&c.include_date&&<Field name="Consultation wording"><textarea rows={3} value={c.consultation_body||''} onChange={e=>set('consultation_body',e.target.value)}/></Field>}{stage==='consult'&&c.include_intake&&<Field name="Intake wording"><textarea rows={3} value={c.intake_body||''} onChange={e=>set('intake_body',e.target.value)}/></Field>}
  </div></fieldset>
  <div className="mio-pnc-actions"><button disabled={busy} onClick={()=>action(async()=>({workflow:await save()}))}>Save draft</button><button disabled={busy} onClick={()=>action(prepare)}>Prepare links and preview</button><button disabled={busy||s[kind+'_delivery']?.status==='sent'||s[kind+'_delivery']?.status==='sending'} onClick={()=>action(send)}>{stage==='consult'?'Send consultation email':'Send fee agreement and retainer email'}</button><button disabled={busy} onClick={()=>action(()=>ctrl.run('refresh',{matter_id:m.id,sync:true}))}>Refresh status</button></div>
  {s[kind+'_delivery']?.status==='sending'&&<p className="mio-pnc-error">A prior email attempt has an uncertain outcome. Check Sent Items. <button disabled={busy} onClick={()=>action(()=>reset(kind))}>Verified not sent: allow retry</button></p>}
  {(s.consult_preparing||s.retainer_preparing)&&<p className="mio-pnc-error">A payment-link preparation did not finish. No card charge was initiated by Mio. <button disabled={busy} onClick={()=>action(async()=>{if(window.confirm('Allow payment-link preparation to be retried? Existing matching links are reused.'))return ctrl.run('reset_preparation',{matter_id:m.id,kind:s.consult_preparing?'consult':'retainer',confirmed:true})})}>Recover link preparation</button></p>}
  {s.signature_sending&&<p className="mio-pnc-error">Dropbox Sign send needs reconciliation. <button onClick={()=>action(async()=>{const id=window.prompt('Paste the existing Dropbox Sign request ID after checking its status:');return id?ctrl.run('link_signature',{matter_id:m.id,signature_request_id:id}):null})}>Link existing signature request</button></p>}
  {notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className="mio-pnc-error">{error}</p>}{s.warnings?.map(x=><p key={x} className="mio-pnc-error">{x}</p>)}
  <details open><summary>Email preview</summary><p><b>{templateText(c[kind+'_subject'],values({...w,config:c},m))}</b></p><pre className="mio-pnc-preview">{templateText(c[kind+'_body'],values({...w,config:c},m))}</pre></details>
  <div className="mio-pnc-actions"><Status title="Consult fee" value={s.consult?.status}/><Status title="Intake" value={s.intake?.status||'not_requested'}/><Status title="Agreement" value={s.signature?.status}/><Status title="Retainer" value={s.retainer?.status}/></div>
  {s.retainer&&<p>Retainer: paid {money(s.retainer.paid_cents/100)}, processing {money(s.retainer.processing_cents/100)} of {money(s.retainer.required_cents/100)}.</p>}
  {s.intake?.id&&<button disabled={busy} onClick={()=>action(async()=>{const data=await ctrl.run('intake_answers',{matter_id:m.id});window.alert(Object.entries(data.answers||{}).map(([k,v])=>k+': '+(typeof v==='object'?JSON.stringify(v):v)).join('\n\n')||'No intake submitted yet.')})}>View intake answers</button>}
  <hr/><button disabled={busy||(stage==='engage'&&!readyToClient(s))} onClick={()=>action(async()=>{if(!window.confirm(stage==='consult'?'The client has told you to move forward. Change status to Consult- Need to Client?':'Verify the signed agreement and full paid/processing retainer, then change status to Client-Need to Draft?'))return;return ctrl.run('advance',{matter_id:m.id,confirmed:true})})}>{stage==='consult'?'Client wants to move forward':'Move to Client-Need to Draft'}</button><p>{stage==='engage'?'Both the signed agreement and full retainer paid or processing are required. The server rechecks them before advancing.':'Consultation payment and intake are tracked independently. Advancing is your explicit decision.'}</p>
 </Dialog>
}
export function MioPncSettings({control:ctrl}){
 const [c,setC]=useState(ctrl.defaults),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[templates,setTemplates]=useState([]),[idx,setIdx]=useState(0)
 const set=(k,v)=>setC(x=>({...x,[k]:v})),intakes=c.intakes||DEFAULT_INTAKES,t=intakes[idx]||intakes[0]
 const editIntake=patch=>set('intakes',intakes.map(x=>x.id===t.id?{...x,...patch}:x))
 async function act(fn){setBusy(true);setMessage('');try{await fn()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 return <section className="mio-pnc-settings"><h2>PNC workflow settings</h2><p>New PNC drafts copy these defaults. Existing requests keep their saved settings and amounts.</p><fieldset disabled={busy}><div className="mio-pnc-grid">{[['retainer','Default retainer (trust)','number'],['consult_fee','Default consultation fee (operating; may be blank)','number'],['duration','Default consultation duration (minutes)','number'],['time_zone','Time zone','text'],['signature_template_id','Dropbox Sign fee-agreement template ID','text'],['signer_role','Client signer role','text']].map(([key,name,type])=><Field key={key} name={name}><input type={type} value={c[key]??''} onChange={e=>set(key,e.target.value)}/></Field>)}</div>
 <button onClick={()=>act(async()=>setTemplates((await ctrl.run('templates',{})).templates))}>Load Dropbox Sign templates</button>{templates.length>0&&<Field name="Choose fee-agreement template"><select value={c.signature_template_id||''} onChange={e=>{const t=templates.find(t=>t.id===e.target.value);setC(x=>({...x,signature_template_id:t?.id||'',signer_role:t?.signer_roles?.[0]?.name||''}))}}><option value="">Choose template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.title} ({t.signer_roles.map(r=>r.name).join(', ')})</option>)}</select></Field>}<p>The fee-agreement template must have one client signer and no required CC roles. Configure its content in Dropbox Sign; Mio supplies the client name and email. Supported sender merge fields: client_name, client_email, client_phone, first_name, last_name, retainer, case_type, matter_name, date. Add other fields by their exact template names as JSON below.</p><Field name="Default agreement merge fields (JSON)"><textarea rows={3} value={c.signature_fields||'{}'} onChange={e=>set('signature_fields',e.target.value)}/></Field>
 <details><summary>Email templates</summary><p>Fields: {'{{client_name}}, {{payment_link}}, {{consult_fee}}, {{retainer}}, {{signature_link}}, {{intake_section}}, {{consultation_section}}, {{consultation_date}}, {{location}}, {{intake_link}}'}.</p>{[['consult_subject','Consultation subject'],['consult_body','Consultation email'],['consultation_body','Consultation date wording'],['intake_body','Intake wording'],['engage_subject','Engagement subject'],['engage_body','Agreement and retainer email']].map(([k,name])=><Field key={k} name={name}><textarea rows={k.endsWith('subject')?1:5} value={c[k]||''} onChange={e=>set(k,e.target.value)}/></Field>)}</details>
 <h3>Intake forms</h3><select aria-label="Intake template to edit" value={idx} onChange={e=>setIdx(Number(e.target.value))}>{intakes.map((x,i)=><option value={i} key={x.id}>{x.name}</option>)}</select><Field name="Form title"><input value={t.name} onChange={e=>editIntake({name:e.target.value})}/></Field><Field name="Introduction"><textarea value={t.description||''} onChange={e=>editIntake({description:e.target.value})}/></Field>
 {t.questions.map((q,i)=><div className="mio-pnc-question" key={q.id||q.key}><Field name={'Question '+(i+1)}><input value={q.label} onChange={e=>editIntake({questions:t.questions.map((r,j)=>i===j?{...r,label:e.target.value}:r)})}/></Field><select aria-label={'Question '+(i+1)+' type'} value={q.type} onChange={e=>editIntake({questions:t.questions.map((r,j)=>i===j?{...r,type:e.target.value}:r)})}>{['text','textarea','email','tel','date','children'].map(type=><option key={type}>{type}</option>)}</select><label><input type="checkbox" checked={!!q.required} onChange={e=>editIntake({questions:t.questions.map((r,j)=>i===j?{...r,required:e.target.checked}:r)})}/> Required</label><button onClick={()=>editIntake({questions:t.questions.filter((_,j)=>j!==i)})}>Remove question</button></div>)}<button onClick={()=>{const id='q_'+crypto.randomUUID().replaceAll('-','');editIntake({questions:[...t.questions,{id,key:id,label:'New question',type:'textarea',required:false,group:'Case information'}]})}}>Add question</button>
 </fieldset><button disabled={busy} onClick={()=>act(async()=>{if(!(Number(c.retainer)>0))throw Error('Default retainer must be positive.');await ctrl.saveSettings(c);setMessage('PNC settings saved to Supabase.')})}>Save PNC settings</button>{message&&<p role="status">{message}</p>}</section>
}
