import React,{useEffect,useState}from'react'
import{FINDING_DIRECTIONS,SOURCE_TYPES,RESEARCH_TOPICS,normalizePublicationDraft,validatePublicationForPublish}from'../lib/research/model.js'
import{getResearchPublication,saveResearchPublication,replaceResearchStudies,replaceResearchAccessLinks,replaceResearchMetrics,replaceResearchReviewMemberships,setResearchEditorialStatus}from'../lib/research/repository.js'
import'./mioResearch.css'

const blankPublication=()=>normalizePublicationDraft({title:'',authors_text:'',publication_year:null,source_type:'original_empirical',finding_direction:'mixed',topics:[],editorial_status:'draft',score_notes:{}})
const blankStudy=()=>({study_label:'Analysis',extraction_status:'unverified',country_text:'',sample_size:null,child_age_text:'',parenting_time_definition:'',exact_or_near_50_50:null,comparator:'',study_design:'',outcomes_measured:'',controls_summary:'',longitudinal:null,pre_separation_controls:null,conflict_controls:null,ses_controls:null,effect_size_summary:'',result_direction:'mixed',result_summary:'',key_limitation:'',causal_claim_strength:'not_applicable'})
const blankLink=()=>({link_type:'canonical',url:'',access_status:'unknown',license_text:'',redistribution_permitted:false,is_preferred:false,is_public:true,checked_at:null})
const blankMetric=()=>({provider:'',metric_type:'citation_count',metric_value:'',source_url:'',captured_at:new Date().toISOString().slice(0,10)})
const blankMembership=()=>({review_publication_id:'',membership_status:'included',membership_note:'',verified_at:null})
const textLabel=v=>String(v||'').replaceAll('_',' ')
function Field({label,children}){return <label className="mio-research-field"><span>{label}</span>{children}</label>}
function Toggle({label,value,onChange}){return <label className="mio-research-toggle"><input type="checkbox" checked={value===true} onChange={e=>onChange(e.target.checked)}/>{label}</label>}

export default function MioResearchEditor({publicationId,onClose,supabase,session}){
 const[publication,setPublication]=useState(blankPublication),[studies,setStudies]=useState([]),[accessLinks,setAccessLinks]=useState([]),[metrics,setMetrics]=useState([]),[memberships,setMemberships]=useState([]),[loading,setLoading]=useState(!!publicationId),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[publishErrors,setPublishErrors]=useState([])
 useEffect(()=>{if(!publicationId)return;let live=true;(async()=>{setLoading(true);try{const b=await getResearchPublication(supabase,publicationId);if(!live)return;setPublication(b.publication);setStudies(b.studies);setAccessLinks(b.accessLinks);setMetrics(b.metrics);setMemberships(b.reviewMemberships)}catch(e){if(live)setError(e.message)}finally{if(live)setLoading(false)}})();return()=>{live=false}},[publicationId])
 const set=(k,v)=>setPublication(p=>({...p,[k]:v})),setScore=(k,v)=>{try{const n=normalizePublicationDraft({...publication,[k]:v});setPublication(n);setError('')}catch(e){setError(e.message)}}
 const update=(setter,i,key,value)=>setter(rows=>rows.map((r,n)=>n===i?{...r,[key]:value}:r))
 async function save(){setSaving(true);setError('');setNotice('');try{const saved=await saveResearchPublication(supabase,{...publication,updated_by:session?.user?.id});setPublication(saved);try{await replaceResearchStudies(supabase,saved.id,studies)}catch(e){throw new Error('Publication saved, but studies failed: '+e.message)}try{await replaceResearchAccessLinks(supabase,saved.id,accessLinks.filter(x=>String(x.url||'').trim()))}catch(e){throw new Error('Publication saved, but access links failed: '+e.message)}try{await replaceResearchMetrics(supabase,saved.id,metrics.filter(x=>x.metric_value!==''&&x.metric_value!==null).map(x=>({...x,metric_value:Number(x.metric_value),captured_at:x.captured_at?new Date(x.captured_at).toISOString():new Date().toISOString()})))}catch(e){throw new Error('Publication saved, but metrics failed: '+e.message)}try{await replaceResearchReviewMemberships(supabase,saved.id,memberships.filter(x=>x.review_publication_id))}catch(e){throw new Error('Publication saved, but review memberships failed: '+e.message)}const fresh=await getResearchPublication(supabase,saved.id);setPublication(fresh.publication);setStudies(fresh.studies);setAccessLinks(fresh.accessLinks);setMetrics(fresh.metrics);setMemberships(fresh.reviewMemberships);setNotice('Saved');return fresh}catch(e){setError(e.message);throw e}finally{setSaving(false)}}
 async function changeStatus(status){setPublishErrors([]);try{if(status==='published'){const errs=validatePublicationForPublish(publication,{studies,accessLinks});if(errs.length){setPublishErrors(errs);return}}const bundle=await save();const row=await setResearchEditorialStatus(supabase,bundle.publication.id,status,session?.user?.id);setPublication(row);setNotice(textLabel(status))}catch(e){setError(e.message)}}
 if(loading)return <section className="mio-research"><p>Loading publication…</p></section>
 return <section className="mio-research mio-research-editor" aria-label="Research publication editor">
  <div className="mio-research-actions"><div><h1>{publication.id?'Edit research publication':'New research publication'}</h1><p className="mio-research-note">Direction describes the finding. It never changes the four quality/relevance scores.</p></div><div><button type="button" onClick={onClose}>Back to research</button> <button type="button" disabled={saving} onClick={()=>void save()}>{saving?'Saving…':'Save'}</button></div></div>
  {error&&<div role="alert" className="mio-research-error">{error}</div>}{notice&&<div role="status">{notice}</div>}{publishErrors.length>0&&<div role="alert" className="mio-research-error"><b>Cannot publish yet:</b><ul>{publishErrors.map(e=><li key={e}>{e}</li>)}</ul></div>}
  <EditorSection title="Bibliography"><div className="mio-research-form-grid"><Field label="Title"><input aria-label="Title" value={publication.title||''} onChange={e=>set('title',e.target.value)}/></Field><Field label="Authors"><input aria-label="Authors" value={publication.authors_text||''} onChange={e=>set('authors_text',e.target.value)}/></Field><Field label="Year"><input aria-label="Year" type="number" value={publication.publication_year??''} onChange={e=>set('publication_year',e.target.value===''?null:Number(e.target.value))}/></Field><Field label="Journal / publisher"><input value={publication.journal_or_publisher||''} onChange={e=>set('journal_or_publisher',e.target.value)}/></Field><Field label="DOI"><input value={publication.doi||''} onChange={e=>set('doi',e.target.value)}/></Field><Field label="Source type"><select aria-label="Source type" value={publication.source_type} onChange={e=>set('source_type',e.target.value)}>{SOURCE_TYPES.map(v=><option key={v} value={v}>{textLabel(v)}</option>)}</select></Field><Field label="Country"><input value={publication.country_text||''} onChange={e=>set('country_text',e.target.value)}/></Field><Field label="Admission route"><input value={publication.admission_route||''} onChange={e=>set('admission_route',e.target.value)}/></Field></div></EditorSection>
  <EditorSection title="Research conclusion"><div className="mio-research-form-grid"><Field label="Finding direction"><select aria-label="Editor finding direction" value={publication.finding_direction} onChange={e=>set('finding_direction',e.target.value)}>{FINDING_DIRECTIONS.map(v=><option key={v} value={v}>{textLabel(v)}</option>)}</select></Field></div>{[['overall_findings_summary','Findings summary'],['limitations_summary','Limitations'],['what_it_supports','What it supports'],['what_it_does_not_establish','What it does not establish']].map(([k,l])=><Field key={k} label={l}><textarea aria-label={l} value={publication[k]||''} onChange={e=>set(k,e.target.value)}/></Field>)}</EditorSection>
  <EditorSection title="Scores"><div className="mio-research-form-grid">{[['evidence_strength_score','Evidence Strength'],['impact_score','Impact'],['equal_parenting_relevance_score','Equal-Parenting Relevance'],['historical_field_importance_score','Historical / Field Importance']].map(([k,l])=><Field key={k} label={l}><input aria-label={l} type="number" min="0" max="100" value={publication[k]??''} onChange={e=>setScore(k,e.target.value)}/></Field>)}</div></EditorSection>
  <EditorSection title="Topics"><div className="mio-research-topics">{RESEARCH_TOPICS.map(t=><label key={t}><input type="checkbox" checked={(publication.topics||[]).includes(t)} onChange={e=>set('topics',e.target.checked?[...(publication.topics||[]),t]:(publication.topics||[]).filter(x=>x!==t))}/>{textLabel(t)}</label>)}</div></EditorSection>
  <EditorSection title="Studies / analyses" action="Add analysis" onAction={()=>setStudies(x=>[...x,blankStudy()])}>{studies.map((s,i)=><div className="mio-research-child" key={s.id||i}><button type="button" className="mio-research-remove" onClick={()=>setStudies(x=>x.filter((_,n)=>n!==i))}>Remove analysis</button><div className="mio-research-form-grid"><Field label="Analysis label"><input value={s.study_label||''} onChange={e=>update(setStudies,i,'study_label',e.target.value)}/></Field><Field label="Sample N"><input type="number" value={s.sample_size??''} onChange={e=>update(setStudies,i,'sample_size',e.target.value===''?null:Number(e.target.value))}/></Field><Field label="Child ages"><input value={s.child_age_text||''} onChange={e=>update(setStudies,i,'child_age_text',e.target.value)}/></Field><Field label="Exact parenting-time definition"><input aria-label={`Parenting time definition ${i+1}`} value={s.parenting_time_definition||''} onChange={e=>update(setStudies,i,'parenting_time_definition',e.target.value)}/></Field><Field label="Comparator"><input value={s.comparator||''} onChange={e=>update(setStudies,i,'comparator',e.target.value)}/></Field><Field label="Design"><input value={s.study_design||''} onChange={e=>update(setStudies,i,'study_design',e.target.value)}/></Field><Field label="Causal claim strength"><select aria-label={`Causal claim strength ${i+1}`} value={s.causal_claim_strength||'not_applicable'} onChange={e=>update(setStudies,i,'causal_claim_strength',e.target.value)}>{['not_applicable','very_low','low','moderate','high'].map(v=><option key={v} value={v}>{textLabel(v)}</option>)}</select></Field><Field label="Extraction status"><select value={s.extraction_status||'unverified'} onChange={e=>update(setStudies,i,'extraction_status',e.target.value)}>{['unverified','needs_review','verified'].map(v=><option key={v} value={v}>{textLabel(v)}</option>)}</select></Field></div><Toggle label="Exact or near 50/50" value={s.exact_or_near_50_50} onChange={v=>update(setStudies,i,'exact_or_near_50_50',v)}/><Field label="Outcomes measured"><textarea value={s.outcomes_measured||''} onChange={e=>update(setStudies,i,'outcomes_measured',e.target.value)}/></Field><Field label="Controls"><textarea value={s.controls_summary||''} onChange={e=>update(setStudies,i,'controls_summary',e.target.value)}/></Field><Field label="Result summary"><textarea value={s.result_summary||''} onChange={e=>update(setStudies,i,'result_summary',e.target.value)}/></Field><Field label="Key limitation"><textarea value={s.key_limitation||''} onChange={e=>update(setStudies,i,'key_limitation',e.target.value)}/></Field></div>)}</EditorSection>
  <EditorSection title="Access" action="Add link" onAction={()=>setAccessLinks(x=>[...x,blankLink()])}>{accessLinks.map((a,i)=><div className="mio-research-child" key={a.id||i}><button type="button" className="mio-research-remove" onClick={()=>setAccessLinks(x=>x.filter((_,n)=>n!==i))}>Remove link</button><div className="mio-research-form-grid"><Field label="Link type"><select value={a.link_type} onChange={e=>{const type=e.target.value;setAccessLinks(rows=>rows.map((r,n)=>n===i?{...r,link_type:type,is_public:type==='mio_public_copy'&&!r.redistribution_permitted?false:r.is_public}:r))}}>{['canonical','publisher','abstract','full_text_oa','repository','purchase','mio_public_copy'].map(v=><option key={v} value={v}>{textLabel(v)}</option>)}</select></Field><Field label="URL"><input aria-label={`Access URL ${i+1}`} value={a.url||''} onChange={e=>update(setAccessLinks,i,'url',e.target.value)}/></Field><Field label="Access status"><input value={a.access_status||''} onChange={e=>update(setAccessLinks,i,'access_status',e.target.value)}/></Field><Field label="License / permission"><input value={a.license_text||''} onChange={e=>update(setAccessLinks,i,'license_text',e.target.value)}/></Field></div><Toggle label="Redistribution permitted" value={a.redistribution_permitted} onChange={v=>setAccessLinks(rows=>rows.map((r,n)=>n===i?{...r,redistribution_permitted:v,is_public:r.link_type==='mio_public_copy'&&!v?false:r.is_public}:r))}/><Toggle label="Public link" value={a.is_public} onChange={v=>update(setAccessLinks,i,'is_public',a.link_type==='mio_public_copy'&&!a.redistribution_permitted?false:v)}/><Toggle label="Preferred link" value={a.is_preferred} onChange={v=>update(setAccessLinks,i,'is_preferred',v)}/></div>)}</EditorSection>
  <EditorSection title="Metrics" action="Add metric" onAction={()=>setMetrics(x=>[...x,blankMetric()])}>{metrics.map((m,i)=><div className="mio-research-child" key={m.id||i}><button type="button" className="mio-research-remove" onClick={()=>setMetrics(x=>x.filter((_,n)=>n!==i))}>Remove metric</button><div className="mio-research-form-grid"><Field label="Provider"><input value={m.provider||''} onChange={e=>update(setMetrics,i,'provider',e.target.value)}/></Field><Field label="Metric type"><input value={m.metric_type||''} onChange={e=>update(setMetrics,i,'metric_type',e.target.value)}/></Field><Field label="Value"><input type="number" value={m.metric_value??''} onChange={e=>update(setMetrics,i,'metric_value',e.target.value)}/></Field><Field label="Source URL"><input value={m.source_url||''} onChange={e=>update(setMetrics,i,'source_url',e.target.value)}/></Field><Field label="Captured date"><input type="date" value={String(m.captured_at||'').slice(0,10)} onChange={e=>update(setMetrics,i,'captured_at',e.target.value)}/></Field></div></div>)}</EditorSection>
  <EditorSection title="Review membership" action="Add membership" onAction={()=>setMemberships(x=>[...x,blankMembership()])}>{memberships.map((m,i)=><div className="mio-research-child" key={m.id||i}><button type="button" className="mio-research-remove" onClick={()=>setMemberships(x=>x.filter((_,n)=>n!==i))}>Remove membership</button><div className="mio-research-form-grid"><Field label="Review publication ID"><input value={m.review_publication_id||''} onChange={e=>update(setMemberships,i,'review_publication_id',e.target.value)}/></Field><Field label="Membership status"><input value={m.membership_status||''} onChange={e=>update(setMemberships,i,'membership_status',e.target.value)}/></Field></div><Field label="Membership note"><textarea value={m.membership_note||''} onChange={e=>update(setMemberships,i,'membership_note',e.target.value)}/></Field></div>)}</EditorSection>
  <EditorSection title="Editorial status"><div className="mio-research-status-actions">{['draft','needs_review','published','archived'].map(v=><button type="button" key={v} disabled={saving||publication.editorial_status===v} onClick={()=>void changeStatus(v)}>{textLabel(v)}</button>)}</div></EditorSection>
 </section>
}
function EditorSection({title,action,onAction,children}){return <section className="mio-research-panel mio-research-editor-section"><header><h2>{title}</h2>{action&&<button type="button" onClick={onAction}>{action}</button>}</header>{children}</section>}
