import React,{useMemo,useState} from 'react'
const money=n=>Number(n||0).toLocaleString(undefined,{style:'currency',currency:'USD'})
const date=v=>v?new Date(v).toLocaleDateString():'Not recorded'
export default function WithdrawalTrustPanel({rows=[],renderGraph,onEnter,onRelease,onRefresh}){
 const [open,setOpen]=useState(true),[scope,setScope]=useState('active'),[caseType,setCaseType]=useState(''),[matterStatus,setMatterStatus]=useState(''),[selected,setSelected]=useState(''),[days,setDays]=useState('90'),[markers,setMarkers]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const filtered=useMemo(()=>rows.filter(r=>(!caseType||r.case_type===caseType)&&(!matterStatus||r.matter_status===matterStatus)&&(!selected||r.matter_id===selected)&&(scope==='all'||scope==='candidates'&&r.candidate||scope==='withdrawing'&&r.withdrawing||scope==='below'&&r.below||scope==='active'&&r.active)),[rows,scope,caseType,matterStatus,selected])
 const selectedRow=selected?rows.find(r=>r.matter_id===selected):null
 const start=days==='all'?null:Date.now()-Number(days)*86400000
 const plotted=filtered.slice(0,12).map(r=>{
  const points=(r.points||[]).filter(p=>Number.isFinite(Date.parse(p.date))).sort((a,b)=>Date.parse(a.date)-Date.parse(b.date))
  const before=start?points.filter(p=>Date.parse(p.date)<start).at(-1):null
  return {...r,points:start?[...(before?[{...before,date:new Date(start).toISOString(),graph_event_description:'Balance carried forward from last recorded entry'}]:[]),...points.filter(p=>Date.parse(p.date)>=start)]:points,notices:markers?(r.notices||[]).filter(n=>!start||Date.parse(n.date)>=start):[]}
 })
 const run=async fn=>{setBusy(true);setError('');try{await fn()}catch(e){setError(e.message||String(e))}finally{setBusy(false)}}
 const changeStatus=row=>row.withdrawing?run(()=>onRelease?.(row.matter_id)):run(()=>onEnter?.(row.matter_id))
 return <section className="mio-wd-trust"><header><div><h2>Trust balances &amp; withdrawal candidates</h2><small>Accounting-ledger history, minimum trust levels, and recorded invoice / notice sends. Black = not withdrawing; red = withdrawing.</small></div><button type="button" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'Hide graph':'Show graph'}</button><button type="button" disabled={busy} onClick={()=>run(onRefresh)}>Refresh financial data</button></header>{error&&<p role="alert">{error}</p>}{open&&<>
 <div className="mio-wd-tools"><label>Graph matters<select value={scope} onChange={e=>setScope(e.target.value)}><option value="active">Active matters</option><option value="candidates">Candidates: below minimum + unpaid 7 days</option><option value="below">Below trust minimum</option><option value="withdrawing">Already withdrawing</option><option value="all">All matters</option></select></label><label>Case type<select value={caseType} onChange={e=>setCaseType(e.target.value)}><option value="">All case types</option>{[...new Set(rows.map(r=>r.case_type).filter(Boolean))].sort().map(v=><option key={v}>{v}</option>)}</select></label><label>Matter status<select value={matterStatus} onChange={e=>setMatterStatus(e.target.value)}><option value="">All statuses</option>{[...new Set(rows.map(r=>r.matter_status).filter(Boolean))].sort().map(v=><option key={v}>{v}</option>)}</select></label><label>Specific matter<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">All matching matters</option>{rows.map(r=><option key={r.matter_id} value={r.matter_id}>{r.client} - {r.name} {r.cause_number}</option>)}</select></label><label>Period<select value={days} onChange={e=>setDays(e.target.value)}><option value="30">30 days</option><option value="90">90 days</option><option value="180">180 days</option><option value="all">All recorded history</option></select></label><label className="mio-wd-check"><input type="checkbox" checked={markers} onChange={e=>setMarkers(e.target.checked)}/>Show sent notices / invoices</label></div>
 {selectedRow&&<div className={'mio-wd-trust-status '+(selectedRow.withdrawing?'withdrawing':'')}><div><strong>{selectedRow.client} — {selectedRow.name}</strong><span>{selectedRow.withdrawing?'Withdrawal status: WITHDRAWING':'Withdrawal status: not withdrawing'}</span></div><button type="button" className={selectedRow.withdrawing?'mio-wd-release':''} disabled={busy||selectedRow.complete&&!selectedRow.withdrawing} onClick={()=>changeStatus(selectedRow)}>{selectedRow.withdrawing?'Release from withdrawal':'Mark as withdrawal'}</button></div>}
 {filtered.length>12&&<p>Showing the first 12 matching lines. Choose a matter or narrow the filters for an uncluttered graph. The table includes every match.</p>}
 {plotted.length?renderGraph(plotted):<p>No matters match these filters.</p>}
 <p className="mio-wd-muted">Candidate means below the recorded minimum with the latest sent invoice still unpaid after 7 days. This is a review prompt, not an automatic withdrawal decision. An invoice send is labeled separately from a withdrawal notice; missing historical sends are not guessed. Select a matter above to mark it as withdrawal or release it from withdrawal status.</p>
 <details><summary>Review {filtered.length} matching matters and withdrawal status</summary><div className="mio-wd-table"><table><thead><tr>{['Matter / client','Trust / minimum','Latest invoice sent','Latest withdrawal email','Withdrawal status'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.matter_id}><td><strong>{r.client}</strong><div>{r.name} {r.cause_number}</div></td><td>{money(r.trust)} / {money(r.minimum)}{r.below&&<small>Below minimum</small>}</td><td>{date(r.last_invoice_sent)}{r.candidate&&<small>Unpaid 7+ days - review candidate</small>}</td><td>{date(r.last_withdrawal_sent)}</td><td>{r.withdrawing?<><strong className="mio-wd-withdrawing-label">WITHDRAWING</strong><button type="button" className="mio-wd-release" disabled={busy} onClick={()=>changeStatus(r)}>Release</button></>:<button type="button" disabled={busy||r.complete} onClick={()=>changeStatus(r)}>{r.complete?'Workflow completed':'Mark as withdrawal'}</button>}</td></tr>)}</tbody></table></div></details>
 </>}</section>
}
