import React,{useEffect,useMemo,useRef,useState,useSyncExternalStore} from 'react'
import {mioCloudStore,mioStorage} from './mioCloudRuntime.js'
import {mioWithdrawalStore as store} from './mioWithdrawalRuntime.js'
import {WithdrawalTemplateSettings} from './MioWithdrawalDashboard.jsx'
import {ageLabel,STATUS_LABELS} from './mioWithdrawalWorkflow.js'
import {withdrawalTimeEntries} from './mioWithdrawalWorkspaceState.js'
import {WORKFLOW_GRAPH_TYPES,actionFor,normalizeWithdrawalView,matchesWithdrawalView,defaultWithdrawalDefinition,validateWorkflowDefinition,configureWorkflow,resolveWorkflowSlot,workflowBlockReason,workflowBlockAttention} from './mioWorkflowBlocks.js'
import {viewKey,definitionKey,stepFinished,clipGraphPoints,graphValue,stepPrimary,effectiveTemplate,downloadWorkflowFlow} from './mioWithdrawalBlockHelpers.js'
import MioWorkflowBuilder from './MioWorkflowBuilder.jsx'
import './MioWithdrawalBlocks.css'
const money=v=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{style:'currency',currency:'USD'}):'Not recorded'
const day=v=>v?new Date(v).toLocaleDateString():'Not recorded'
const copy=x=>JSON.parse(JSON.stringify(x))
function readPreference(key,fallback){const raw=mioStorage.getItem(key);if(raw==null)return fallback;return JSON.parse(raw)}
function Modal({title,children,onClose}){const ref=useRef(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close()},[]);return <dialog ref={ref} className="mio-blocks mio-block-dialog" onCancel={e=>{e.preventDefault();onClose()}}><header><h2>{title}</h2><button type="button" onClick={onClose}>Close</button></header>{children}</dialog>}
function OptionFilter({name,items,value,onChange}){const all=!value.length,selected=all?items.map(o=>o.name):value;return <details className="mio-block-filter"><summary>{name} ({all?'All':items.filter(o=>selected.includes(o.name)).length} of {items.length})</summary><div className="mio-block-filter-box"><button type="button" onClick={()=>onChange([])}>Select all</button> <button type="button" onClick={()=>onChange(['__none__'])}>Clear all</button>{items.map(o=><label key={o.id||o.name} className="mio-block-check"><input type="checkbox" checked={selected.includes(o.name)} onChange={e=>{const values=e.target.checked?[...selected.filter(x=>x!=='__none__'),o.name]:selected.filter(x=>x!==o.name);onChange(values.length?values:['__none__'])}}/>{o.name}</label>)}{!items.length&&<p>Configure these options in Settings.</p>}</div></details>}
function SlotButton({slot,state,onClick}){const current=resolveWorkflowSlot(state,slot.id);return <button type="button" className={'mio-block-slot '+(current?'filled':'')} onClick={onClick}><strong>{slot.name}</strong><span>{current?current.name:'Empty - waiting for document'}</span><span>{current?(current.verified?'Reviewed':'Needs review'):'Not created yet'}{state.document_slots?.[slot.id]?.versions.length>1?' - '+state.document_slots[slot.id].versions.length+' versions':''}</span></button>}
export default function WithdrawalBlocksDashboard({rows=[],snapshot,owner,documents=[],onRefresh,onViewDocument,templates=[],profile={},onSaveDrafting,optionLists={},timeEntries=[],onAddTime,getFinanceRows,renderTrustGraph,onEnter,onRelease,onAction,getPeople,initialExpanded=''}){
 useSyncExternalStore(mioCloudStore.subscribe,mioCloudStore.getVersion,mioCloudStore.getVersion)
 let preferenceError='',view,template
 try{view=normalizeWithdrawalView(readPreference(viewKey,{}));template=readPreference(definitionKey,null)||defaultWithdrawalDefinition();validateWorkflowDefinition(template)}catch(e){preferenceError='Saved withdrawal preferences could not be read. Nothing was overwritten. '+e.message;view=normalizeWithdrawalView();template=defaultWithdrawalDefinition()}
 const[expanded,setExpanded]=useState(initialExpanded),[selectedId,setSelectedId]=useState(''),[settingsOpen,setSettingsOpen]=useState(false),[builder,setBuilder]=useState(false),[editor,setEditor]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[now,setNow]=useState(Date.now())
 const init=useRef(new Set()),initial=useRef(''),selectedKey=useRef('')
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer)},[])
 const finance=getFinanceRows(view.metric),financeById=new Map(finance.map(r=>[String(r.matter_id),r]))
 const matchingFinance=finance.filter(r=>matchesWithdrawalView(r,view)&&(!view.selected||String(r.matter_id)===view.selected))
 const joined=rows.map(row=>{const saved=snapshot.rows[row.matter_id]?.state;return {...financeById.get(String(row.matter_id)),...row,state:saved?.definition?saved:saved?configureWorkflow(saved,template):null}})
 const selected=joined.find(r=>r.matter_id===expanded),attention=selected?.state?workflowBlockAttention(selected.state,now):null
 useEffect(()=>{const key=expanded+':'+(attention?.step_id||'');if(key!==selectedKey.current){selectedKey.current=key;setSelectedId(attention?.step_id||'')}},[expanded,attention?.step_id])
 useEffect(()=>{if(initialExpanded&&initialExpanded!==initial.current){initial.current=initialExpanded;setExpanded(initialExpanded)}},[initialExpanded])
 async function ensure(row){
  if(!owner||!row||snapshot.loading||init.current.has(row.matter_id))return
  init.current.add(row.matter_id)
  try{let entry=store.getSnapshot().rows[row.matter_id]
   if(!entry){entry=await store.initialize(owner,row.matter_id,row.started_at||null);entry=await store.apply(owner,row.matter_id,{type:'step_update',step_id:'decision',status:'complete',confirmed:true,historical_confirmed:true,note:'Existing matter withdrawal status confirmed.',evidence:{reference:'Matter already marked as withdrawing'}})}
   if(entry.state.status==='active'&&!entry.state.definition)await store.apply(owner,row.matter_id,{type:'workflow_configure',definition:template,confirmed:true})
  }finally{init.current.delete(row.matter_id)}
 }
 useEffect(()=>{if(selected?.state?.status==='active'&&!snapshot.rows[expanded]?.state?.definition)void ensure(selected).catch(e=>setError(e.message))},[expanded,snapshot.loading])
 const changeView=patch=>{if(preferenceError){setError(preferenceError);return}try{const latest=normalizeWithdrawalView(readPreference(viewKey,{}));mioCloudStore.stage(viewKey,JSON.stringify({...latest,...patch}));void mioCloudStore.flushAll()}catch(e){setError(e.message)}}
 const run=async fn=>{if(busy)return;setBusy(true);setError('');try{return await fn()}catch(e){setError(e.message||String(e));return null}finally{setBusy(false)}}
 const mutate=(matter,event)=>store.apply(owner,matter,event)
 const close=()=>{if(!busy)setEditor(null)}
 const safeState=row=>{const s=store.getSnapshot().rows[row.matter_id]?.state;if(!s?.definition)throw new Error('The editable workflow is still loading. Try again once saved.');return s}
 async function showRow(row){if(expanded===row.matter_id){setExpanded('');return}setExpanded(row.matter_id);await ensure(row)}
 async function afterComplete(row,step,extra={}){
  const state=safeState(row),result=await mutate(row.matter_id,{type:'step_update',step_id:step.id,status:'complete',confirmed:true,note:extra.historical_confirmed?'Attorney confirmed previously completed work. No external action repeated.':'Attorney reviewed and approved '+step.name+'.',evidence:{reference:'Attorney approval; '+[...step.input_slots,...step.output_slots].map(id=>resolveWorkflowSlot(state,id)?.document_id).filter(Boolean).join(', ')},...extra})
  const next=workflowBlockAttention(result.state,Date.now());setSelectedId(next?.step_id||step.id);setEditor({type:'next',matter:row.matter_id,title:step.name+' - complete',nextId:next?.step_id||''});return result
 }
 async function complete(row,step,historical=false){
  if(historical&&!window.confirm('Mark "'+step.name+'" as already completed outside Mio? This records your confirmation; it will not send, file, sign, or invent missing documents.'))return
  const state=safeState(row),missing=step.output_slots.filter(id=>!resolveWorkflowSlot(state,id)?.verified)
  if(missing.length&&(!historical||missing.includes(state.definition.completion_slot))){setEditor({type:'outputs',title:'Complete '+step.name,matter:row.matter_id,stepId:step.id,historical,outputs:{}});return}
  return afterComplete(row,step,{historical_confirmed:historical})
 }
 async function action(row,step){
  const state=safeState(row);if(state.paused||state.status!=='active')throw new Error('Resume an active workflow before continuing.')
  if(state.steps[step.id].status==='not_started')throw new Error('Complete the prerequisites or start this manual step first.')
  const reason=workflowBlockReason(state,step);if(reason)throw new Error(reason)
  await onAction(row.matter_id,step,state)
 }
 const slotEditor=(row,slot)=>setEditor({type:'slot',title:slot.name,matter:row.matter_id,slotId:slot.id,documentId:'',stepId:selectedId})
 const rowEditable=row=>row.state?.status==='active'&&!row.state.paused&&!busy
 const counts={needs:0,waiting:0,paused:0,complete:0,active:0}
 for(const r of joined){const a=workflowBlockAttention(r.state,now);if(a?.kind==='complete')counts.complete++;else if(a?.kind==='paused'){counts.paused++;counts.active++}else if(a?.kind!=='released'){counts.active++;counts[a?.needsMe?'needs':'waiting']++}}
 const visible=joined.filter(r=>{const a=workflowBlockAttention(r.state,now);return matchesWithdrawalView(r,view)&&(!view.selected||r.matter_id===view.selected)&&(!view.query||[r.name,r.client,r.cause_number].join(' ').toLowerCase().includes(view.query.toLowerCase()))&&(view.show==='all'||view.show==='active'&&!['complete','released'].includes(a?.kind)||view.show==='needs'&&a?.needsMe||view.show==='waiting'&&a?.kind==='waiting'||view.show==='paused'&&a?.kind==='paused'||view.show==='complete'&&a?.kind==='complete')}).sort((a,b)=>{
  const aa=workflowBlockAttention(a.state,now),bb=workflowBlockAttention(b.state,now),time=x=>x?Date.parse(x):Infinity
  if(view.sort==='attention')return Number(!aa?.needsMe)-Number(!bb?.needsMe)||time(aa?.since)-time(bb?.since)||a.client.localeCompare(b.client)
  const diff=time(a.state?.started_at)-time(b.state?.started_at);return view.sort==='newest'?-diff:diff
 })
 const current=selected?.state?.definition.steps.find(s=>s.id===selectedId)||selected?.state?.definition.steps[0],currentState=current&&selected.state.steps[current.id],primary=current&&stepPrimary(selected.state,current),currentReason=current&&workflowBlockReason(selected.state,current)
 const editorRow=editor&&joined.find(r=>r.matter_id===editor.matter),editorState=editorRow?.state,editorStep=editorState?.definition.steps.find(s=>s.id===editor?.stepId),editorDocs=editorRow?documents.filter(d=>String(d.matter_id)===editorRow.matter_id):[]
 const cloud=mioCloudStore.status(),settingsVersion=mioStorage.getItem(definitionKey)||'default'
 return <main className="mio-blocks"><header><div><h1>Withdrawal dashboard</h1><p className="mio-block-note">One process per matter. Reusable actions, shared document versions, and a clear next approval.</p></div><div className="mio-block-tools"><button type="button" disabled={busy} onClick={()=>run(async()=>{await store.load(owner);await onRefresh()})}>Refresh linked activity</button><button type="button" aria-expanded={settingsOpen} onClick={()=>setSettingsOpen(!settingsOpen)}>Settings</button></div></header>
 {(preferenceError||error||snapshot.error||cloud.error)&&<p className="mio-block-error" role="alert">{preferenceError||error||snapshot.error||cloud.error}</p>}{message&&<p className="mio-block-success" role="status">{message}</p>}
 <section className="mio-block-panel"><header><h2>Trust balances and withdrawal selection</h2><button type="button" onClick={()=>changeView({open:!view.open})}>{view.open?'Hide graph':'Show graph'}</button></header>
 <div className="mio-block-filters">{[['matter_status','Matter status'],['case_status','Case status'],['case_type','Case type']].map(([k,label])=><OptionFilter key={k} name={label} items={optionLists[k]||[]} value={view[k]} onChange={value=>changeView({[k]:value})}/>)}<label>Graph type<select value={view.metric} onChange={e=>changeView({metric:e.target.value})}>{WORKFLOW_GRAPH_TYPES.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Specific matter<select value={view.selected} onChange={e=>changeView({selected:e.target.value})}><option value="">All matching matters</option>{finance.map(r=><option key={r.matter_id} value={r.matter_id}>{r.client} - {r.name} {r.cause_number}</option>)}</select></label><label>Period<select value={view.days} onChange={e=>changeView({days:e.target.value})}>{['30','90','180','all'].map(d=><option key={d} value={d}>{d==='all'?'All recorded history':d+' days'}</option>)}</select></label><label className="mio-block-check"><input type="checkbox" checked={view.markers} onChange={e=>changeView({markers:e.target.checked})}/>Show sent notices / invoices</label></div>
 <p className="mio-block-saving" role="status">{cloud.pending?'Saving view to Supabase...':'View saved to Supabase. Hard refresh does not reset these selections.'}</p>
 {view.selected&&financeById.get(view.selected)&&(()=>{const r=financeById.get(view.selected);return <div className={'mio-block-status '+(r.withdrawing?'withdrawing':'')}><strong>{r.client} - {r.name}</strong> - {r.withdrawing?'WITHDRAWING':'Not withdrawing'} <button type="button" disabled={busy||r.complete&&!r.withdrawing} onClick={()=>run(()=>r.withdrawing?onRelease(r.matter_id):onEnter(r.matter_id))}>{r.withdrawing?'Release from withdrawal':'Mark as withdrawal'}</button></div>})()}
 {view.open&&<><p className="mio-block-graph-note">Black = not withdrawing. Red = withdrawing. {matchingFinance.length>12?'First 12 matching lines shown; narrow the filters or select a matter. ':''}{view.metric==='matter_trust_funds'?'Trust uses the accounting ledger.':'Adjusted values use recorded financial snapshots; today\'s WIP and outstanding balances are not applied retroactively to old ledger entries.'}</p>{matchingFinance.length?renderTrustGraph(matchingFinance.slice(0,12).map(r=>({...r,points:clipGraphPoints(r.points,view.days,now),notices:view.markers?(r.notices||[]).filter(n=>view.days==='all'||Date.parse(n.date)>=now-Number(view.days)*86400000):[]})),view.metric):<p>No matters match the selected Settings options.</p>}</>}
 <details><summary>Review {matchingFinance.length} matching matters / change withdrawal status</summary><div className="mio-block-table-wrap"><table><thead><tr><th>Matter</th><th>{WORKFLOW_GRAPH_TYPES.find(([id])=>id===view.metric)?.[1]}</th><th>Last invoice sent</th><th>Withdrawal</th></tr></thead><tbody>{matchingFinance.map(r=><tr key={r.matter_id}><td>{r.client} - {r.name}</td><td>{money(graphValue(r,view.metric))}</td><td>{day(r.last_invoice_sent)}</td><td><button type="button" disabled={busy||r.complete&&!r.withdrawing} onClick={()=>run(()=>r.withdrawing?onRelease(r.matter_id):onEnter(r.matter_id))}>{r.withdrawing?'Release from withdrawal':'Mark as withdrawal'}</button></td></tr>)}</tbody></table></div></details></section>
 {settingsOpen&&<section className="mio-block-panel mio-block-workflow-settings"><header><h2>Withdrawal settings</h2><button type="button" onClick={()=>setSettingsOpen(false)}>Close settings</button></header><div className="mio-block-tools"><button type="button" onClick={()=>downloadWorkflowFlow(template)}>Download flow sheet</button><button type="button" disabled={!!preferenceError} onClick={()=>setBuilder(!builder)}>{builder?'Hide workflow editor':'Edit rows, steps and document slots'}</button></div><p className="mio-block-note">The flow sheet follows your saved workflow definition. Existing matters retain their own version until you apply a replacement. Drafting styles and caption libraries remain on the Drafting page.</p><WithdrawalTemplateSettings profile={profile} templates={templates} onSave={onSaveDrafting}/>{builder&&<div className="mio-block-full-builder"><MioWorkflowBuilder key={settingsVersion} definition={template} templates={templates} statusOptions={optionLists} onClose={()=>setBuilder(false)} onSave={async value=>{validateWorkflowDefinition(value);await mioCloudStore.saveNow(definitionKey,JSON.stringify(value),{throwOnError:true});setMessage('Workflow template saved to Supabase. New processes will use it; existing processes are unchanged.')}}/></div>}</section>}
 <div className="mio-block-counts">{[['needs','Needs me'],['waiting','Waiting on others'],['active','Active withdrawals'],['complete','Completed']].map(([k,label])=><div key={k}><strong>{counts[k]}</strong>{label}</div>)}</div>
 <div className="mio-block-tools"><label>Workflow view<select value={view.show} onChange={e=>changeView({show:e.target.value})}>{[['active','Active withdrawals'],['needs','Needs my action'],['waiting','Waiting on others'],['paused','Paused'],['complete','Completed'],['all','All workflows']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Sort<select value={view.sort} onChange={e=>changeView({sort:e.target.value})}><option value="attention">Needs me first - longest pending</option><option value="oldest">Withdrawal entry - oldest first</option><option value="newest">Withdrawal entry - newest first</option></select></label><label>Find matter<input value={view.query} placeholder="Matter, client or cause number" onChange={e=>changeView({query:e.target.value})}/></label></div>
 <div className="mio-block-table-wrap"><table><thead><tr><th>Matter / client</th><th>Status</th><th>Next action / what is needed</th><th>Pending</th><th>In withdrawal</th><th>Open</th></tr></thead><tbody>{visible.map(row=>{const a=workflowBlockAttention(row.state,now),progress=row.state?.definition.steps.filter(s=>stepFinished(row.state.steps[s.id])).length||0;return <React.Fragment key={row.matter_id}><tr className={'mio-block-summary '+(a?.needsMe?'needs':'')} onClick={()=>run(()=>showRow(row))}><td><strong>{row.client}</strong><small>{row.name} {row.cause_number}</small></td><td><span className={'mio-block-badge '+(a?.needsMe?'needs':'')}>{a?.needsMe?'NEEDS ME':a?.kind==='waiting'?'\u231b WAITING':(a?.kind||'LOADING').toUpperCase()}</span><small>{progress}/{row.state?.definition.steps.length||template.steps.length} steps</small></td><td>{a?.next||'Open to initialize the process'}</td><td>{ageLabel(a?.since,now)}</td><td>{ageLabel(row.state?.started_at,now)}</td><td><button type="button" aria-expanded={expanded===row.matter_id} onClick={e=>{e.stopPropagation();run(()=>showRow(row))}}>{expanded===row.matter_id?'Collapse':'Review'}</button></td></tr>
 {expanded===row.matter_id&&row.state&&<tr className="mio-block-expanded"><td colSpan={6}><header><h2>{row.client} - {row.name}</h2><span>{row.state.status==='complete'?'Process complete':row.state.paused?'Paused':'Active process'}</span></header>
 <div className="mio-block-lanes">{row.state.definition.rows.map(lane=><div className="mio-block-lane" key={lane.id}><strong>{lane.name}</strong><div className="mio-block-lane-steps">{row.state.definition.steps.filter(s=>s.row_id===lane.id).map(s=>{const t=row.state.steps[s.id];return <button type="button" key={s.id} className={'mio-block-step '+t.status+(a?.step_id===s.id?' next':'')} aria-pressed={current?.id===s.id} onClick={()=>setSelectedId(s.id)}><strong>{t.status==='complete'?'\u2713 ':t.status==='waiting'?'\u231b ':a?.step_id===s.id?'\u2192 ':''}{row.state.definition.steps.indexOf(s)+1}. {s.name}</strong><small>{STATUS_LABELS[t.status]||t.status}</small></button>})}</div></div>)}</div>
 <div className="mio-block-overview"><section className="mio-block-box"><h3>Process actions</h3><p className="mio-block-note">Entered withdrawal: {day(row.state.started_at)}</p><div><button type="button" disabled={busy||row.state.status!=='active'} onClick={()=>run(()=>mutate(row.matter_id,{type:'workspace_pause',paused:!row.state.paused}))}>{row.state.paused?'Resume':'Pause'}</button><button type="button" disabled={!rowEditable(row)} onClick={()=>run(async()=>{const final=row.state.definition.steps.find(s=>s.action==='finish');if(!final)throw new Error('Add a Complete workflow action to this process first.');setSelectedId(final.id);await complete(row,final)})}>Mark complete</button><button type="button" disabled={busy||row.state.status!=='active'} onClick={()=>setEditor({type:'builder',title:'Edit this matter workflow',matter:row.matter_id})}>Edit this process</button><button type="button" disabled={!rowEditable(row)} onClick={()=>run(async()=>{if(window.confirm('Apply the saved template to this matter? Existing step history and document versions are retained. New prerequisites and new steps take effect immediately.'))await mutate(row.matter_id,{type:'workflow_configure',definition:template,confirmed:true})})}>Apply saved template</button><button type="button" onClick={()=>downloadWorkflowFlow(row.state.definition)}>Flow sheet</button><button type="button" disabled={busy} onClick={()=>run(async()=>setEditor({type:'history',title:'Process audit history',matter:row.matter_id,events:await store.history(owner,row.matter_id)}))}>Audit history</button><button type="button" disabled={busy||row.state.status!=='active'} onClick={()=>run(()=>onRelease(row.matter_id))}>Release from withdrawal</button></div></section>
 <section className="mio-block-box mio-block-selected"><h3>Selected step: {current?.name||'Choose a step'}</h3>{current&&<><p className="mio-block-note">Action: {actionFor(current.action).label} | {STATUS_LABELS[currentState.status]}</p>{a?.step_id===current.id&&<p className="mio-block-next">Next: {primary.label}</p>}{currentReason&&<p className="mio-block-error">{currentReason}. Select the document slot below to provide it.</p>}{currentState.status==='not_started'&&<p className="mio-block-note">{current.manual_start?'This step starts manually.':'Waiting for: '+current.depends_on.filter(id=>!stepFinished(row.state.steps[id])).map(id=>row.state.definition.steps.find(s=>s.id===id)?.name||id).join('; ')}</p>}{currentState.waiting_on&&<p>{'\u231b'} Waiting on {currentState.waiting_on}. Follow up: {day(currentState.due_at)}</p>}
 {current.action==='draft_document'&&<label>Connected drafting template<select value={effectiveTemplate(row.state,current,profile)} disabled={!rowEditable(row)||stepFinished(currentState)} onChange={e=>run(()=>mutate(row.matter_id,{type:'step_config',step_id:current.id,template_id:e.target.value}))}><option value="">Use configured / built-in template</option>{templates.filter(t=>t.is_active!==false&&t.status!=='retired').map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}
 {['draft_email','esign_document'].includes(current.action)&&<><button type="button" disabled={!rowEditable(row)} onClick={()=>setEditor({type:'recipients',title:'Recipients and message',matter:row.matter_id,stepId:current.id,recipient_ids:currentState.recipient_ids||[],signature_url:currentState.signature_url||'',email_subject:currentState.email_subject||'',email_body:currentState.email_body||'',client_links:currentState.client_links||{},links_verified:!!currentState.links_verified})}>Choose people / message ({currentState.recipient_ids?.length||0})</button><button type="button" disabled={!rowEditable(row)} onClick={()=>run(()=>onAction(row.matter_id,{...current,openExisting:true},safeState(row)))}>Open linked email</button>{current.action==='esign_document'&&<p className="mio-block-note">Prepare an invitation using a real signature-provider link. The returned signed document goes in the output slot; email sending alone is not a signature.</p>}</>}
 {(current.input_slots.length>0||current.output_slots.length>0)&&<p className="mio-block-note">Input: {current.input_slots.map(id=>row.state.definition.slots.find(s=>s.id===id)?.name).join('; ')||'None'}<br/>Output: {current.output_slots.map(id=>row.state.definition.slots.find(s=>s.id===id)?.name).join('; ')||'No document output'}</p>}
 <div className="mio-block-actions"><h3>Step actions</h3><button type="button" disabled={busy} onClick={()=>onAddTime(row.matter_id,current)}>{'\u23f1'} Add time</button><button type="button" disabled={busy||row.state.status!=='active'} onClick={()=>setEditor({type:'note',title:'Add note - '+current.name,matter:row.matter_id,stepId:current.id,note:''})}>Add note</button>
 {!stepFinished(currentState)&&<><button type="button" className="mio-block-primary" disabled={!rowEditable(row)||!!currentReason||currentState.status==='not_started'&&!current.manual_start} onClick={()=>run(async()=>{if(currentState.status==='not_started')await mutate(row.matter_id,{type:'step_update',step_id:current.id,status:'needs_action',note:'Attorney started manual step.'});if(primary.mode==='documents'){setEditor({type:'outputs',title:'Connect the returned document',matter:row.matter_id,stepId:current.id,outputs:{}});return}return primary.mode==='complete'?complete(row,current):action(row,current)})}>{primary.label}</button>{primary.mode!=='complete'&&current.action!=='matter_status'&&<button type="button" disabled={!rowEditable(row)} onClick={()=>run(()=>complete(row,current))}>Complete step</button>}<button type="button" disabled={!rowEditable(row)||current.action==='matter_status'} onClick={()=>run(()=>complete(row,current,true))}>Already completed</button></>}
 {stepFinished(currentState)&&<button type="button" disabled={!rowEditable(row)} onClick={()=>run(async()=>{if(window.confirm('Reopen this step? Later steps and previously sent items are not repeated automatically.'))await mutate(row.matter_id,{type:'step_update',step_id:current.id,status:'needs_action',note:'Attorney reopened the step.'})})}>Reopen step</button>}
 <button type="button" disabled={!rowEditable(row)} onClick={()=>setEditor({type:'waiting',title:'Waiting / skip step',matter:row.matter_id,stepId:current.id,status:'waiting',waiting_on:currentState.waiting_on||'',due_at:new Date(Date.now()+7*86400000).toISOString().slice(0,10),note:''})}>{'\u231b'} Waiting / skip</button></div>
 {(currentState.note||(row.state.workspace_notes||[]).some(n=>n.step_id===current.id))&&<details><summary>Step notes and activity</summary><p>{currentState.note}</p>{(row.state.workspace_notes||[]).filter(n=>n.step_id===current.id).map((n,i)=><p key={i}>{day(n.created_at)} - {n.note}</p>)}</details>}</>}</section>
 <section className="mio-block-box mio-block-billing-box"><h3>Billing entries - this withdrawal</h3><div className="mio-block-billing"><table><thead><tr><th>Date / work</th><th>Hours</th><th>Amount</th></tr></thead><tbody>{withdrawalTimeEntries(timeEntries,row.matter_id).map(e=><tr key={e.id}><td>{day(e.date)}<br/>{e.description||e.matter_step}</td><td>{e.billing_time}</td><td>{money(e.amount)}</td></tr>)}</tbody></table>{!withdrawalTimeEntries(timeEntries,row.matter_id).length&&<p className="mio-block-note">No withdrawal time recorded. Use the clock button on a step.</p>}</div></section></div>
 <section className="mio-block-box" style={{marginTop:9}}><header><h3>Process documents - shared input and output slots</h3><span className="mio-block-note">Empty slots fill as work is saved and reviewed. Existing versions are retained.</span></header><div className="mio-block-slots">{row.state.definition.slots.map(slot=><SlotButton key={slot.id} slot={slot} state={row.state} onClick={()=>slotEditor(row,slot)}/>)}</div></section></td></tr>}</React.Fragment>})}</tbody></table>{!visible.length&&<p>No withdrawal workflows match these filters.</p>}</div>
 {editor&&<Modal title={editor.title} onClose={close}>{editor.type==='builder'&&editorState&&<MioWorkflowBuilder definition={editorState.definition} templates={templates} statusOptions={optionLists} title="Rows, steps and actions for this matter" onClose={close} onSave={async def=>{await mutate(editor.matter,{type:'workflow_configure',definition:def,confirmed:true});setMessage('This process was updated. Its document versions and prior history were retained.');setEditor(null)}}/>}
 {editor.type==='slot'&&editorState&&(()=>{const slot=editorState.definition.slots.find(s=>s.id===editor.slotId),container=editorState.document_slots[editor.slotId],doc=editorDocs.find(d=>String(d.id)===editor.documentId);return <><p>{slot.kind==='filed'?'Choose the actual file-stamped document, not the unfiled draft.':slot.kind==='signed'?'Choose the actual signed version and verify whose signatures it contains.':'Choose a saved document from this matter.'}</p><label>Saved matter document<select value={editor.documentId} onChange={e=>setEditor({...editor,documentId:e.target.value})}><option value="">Select a document</option>{editorDocs.map(d=><option key={d.id} value={d.id}>{d.file_name||d.name}</option>)}</select></label>{doc&&<button type="button" onClick={()=>onViewDocument(doc)}>Open document to review</button>}<footer className="mio-block-tools"><button type="button" className="mio-block-primary" disabled={!doc||busy||editorState.status!=='active'||editorState.paused} onClick={()=>run(async()=>{await mutate(editor.matter,{type:'slot_attach',slot_id:slot.id,document_id:doc.id,matter_id:editor.matter,name:doc.file_name||doc.name,step_id:editor.stepId,verified:true,confirmed:true,source:'Attorney selected and reviewed this document for '+slot.name});setEditor(null)})}>Attach reviewed document to this slot</button></footer><h3>Document versions</h3>{!(container?.versions||[]).length&&<p>This slot is empty.</p>}{(container?.versions||[]).map(v=><div className="mio-block-status" key={v.id}><strong>{v.name}</strong> - {v.verified?'Reviewed':'Needs review'} - {day(v.recorded_at)} {v.id===container.current_version&&<b>(current)</b>} <button type="button" onClick={()=>{const saved=editorDocs.find(d=>String(d.id)===v.document_id);if(saved)onViewDocument(saved);else setError('The original document is no longer in this matter Documents.')}}>Open</button>{!v.verified&&v.id===container.current_version&&<button type="button" disabled={busy||editorState.status!=='active'} onClick={()=>run(async()=>{await mutate(editor.matter,{type:'slot_verify',slot_id:slot.id,confirmed:true});setEditor(null)})}>I reviewed this version</button>}</div>)}</>})()}
 {editor.type==='outputs'&&editorStep&&<><p>Connect the actual output document(s), then approve this step. Missing files are never invented from a status label.</p>{editorStep.output_slots.map(slotId=>{const slot=editorState.definition.slots.find(s=>s.id===slotId),existing=resolveWorkflowSlot(editorState,slotId),id=editor.outputs[slotId]||'';return <div key={slotId}><label>{slot.name}<select value={id} onChange={e=>setEditor({...editor,outputs:{...editor.outputs,[slotId]:e.target.value}})}><option value="">{existing?.verified?'Keep reviewed: '+existing.name:'Select the completed document'}</option>{editorDocs.map(d=><option key={d.id} value={d.id}>{d.file_name||d.name}</option>)}</select></label>{id&&<button type="button" onClick={()=>onViewDocument(editorDocs.find(d=>String(d.id)===id))}>Review selected file</button>}</div>})}<p className="mio-block-note">Approving confirms that these are the correct completed / signed / filed versions for their named slots.</p><footer><button type="button" className="mio-block-primary" disabled={busy} onClick={()=>run(async()=>{const outputs={};for(const[slotId,id]of Object.entries(editor.outputs)){const d=editorDocs.find(x=>String(x.id)===id);if(d)outputs[slotId]={document_id:id,name:d.file_name||d.name}}await afterComplete(editorRow,editorStep,{outputs,historical_confirmed:!!editor.historical})})}>Approve documents & complete step</button></footer></>}
 {editor.type==='next'&&editorState&&(()=>{const next=editorState.definition.steps.find(s=>s.id===editor.nextId);return <><p className="mio-block-success">Completion saved to Supabase.</p>{next?<><h3>Next: {next.name}</h3><p>{workflowBlockReason(editorState,next)||'Mio has activated this step. Review or prepare its task next.'}</p><div className="mio-block-slots">{next.input_slots.map(id=>{const slot=editorState.definition.slots.find(s=>s.id===id);return <SlotButton key={id} slot={slot} state={editorState} onClick={()=>slotEditor(editorRow,slot)}/>})}</div><footer className="mio-block-tools"><button type="button" className="mio-block-primary" onClick={()=>{setSelectedId(next.id);setEditor(null)}}>Go to next step</button>{!workflowBlockReason(editorState,next)&&!['finish','manual','approve','review_document'].includes(next.action)&&<button type="button" disabled={busy} onClick={()=>run(async()=>{await action(editorRow,next);setEditor(null)})}>{actionFor(next.action).button}</button>}</footer></>:<p>{editorState.status==='complete'?'The withdrawal process is complete.':'No new step is ready. Review the remaining waiting or manually started steps.'}</p>}</>})()}
 {editor.type==='note'&&<><label>Step note<textarea rows={5} value={editor.note} onChange={e=>setEditor({...editor,note:e.target.value})}/></label><button type="button" className="mio-block-primary" disabled={busy||!editor.note.trim()} onClick={()=>run(async()=>{await mutate(editor.matter,{type:'step_note',step_id:editor.stepId,note:editor.note});setEditor(null)})}>Save note</button></>}
 {editor.type==='waiting'&&<><label>Status<select value={editor.status} onChange={e=>setEditor({...editor,status:e.target.value})}><option value="waiting">Waiting on someone / something</option><option value="needs_action">Needs my action</option><option value="cancelled">Skip / not applicable</option></select></label>{editor.status==='waiting'&&<><label>Waiting on<input value={editor.waiting_on} onChange={e=>setEditor({...editor,waiting_on:e.target.value})}/></label><label>Follow up date<input type="date" value={editor.due_at} onChange={e=>setEditor({...editor,due_at:e.target.value})}/></label></>}<label>Note / reason<textarea value={editor.note} onChange={e=>setEditor({...editor,note:e.target.value})}/></label><p className="mio-block-note">Skipping a step does not cancel an actual court setting or external request.</p><button type="button" disabled={busy||!editor.note.trim()} onClick={()=>run(async()=>{await mutate(editor.matter,{type:'step_update',step_id:editor.stepId,status:editor.status,waiting_on:editor.waiting_on,due_at:editor.status==='waiting'?new Date(editor.due_at+'T12:00:00').toISOString():null,note:editor.note,confirmed:true});setEditor(null)})}>Save step status</button></>}
 {editor.type==='recipients'&&editorStep&&<><p>Select the actual people associated with this matter. Each selected recipient gets a separate proposed email for review; nothing is sent here.</p><fieldset><legend>Matter people</legend>{getPeople(editor.matter).map(p=><label className="mio-block-check" key={p.key}><input type="checkbox" checked={editor.recipient_ids.includes(p.key)} onChange={e=>setEditor({...editor,recipient_ids:e.target.checked?[...editor.recipient_ids,p.key]:editor.recipient_ids.filter(id=>id!==p.key)})}/>{p.label} - {p.email}</label>)}</fieldset>{!getPeople(editor.matter).length&&<p>Add the client's or counsel's email in Matter People first.</p>}{editorStep.action==='esign_document'&&<label>Signing-provider request link<input type="url" value={editor.signature_url} placeholder="https://... (an actual signing invitation link)" onChange={e=>setEditor({...editor,signature_url:e.target.value})}/></label>}{editorStep.id==='closeout_email'&&<fieldset><legend>Client-accessible resource links</legend>{[['invoices','Invoices'],['efilings','E-filings'],['documents','Case documents']].map(([key,label])=><label key={key}>{label}<input type="url" value={editor.client_links[key]||''} onChange={e=>setEditor({...editor,links_verified:false,client_links:{...editor.client_links,[key]:e.target.value}})}/></label>)}<label className="mio-block-check"><input type="checkbox" checked={editor.links_verified} onChange={e=>setEditor({...editor,links_verified:e.target.checked})}/>I checked that these links are accessible to the client and expose only this matter.</label></fieldset>}<label>Proposed subject (optional)<input value={editor.email_subject} onChange={e=>setEditor({...editor,email_subject:e.target.value})}/></label><label>Proposed message (optional - Mio prepares text when blank)<textarea rows={5} value={editor.email_body} onChange={e=>setEditor({...editor,email_body:e.target.value})}/></label><button type="button" className="mio-block-primary" disabled={busy} onClick={()=>run(async()=>{await mutate(editor.matter,{type:'step_config',step_id:editor.stepId,recipient_ids:editor.recipient_ids,signature_url:editor.signature_url,email_subject:editor.email_subject,email_body:editor.email_body,client_links:editor.client_links,links_verified:editor.links_verified});setEditor(null)})}>Save recipients and message</button></>}
 {editor.type==='history'&&<ol>{editor.events.map(e=><li key={e.event_id}><strong>{new Date(e.recorded_at).toLocaleString()} - {e.event.type}</strong><p>{e.event.note||e.event.reason||e.event.step_id||''}</p></li>)}</ol>}{error&&<p className="mio-block-error" role="alert">{error}</p>}</Modal>}
 </main>
}
