import React,{useEffect,useRef,useState,useSyncExternalStore} from 'react'
import {mioWithdrawalStore as store} from './mioWithdrawalRuntime.js'
import {WITHDRAWAL_STEPS,STATUS_LABELS,workflowAttention,sortWithdrawalRows,ageLabel} from './mioWithdrawalWorkflow.js'
import './mioWithdrawalDashboard.css'
const EMPTY={rows:{},loading:false,error:''}
export function useMioWithdrawals(owner,active){
 const snapshot=useSyncExternalStore(store.subscribe,store.getSnapshot,()=>EMPTY)
 useEffect(()=>{store.account(owner||'');if(owner)void store.load(owner).catch(()=>{})},[owner])
 useEffect(()=>{if(!owner||!active)return;const refresh=()=>{if(document.visibilityState==='visible')void store.load(owner).catch(()=>{})};refresh();const timer=setInterval(refresh,60000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh)}},[owner,active])
 return{...snapshot,rows:Object.fromEntries(Object.entries(snapshot.rows).filter(([,row])=>row.owner_id===owner))}
}
const when=v=>v?new Date(v).toLocaleString():'Not recorded'
const dateInput=v=>v?new Date(new Date(v).getTime()-new Date(v).getTimezoneOffset()*60000).toISOString().slice(0,16):''
function Dialog({title,close,children}){const ref=useRef(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close()},[]);return <dialog ref={ref} className="mio-wd-dialog" onCancel={close}><header><h2>{title}</h2><button type="button" onClick={close}>Close</button></header>{children}</dialog>}
export function WithdrawalTemplateSettings({profile,templates,onSave}){
 const[value,setValue]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const map=value||profile.withdrawal_templates||{}
 return <section className="mio-wd-settings"><h3>Withdrawal drafting connections</h3><p>A client letter is not a Notice of Hearing. Assign the reviewed hearing-notice template before using that step.</p>{[['motion','Motion / proposed order packet'],['notice','Hearing notice']].map(([key,label])=><label key={key}>{label}<select value={map[key]||''} onChange={e=>setValue({...map,[key]:e.target.value})}><option value="">{key==='motion'?'Built-in withdrawal packet':'Select a reviewed hearing-notice template'}</option>{templates.filter(t=>t.is_active!==false&&t.status!=='retired').map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>)}<button type="button" disabled={!value||busy} onClick={async()=>{setBusy(true);try{await onSave({withdrawal_templates:value});setValue(null);setMessage('Saved to Supabase')}catch(e){setMessage('Not saved: '+(e.message||e))}finally{setBusy(false)}}}>Save template connections</button><p role="status">{message}</p></section>
}
export function WithdrawalDashboard({rows,snapshot,owner,documents,onOpen,onStatus,onRefresh,onViewDocument,settings,legacy}){
 const[sort,setSort]=useState('attention'),[filter,setFilter]=useState('active'),[query,setQuery]=useState(''),[expanded,setExpanded]=useState(''),[editor,setEditor]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[settingsOpen,setSettingsOpen]=useState(false),[now,setNow]=useState(Date.now())
 const bottom=useRef(null)
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer)},[])
 const joined=rows.map(r=>({...r,state:snapshot.rows[r.matter_id]?.state})),selected=joined.find(r=>r.matter_id===expanded)
 const counts={active:0,needs:0,waiting:0,complete:0}
 joined.forEach(r=>{const a=workflowAttention(r.state,now);if(a.kind==='complete')counts.complete++;else{counts.active++;counts[a.needsMe?'needs':'waiting']++}})
 const visible=sortWithdrawalRows(joined.filter(r=>{const a=workflowAttention(r.state,now);return(filter==='all'||filter==='active'&&a.kind!=='complete'||filter==='needs'&&a.needsMe||filter==='waiting'&&a.kind==='waiting'||filter==='complete'&&a.kind==='complete')&&[r.name,r.client,r.cause_number].join(' ').toLowerCase().includes(query.toLowerCase())}),sort,now)
 const run=async fn=>{setBusy(true);setError('');setNotice('');try{await fn();setNotice('Saved / synchronized');return true}catch(e){setError(e.message||String(e));return false}finally{setBusy(false)}}
 const close=()=>{if(!busy){setEditor(null);setError('')}}
 const edit=(row,d)=>{const step=row.state.steps[d.id];setError('');setEditor({type:'step',matter:row.matter_id,title:d.name,id:d.id,task:step,status:step.status==='not_started'?'needs_action':step.status,note:'',reference:step.evidence?.reference||'',document_id:step.evidence?.document_id||'',waiting_on:step.waiting_on||'',due_at:dateInput(step.due_at),confirmed:false,historical_confirmed:false,delivery_confirmed:false})}
 const change=patch=>setEditor(current=>({...current,...patch}))
 async function save(){
  if((editor.due_at&&!Number.isFinite(Date.parse(editor.due_at)))||(editor.type==='date'&&!Number.isFinite(Date.parse(editor.date)))){setError('Enter a valid date and time.');return}
  let e
  if(editor.type==='step')e={type:'step_update',step_id:editor.id,status:editor.status,note:editor.note,waiting_on:editor.waiting_on,due_at:editor.due_at?new Date(editor.due_at).toISOString():null,evidence:{reference:editor.reference,...(editor.document_id?{document_id:editor.document_id}:{})},confirmed:editor.confirmed,historical_confirmed:editor.historical_confirmed,delivery_confirmed:editor.delivery_confirmed}
  if(editor.type==='date')e={type:'start_date',started_at:new Date(editor.date).toISOString(),reason:editor.reason}
  if(editor.type==='routes')e={type:'routes',agreed:editor.agreed,hearing:editor.hearing,reason:editor.reason}
  if(editor.type==='closeout')e={type:'closeout_details',links:editor.links,links_verified:editor.links_verified,subject:editor.subject,body:editor.body.replace(/\{\{(invoices|efilings|documents)\}\}/g,(_,k)=>editor.links[k]||'')}
  if(await run(()=>store.apply(owner,editor.matter,e)))setEditor(null)
 }
 const prepareCloseout=row=>{const c=row.state.closeout;setError('');setEditor({type:'closeout',title:'Prepare client closeout email',matter:row.matter_id,links:c.links||{},links_verified:!!c.links_verified,subject:c.subject||`Signed withdrawal order - ${row.cause_number||row.name}`,body:c.body||`Dear ${row.client||'Client'},\n\nPlease see the signed order granting withdrawal.\n\nInvoices: {{invoices}}\nE-filings: {{efilings}}\nCase documents, exhibits, photos, and client-provided files: {{documents}}\n\nPlease retain these records.`})}
 return <main className="mio-wd"><header><div><h1>Withdrawal dashboard</h1><p>What needs your attention - and how long it has been waiting.</p></div><button type="button" disabled={busy||!owner} onClick={()=>run(async()=>{await store.load(owner);await onRefresh()})}>Refresh linked activity</button><button type="button" aria-expanded={settingsOpen} onClick={()=>{setSettingsOpen(!settingsOpen);if(!settingsOpen)setTimeout(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),0)}}>Settings</button></header>
 <div className="mio-wd-counts">{[['needs','Needs me'],['waiting','Waiting on others'],['active','Active withdrawals'],['complete','Completed']].map(([key,label])=><button type="button" key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}><strong>{counts[key]}</strong><span>{label}</span></button>)}</div>
 <div className="mio-wd-tools"><label>Show<select value={filter} onChange={e=>setFilter(e.target.value)}>{[['active','All active'],['needs','Needs me'],['waiting','Waiting on others'],['complete','Completed'],['all','All including completed']].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="attention">Needs me first - longest pending action</option><option value="oldest">Withdrawal age - oldest first</option><option value="newest">Withdrawal age - newest first</option></select></label><label>Find matter<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Matter, client or cause number" /></label></div>
 {snapshot.loading&&<p role="status">Refreshing saved workflows...</p>}{!editor&&(error||snapshot.error)&&<p role="alert">{error||snapshot.error}</p>}{!editor&&notice&&<p role="status">{notice}</p>}
 <div className="mio-wd-table"><table><thead><tr>{['Matter / client','Attention / waiting on','Next action','Action pending','In withdrawal','Open'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{visible.map(r=>{const a=workflowAttention(r.state,now);return <tr key={r.matter_id} className={a.needsMe?'needs-me':''}><td><strong>{r.name}</strong><div>{r.client}</div><small>{r.cause_number}</small></td><td><b className={'mio-wd-badge '+(a.needsMe?'needs':'')}>{a.kind==='complete'?'COMPLETE':a.needsMe?'NEEDS ME':'WAITING'}</b>{a.count>1&&<div>{a.count} pending actions</div>}<small>{a.waiting.join('; ')}</small></td><td>{a.next}{a.overdue&&<strong> - follow-up due</strong>}</td><td>{a.needsMe?ageLabel(a.since,now):'-'}</td><td title={r.state?.started_at||r.started_at||'Historical entry date unknown'}>{ageLabel(r.state?.started_at||r.started_at,now)}</td><td><button type="button" aria-expanded={expanded===r.matter_id} onClick={()=>setExpanded(expanded===r.matter_id?'':r.matter_id)}>Review</button></td></tr>})}{!visible.length&&<tr><td colSpan={6}>No withdrawals match this view.</td></tr>}</tbody></table></div>
 <p className="mio-wd-muted">Action time and withdrawal-entry time are separate clocks. Unknown historical dates are not guessed. Linked module updates are recorded when synchronized; this is not an always-on email, e-signature, or court monitor.</p>
 {selected&&<section className="mio-wd-detail"><header><h2>{selected.name}</h2><button type="button" onClick={()=>setExpanded('')}>Close details</button></header>{!selected.state?<><p>This existing matter needs a verified workflow record. The previous checklist is preserved below; a checked box alone is not filing or delivery proof.</p><button type="button" disabled={busy} onClick={()=>run(()=>store.initialize(owner,selected.matter_id,selected.started_at||null))}>Initialize and review current progress</button></>:<><div className="mio-wd-tools"><span>Entered withdrawal: {when(selected.state.started_at)}</span><button type="button" disabled={busy||selected.state.status==='complete'} onClick={()=>setEditor({type:'date',title:'Withdrawal entry date',matter:selected.matter_id,date:dateInput(selected.state.started_at),reason:''})}>Record / correct entry date</button><button type="button" disabled={busy||selected.state.status==='complete'} onClick={()=>setEditor({type:'routes',title:'Parallel workflow routes',matter:selected.matter_id,...selected.state.routes,reason:''})}>Signature / hearing routes</button><button type="button" disabled={busy} onClick={()=>run(async()=>setEditor({type:'history',title:'Audit history',events:await store.history(owner,selected.matter_id)}))}>Audit history</button></div>
 <div className="mio-wd-lanes">{[...new Set(WITHDRAWAL_STEPS.map(s=>s.lane))].map(lane=><section key={lane}><h3>{lane}</h3>{WITHDRAWAL_STEPS.filter(s=>s.lane===lane).map(d=>{const t=selected.state.steps[d.id];return <article className={'mio-wd-step '+t.status} key={d.id}><strong>{d.name}</strong><div>{STATUS_LABELS[t.status]}</div>{t.attention_since&&<small>Pending {ageLabel(t.attention_since,now)}</small>}{t.status==='waiting'&&<p>{t.waiting_on}<br/>Follow-up: {when(t.due_at)}</p>}{t.note&&<p>{t.note}</p>}{t.evidence?.reference&&<small>Evidence: {t.evidence.reference}</small>}{selected.state.status!=='complete'&&<div className="mio-wd-tools"><button type="button" disabled={busy} onClick={()=>edit(selected,d)}>Record update / evidence</button>{d.module==='status'?<button type="button" disabled={busy||selected.state.steps.signed_order.status!=='complete'||t.status==='complete'} onClick={()=>run(()=>onStatus(selected.matter_id))}>Approve case status change</button>:d.module!=='review'&&<button type="button" disabled={busy||['not_started','cancelled'].includes(t.status)} onClick={()=>run(()=>onOpen(selected.matter_id,d,selected.state))}>Open {d.module==='email'?'Email':d.module}</button>}{d.id==='closeout_email'&&<button type="button" disabled={busy||selected.state.steps.signed_order.status!=='complete'} onClick={()=>prepareCloseout(selected)}>Prepare client closeout</button>}{['notice','service'].includes(d.id)&&!['not_started','cancelled'].includes(t.status)&&['efile','mail_center'].map(module=><button type="button" disabled={busy} key={module} onClick={()=>run(()=>onOpen(selected.matter_id,{...d,module},selected.state))}>Open {module==='efile'?'eFile':'Mail Center'}</button>)}</div>}</article>})}</section>)}</div><details><summary>Linked matter documents</summary>{documents.filter(d=>String(d.matter_id)===selected.matter_id).map(d=><p key={d.id}><button type="button" onClick={()=>onViewDocument(d)}>{d.file_name||d.name}</button></p>)}</details></>}</section>}
 <div ref={bottom}>{settingsOpen&&<section className="mio-wd-detail"><h2>Withdrawal and drafting settings</h2><p>Approval and evidence gates remain enabled. Each waiting step has its own editable follow-up time; when due, the row returns to Needs me. This does not automatically send an email.</p>{settings}</section>}</div><details className="mio-wd-legacy"><summary>Previous withdrawal graph and checklist (preserved)</summary>{legacy}</details>
 {editor&&<Dialog title={editor.title} close={close}>{editor.type==='step'&&<><label>Status<select value={editor.status} onChange={e=>change({status:e.target.value})}>{['needs_action','needs_approval','waiting','complete','cancelled'].map(s=><option key={s} value={s}>{STATUS_LABELS[s]}</option>)}</select></label><label>Update / evidence explanation<textarea rows={3} value={editor.note} onChange={e=>change({note:e.target.value})}/></label><label>Evidence reference (document, filing receipt, thread or recorded approval)<input value={editor.reference} onChange={e=>change({reference:e.target.value})}/></label>{editor.id==='signed_order'&&<label>Actual signed-order document<select value={editor.document_id} onChange={e=>change({document_id:e.target.value,reference:e.target.value})}><option value="">Select a saved matter document</option>{documents.filter(d=>String(d.matter_id)===editor.matter).map(d=><option key={d.id} value={d.id}>{d.file_name||d.name}</option>)}</select></label>}{editor.status==='waiting'&&<label>Waiting on<input value={editor.waiting_on} onChange={e=>change({waiting_on:e.target.value})}/></label>}{(editor.status==='waiting'||editor.id==='setting')&&<label>{editor.id==='setting'&&editor.status==='complete'?'Confirmed hearing / submission date':'Follow-up due'}<input type="datetime-local" value={editor.due_at} onChange={e=>change({due_at:e.target.value})}/></label>}{editor.status==='complete'&&<><label className="check"><input type="checkbox" checked={editor.confirmed} onChange={e=>change({confirmed:e.target.checked})}/>I reviewed the actual evidence and confirm completion.</label>{editor.task.status==='not_started'&&<label className="check"><input type="checkbox" checked={editor.historical_confirmed} onChange={e=>change({historical_confirmed:e.target.checked})}/>This records verified historical work completed outside the workflow.</label>}{editor.id==='closeout_email'&&<label className="check"><input type="checkbox" checked={editor.delivery_confirmed} onChange={e=>change({delivery_confirmed:e.target.checked})}/>I verified delivery of the signed order and all resource links; the reference identifies that proof.</label>}{editor.id==='status_update'&&<p>Use the case-status approval button. A checked box does not update the matter.</p>}</>}</>}
 {editor.type==='date'&&<><label>When the matter entered withdrawal<input type="datetime-local" value={editor.date} onChange={e=>change({date:e.target.value})}/></label><label>Source / reason<input value={editor.reason} onChange={e=>change({reason:e.target.value})}/></label></>}
 {editor.type==='routes'&&<>{[['agreed','Agreed-order / signature route'],['hearing','Hearing / court setting route']].map(([key,label])=><label className="check" key={key}><input type="checkbox" checked={editor[key]} onChange={e=>change({[key]:e.target.checked})}/>{label}</label>)}<label>Reason<textarea value={editor.reason} onChange={e=>change({reason:e.target.value})}/></label><p>Stopping a route here does not cancel court events, filings, or signature requests.</p></>}
 {editor.type==='closeout'&&<><p>Supply client-accessible, matter-specific sharing links, not internal Mio dashboard URLs. The verified signed order will be attached in the Email module.</p>{[['invoices','All invoices'],['efilings','All e-filings'],['documents','All case documents, exhibits and client-provided files']].map(([key,label])=><label key={key}>{label}<input type="url" value={editor.links[key]||''} onChange={e=>change({links:{...editor.links,[key]:e.target.value}})}/></label>)}<label className="check"><input type="checkbox" checked={editor.links_verified} onChange={e=>change({links_verified:e.target.checked})}/>I verified client access and that these links expose only this matter.</label><label>Subject<input value={editor.subject} onChange={e=>change({subject:e.target.value})}/></label><label>Message<textarea rows={9} value={editor.body} onChange={e=>change({body:e.target.value})}/></label><h3>Populated preview</h3><div className="mio-wd-message">{editor.body.replace(/\{\{(invoices|efilings|documents)\}\}/g,(_,k)=>editor.links[k]||`[Add ${k} link]`)}</div><p>Saving prepares this message. It does not send it.</p></>}
 {editor.type==='history'&&<ol>{editor.events.map(e=><li key={e.event_id}><strong>{when(e.recorded_at)} - {e.event.type}</strong><p>{e.event.step_id} {e.event.note||e.event.reason}</p><small>{e.event.evidence?.reference}</small></li>)}</ol>}{error&&<p role="alert">{error}</p>}{editor.type!=='history'&&<div className="mio-wd-tools"><button type="button" disabled={busy} onClick={save}>{busy?'Saving...':'Save to workflow'}</button><button type="button" disabled={busy} onClick={close}>Cancel</button></div>}</Dialog>}
 </main>
}
