import React from 'react'

export const WITHDRAWAL_FLOW_SHEET=[
 {lane:'Preparation',step:'1. Approve withdrawal',complete:'Attorney confirms the matter should enter withdrawal status.',mio:'Start the motion / proposed-order drafting step and offer the connected withdrawal template.',you:'Approve the withdrawal decision.',wait:'None.'},
 {lane:'Preparation',step:'2. Prepare and approve motion / order',complete:'The reviewed motion / order files are connected and attorney approves the draft.',mio:'Prepare the next e-file step around the approved PDF and ask for filing selections and service contacts.',you:'Review the draft and approve it. If it was already done, use Already completed.',wait:'None after approval.'},
 {lane:'Preparation',step:'3. File motion and verify acceptance',complete:'The approved filing is submitted and clerk/provider evidence shows acceptance. Submission alone is not acceptance.',mio:'Prepare the filing package, then track provider status. After acceptance, move to initial service / delivery.',you:'Confirm what is being filed, filing code/location, service contacts and fees; approve final submission.',wait:'Clerk / e-file provider acceptance.'},
 {lane:'Preparation',step:'4. Verify initial service / delivery',complete:'Correct recipients, attachments, method and delivery are verified.',mio:'Start the agreed-order and hearing routes that are enabled.',you:'Verify service / delivery. If already complete, use Already completed.',wait:'Delivery confirmation if required.'},
 {lane:'Agreed-order route',step:'5. Client signature / response',complete:'Client response/signature is received and reviewed, or the route is superseded.',mio:'Draft the client email with the correct documents and monitor the linked thread after approved send.',you:'Review/approve the email, recipients and attachments; review the response.',wait:'Client response / signature.'},
 {lane:'Agreed-order route',step:'6. Counsel / pro se signature',complete:'Opposing counsel / pro se response or signature is received and reviewed.',mio:'Draft the signature-request email, propose recipients from the matter, and monitor the linked thread after approved send.',you:'Confirm recipient(s), approve the email, and review the response.',wait:'Opposing counsel / party response.'},
 {lane:'Agreed-order route',step:'7. Submit agreed order to court',complete:'The agreed order is submitted through the proper channel.',mio:'Prepare the agreed-order submission and then move into signed-order monitoring.',you:'Approve the exact order and submission method.',wait:'Court-signed order.'},
 {lane:'Hearing route',step:'8. Request and confirm setting',complete:'A hearing/submission date is confirmed and saved.',mio:'Draft the setting-request email, propose the court recipient, and surface the confirmed setting in Need to Set / Calendar.',you:'Approve the request email and verify the confirmed setting.',wait:'Court / coordinator response.'},
 {lane:'Hearing route',step:'9. Draft, file, serve and mail hearing notice',complete:'Notice is approved, filed if required, served on correct contacts, mailed if required, and related confirmations are recorded.',mio:'Draft the notice from the confirmed setting and prepare the filing/service/mail actions.',you:'Review the notice and approve filing, service, mailing and recipients.',wait:'Clerk acceptance and any service / mailing confirmation.'},
 {lane:'Hearing route',step:'10. Hearing / submission outcome',complete:'The hearing/submission occurred and the outcome is recorded.',mio:'Keep the setting visible and then move into signed-order monitoring.',you:'Verify the result and any follow-up required.',wait:'Hearing/submission date, then signed order.'},
 {lane:'Signed order and closeout',step:'11. Receive and verify signed order',complete:'The actual signed withdrawal order is connected and verified.',mio:'Begin closeout: surface remaining settings, propose the matter-status change, gather client links and prepare the closeout email.',you:'Verify that the connected file is the signed order.',wait:'Court-signed order until received.'},
 {lane:'Signed order and closeout',step:'12. Review remaining court settings',complete:'Every future setting is reviewed and either properly cleared/cancelled or intentionally kept.',mio:'Show remaining settings from Need to Set / Calendar and propose the action for each.',you:'Approve what should be cancelled, cleared or kept. Mio never assumes an external setting was cancelled.',wait:'Court confirmation when required.'},
 {lane:'Signed order and closeout',step:'13. Review new correspondence',complete:'Any new withdrawal-related reply is reviewed and resolved.',mio:'Surface new replies and identify the related withdrawal step/thread.',you:'Review the reply and choose any needed response.',wait:'Only if an outside response/action is required.'},
 {lane:'Signed order and closeout',step:'14. Approve Order Need to Close status',complete:'The matter status change is approved and saved.',mio:'Propose Order Need to Close as soon as the signed order is verified.',you:'Approve the matter status change.',wait:'None after approval.'},
 {lane:'Signed order and closeout',step:'15. Send signed order and client-file links',complete:'The approved closeout email contains the signed order and verified client-accessible invoice, e-filing and document links; delivery is verified.',mio:'Gather links, draft the email, attach/link the signed order and present the complete message for approval.',you:'Review/approve the email and links; verify delivery if the provider cannot confirm it.',wait:'Email delivery / response if confirmation is needed.'},
 {lane:'Signed order and closeout',step:'16. Approve workflow completion',complete:'Signed order, remaining settings, matter status, client delivery and new correspondence are resolved.',mio:'Show a final closeout summary and close the workflow after approval.',you:'Final approval that nothing remains outstanding.',wait:'None.'}
]

const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))
function downloadFlowSheet(){
 const rows=WITHDRAWAL_FLOW_SHEET.map(r=>`<tr><td>${esc(r.lane)}</td><td>${esc(r.step)}</td><td>${esc(r.complete)}</td><td>${esc(r.mio)}</td><td>${esc(r.you)}</td><td>${esc(r.wait)}</td></tr>`).join('')
 const html=`<!doctype html><html><head><meta charset="utf-8"><title>Mio Withdrawal Workflow Flow Sheet</title><style>body{font:13px Arial,sans-serif;margin:28px;color:#17202a}h1{margin-bottom:4px}p{max-width:1000px;line-height:1.45}table{border-collapse:collapse;width:100%}th,td{border:1px solid #aeb9c4;padding:8px;vertical-align:top;text-align:left}th{background:#eef3f7}tr:nth-child(even){background:#fafcfd}.rule{padding:10px 12px;background:#eef6ff;border-left:4px solid #356f9f;margin:14px 0}@media print{body{margin:12mm}thead{display:table-header-group}}</style></head><body><h1>Mio Withdrawal Workflow Flow Sheet</h1><p>Design rule: whenever Mio can safely prepare the next task without external consequences, Mio should prepare it automatically and present the result for attorney approval. Sending email, filing with a court, changing a matter status, or representing that service/acceptance occurred still requires the appropriate confirmation or provider evidence.</p><div class="rule"><strong>Normal rhythm:</strong> Mio prepares → attorney reviews/approves → Mio performs or stages the approved action → Mio verifies the result → Mio advances to the next step. Historical work may use <strong>Already completed</strong>.</div><table><thead><tr><th>Branch</th><th>Step</th><th>Required to complete</th><th>What Mio does next</th><th>What you approve / provide</th><th>Waiting on</th></tr></thead><tbody>${rows}</tbody></table></body></html>`
 const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='Mio-Withdrawal-Workflow-Flow-Sheet.html';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)
}

export default function MioWithdrawalFlowSheet(){return <section className="mio-wd-flow-sheet"><header><div><h3>Withdrawal workflow flow sheet</h3><p>See what completes each step, what Mio should prepare next, what still needs your approval, and what the workflow is waiting on.</p></div><button type="button" onClick={downloadFlowSheet}>Download flow sheet</button></header><div className="mio-wd-flow-rule"><strong>Target workflow:</strong> Mio prepares → you approve → Mio advances. Use <strong>Already completed</strong> for work that happened outside Mio.</div><div className="mio-wd-flow-table"><table><thead><tr><th>Step</th><th>Required to complete</th><th>What Mio does next</th><th>You</th></tr></thead><tbody>{WITHDRAWAL_FLOW_SHEET.map(r=><tr key={r.step}><td><small>{r.lane}</small><strong>{r.step}</strong></td><td>{r.complete}</td><td>{r.mio}<small>Waiting: {r.wait}</small></td><td>{r.you}</td></tr>)}</tbody></table></div></section>}
