import React,{useEffect,useState} from 'react'
import {WORKFLOW_ACTIONS,validateWorkflowDefinition,removeWorkflowRow,removeWorkflowSteps} from './mioWorkflowBlocks.js'
const clone=x=>JSON.parse(JSON.stringify(x)),id=prefix=>prefix+'_'+crypto.randomUUID().replaceAll('-','')
function Choices({label,items,value=[],onChange}){return <fieldset><legend>{label}</legend>{items.length?items.map(x=><label className="mio-block-check" key={x.id}><input type="checkbox" checked={value.includes(x.id)} onChange={e=>onChange(e.target.checked?[...value,x.id]:value.filter(v=>v!==x.id))}/>{x.name}</label>):<small>No items available.</small>}</fieldset>}
export default function MioWorkflowBuilder({definition,templates=[],statusOptions={},onSave,onClose,title='Withdrawal workflow template'}){
 const[draft,setDraft]=useState(()=>clone(definition)),[selected,setSelected]=useState(''),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{if(!dirty)return;const stop=e=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',stop);return()=>window.removeEventListener('beforeunload',stop)},[dirty])
 const change=fn=>{setDraft(d=>fn(clone(d)));setDirty(true);setError('')},step=draft.steps.find(s=>s.id===selected)
 const patchStep=patch=>change(d=>({...d,steps:d.steps.map(s=>s.id===selected?{...s,...patch}:s)}))
 function move(items,index,delta){const target=index+delta;if(target<0||target>=items.length)return items;[items[index],items[target]]=[items[target],items[index]];return items}
 function moveStep(s,delta){const lane=draft.steps.filter(x=>x.row_id===s.row_id),i=lane.findIndex(x=>x.id===s.id),other=lane[i+delta];if(!other)return;change(d=>{const a=d.steps.findIndex(x=>x.id===s.id),b=d.steps.findIndex(x=>x.id===other.id);[d.steps[a],d.steps[b]]=[d.steps[b],d.steps[a]];return d})}
 function removeRow(row){if(!window.confirm('Remove row "'+row.name+'" and its steps from this definition? Saved progress and documents are retained. Later prerequisites will reconnect to the removed steps\' prerequisites.'))return;try{const next=removeWorkflowRow(draft,row.id);change(()=>next)}catch(e){setError(e.message)}}
 function removeStep(s){if(!window.confirm('Remove "'+s.name+'"? Saved history and document slots are retained; later prerequisites reconnect to its prerequisites.'))return;try{const next=removeWorkflowSteps(draft,[s.id]);change(()=>next);setSelected('')}catch(e){setError(e.message)}}
 const close=()=>{if(!dirty||window.confirm('Discard unsaved workflow edits?'))onClose?.()}
 return <section className="mio-block-builder"><header><div><h2>{title}</h2><p>Rows organize the process. Steps choose an action, prerequisites, input slots and output slots.</p></div><button type="button" disabled={busy} onClick={close}>Close editor</button></header>
 <p className="mio-block-note">Template changes affect new processes. An existing matter keeps its saved definition until you explicitly apply the template or edit that matter. Removing a step never deletes a document or its audit history.</p>
 {error&&<p role="alert" className="mio-block-error">{error}</p>}
 <div className="mio-block-layout"><div><h3>Rows and steps</h3>{draft.rows.map((row,ri)=><section className="mio-block-row-editor" key={row.id}><div className="mio-block-tools"><input aria-label={'Row name '+(ri+1)} value={row.name} maxLength={160} onChange={e=>change(d=>({...d,rows:d.rows.map(r=>r.id===row.id?{...r,name:e.target.value}:r)}))}/><button type="button" aria-label={'Move '+row.name+' up'} disabled={!ri} onClick={()=>change(d=>({...d,rows:move(d.rows,ri,-1)}))}>Up</button><button type="button" aria-label={'Move '+row.name+' down'} disabled={ri===draft.rows.length-1} onClick={()=>change(d=>({...d,rows:move(d.rows,ri,1)}))}>Down</button><button type="button" disabled={draft.rows.length===1} onClick={()=>removeRow(row)}>Delete row</button></div>
 {draft.steps.filter(s=>s.row_id===row.id).map(s=><div key={s.id} className="mio-block-tools"><button type="button" aria-pressed={selected===s.id} onClick={()=>setSelected(s.id)}>{s.name}</button><button type="button" aria-label={'Move '+s.name+' up'} onClick={()=>moveStep(s,-1)}>Up</button><button type="button" aria-label={'Move '+s.name+' down'} onClick={()=>moveStep(s,1)}>Down</button><button type="button" onClick={()=>removeStep(s)}>Delete step</button></div>)}
 <button type="button" onClick={()=>{const key=id('step');change(d=>({...d,steps:[...d.steps,{id:key,name:'New step',row_id:row.id,action:'manual',depends_on:[],dependency_mode:'all',input_slots:[],output_slots:[],recipient_roles:[],manual_start:true,template_id:'',output_files:{},target_field:'matter_status',target_value:''}]}));setSelected(key)}}>+ Add step to {row.name}</button></section>)}
 <button type="button" onClick={()=>change(d=>({...d,rows:[...d.rows,{id:id('row'),name:'New row'}]}))}>+ Add row</button></div>
 <div>{step?<section className="mio-block-step-editor"><h3>Edit step</h3><label>Step name<input value={step.name} maxLength={160} onChange={e=>patchStep({name:e.target.value})}/></label><label>Row<select value={step.row_id} onChange={e=>patchStep({row_id:e.target.value})}>{draft.rows.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label><label>Step action<select value={step.action} onChange={e=>patchStep({action:e.target.value})}>{WORKFLOW_ACTIONS.map(a=><option value={a.id} key={a.id}>{a.label}</option>)}</select></label>
 <Choices label="Input document slots" items={draft.slots} value={step.input_slots} onChange={input_slots=>patchStep({input_slots})}/><Choices label="Output document slots" items={draft.slots} value={step.output_slots} onChange={output_slots=>patchStep({output_slots})}/>
 <Choices label="Prerequisite steps" items={draft.steps.filter(s=>s.id!==step.id)} value={step.depends_on} onChange={depends_on=>patchStep({depends_on})}/><label>Start after<select value={step.dependency_mode} onChange={e=>patchStep({dependency_mode:e.target.value})}><option value="all">All prerequisites complete or cancelled</option><option value="any">Any prerequisite complete or cancelled</option></select></label><label className="mio-block-check"><input type="checkbox" checked={!!step.manual_start} onChange={e=>patchStep({manual_start:e.target.checked})}/>Start manually (otherwise activate when prerequisites are met)</label>
 {step.action==='draft_document'&&<><label>Connected drafting template<select value={step.template_id||''} onChange={e=>patchStep({template_id:e.target.value,output_files:{}})}><option value="">Choose at runtime / use existing connection</option>{templates.filter(t=>t.is_active!==false&&t.status!=='retired').map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{step.output_slots.map(slot=><label key={slot}>Generated file for {draft.slots.find(s=>s.id===slot)?.name}<select value={step.output_files?.[slot]||''} onChange={e=>patchStep({output_files:{...step.output_files,[slot]:e.target.value}})}><option value="">Assign after generation if ambiguous</option>{(templates.find(t=>t.id===step.template_id)?.files||[]).map(f=><option value={f.name} key={f.id||f.name}>{f.name}</option>)}</select></label>)}</>}
 {['draft_email','esign_document'].includes(step.action)&&<><Choices label="Suggested recipient roles (confirm actual people per matter)" items={[{id:'client',name:'Client'},{id:'opposing_counsel',name:'Opposing counsel'},{id:'opposing_party',name:'Opposing party'},{id:'court',name:'Court coordinator'}]} value={step.recipient_roles||[]} onChange={recipient_roles=>patchStep({recipient_roles})}/>{step.action==='esign_document'&&<p className="mio-block-note">This block prepares the request and tracks the returned document. A signature-provider request link is required to send an e-signature invitation; it does not invent a signing link or treat email delivery as a signature.</p>}</>}
 {step.action==='matter_status'&&<><label>Status field<select value={step.target_field||'matter_status'} onChange={e=>patchStep({target_field:e.target.value,target_value:''})}><option value="matter_status">Matter status</option><option value="case_status">Case status</option></select></label><label>New status<select value={step.target_value||''} onChange={e=>patchStep({target_value:e.target.value})}><option value="">Choose from Settings</option>{(statusOptions[step.target_field||'matter_status']||[]).map(o=><option key={o.id||o.name} value={o.name}>{o.name}</option>)}</select></label></>}
 </section>:<p>Select a step to edit its action, input / output slots and prerequisites.</p>}</div></div>
 <details><summary>Shared document slot definitions ({draft.slots.length})</summary><p>These slots belong to the entire process, not to a single step.</p>{draft.slots.map(slot=><div key={slot.id} className="mio-block-tools"><input aria-label={'Slot name '+slot.name} value={slot.name} maxLength={160} onChange={e=>change(d=>({...d,slots:d.slots.map(s=>s.id===slot.id?{...s,name:e.target.value}:s)}))}/><select aria-label={'Document kind '+slot.name} value={slot.kind} onChange={e=>change(d=>({...d,slots:d.slots.map(s=>s.id===slot.id?{...s,kind:e.target.value}:s)}))}><option value="draft">Draft</option><option value="filed">File-stamped</option><option value="signed">Signed</option><option value="other">Other</option></select><button type="button" disabled={slot.id===draft.completion_slot||draft.steps.some(s=>[...s.input_slots,...s.output_slots].includes(slot.id))} title="Remove step references before deleting a slot. The completion slot must remain." onClick={()=>change(d=>({...d,slots:d.slots.filter(s=>s.id!==slot.id)}))}>Delete slot</button></div>)}<button type="button" onClick={()=>change(d=>({...d,slots:[...d.slots,{id:id('slot'),name:'New document slot',kind:'other'}]}))}>+ Add document slot</button></details>
 <footer className="mio-block-tools"><button type="button" className="mio-block-primary" disabled={busy||!dirty} onClick={async()=>{setBusy(true);setError('');try{validateWorkflowDefinition(draft);await onSave(draft);setDirty(false)}catch(e){setError(e.message||String(e))}finally{setBusy(false)}}}>{busy?'Saving...':'Save workflow definition'}</button><span>{dirty?'Unsaved definition changes':'Definition saved / unchanged'}</span></footer></section>
}
