import React,{useEffect,useRef,useState} from 'react'
import {aggregateMetrics} from '../../lib/ads/model.js'
import {Notice,money} from './Common.jsx'
function groups(rows=[]){const m=new Map();for(const r of rows){const k=JSON.stringify([r.label,r.locationType]);if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return[...m.values()].map(a=>({...a[0],...aggregateMetrics(a)})).sort((a,b)=>b.cost-a.cost)}
export default function Audience({api,data,days=30,initialCampaignId='',initialAdGroupId=''}){
 const[open,setOpen]=useState(false),[campaign,setCampaign]=useState(initialCampaignId),[group,setGroup]=useState(initialAdGroupId),[value,setValue]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState('');const call=useRef(api);call.current=api
 const source=[...(data.ads||[]),...(data.searchTerms||[])],campaigns=[...new Map(source.map(r=>[r.campaignId,r.campaignName])).entries()].filter(r=>r[0]),adGroups=[...new Map(source.filter(r=>!campaign||r.campaignId===campaign).map(r=>[r.adGroupId,r.adGroupName])).entries()].filter(r=>r[0])
 useEffect(()=>{if(!open)return;let active=true;setLoading(true);setValue(null);setError('');call.current('workspace_audience',{params:{days,...(campaign?{campaignId:campaign}:{}),...(group?{adGroupId:group}:{})}}).then(r=>{if(active)setValue(r)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[open,campaign,group,days])
 return<details className="aw-audience" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>Audience &amp; locations</summary>{open&&<><Notice>Aggregate campaign/ad-group reports, not the demographics of individual search terms or identifiable visitors. Unknown values are not inferred.</Notice><div className="aw-toolbar"><label>Campaign<select value={campaign} onChange={e=>{setCampaign(e.target.value);setGroup('')}}><option value="">All campaigns</option>{campaigns.map(([id,n])=><option value={id} key={id}>{n}</option>)}</select></label><label>Ad group<select value={group} onChange={e=>setGroup(e.target.value)}><option value="">All ad groups</option>{adGroups.map(([id,n])=><option value={id} key={id}>{n}</option>)}</select></label><span>Last {days} days</span></div>{loading&&<p role="status">Loading aggregate reports...</p>}<Notice error>{error}</Notice>{value?.warnings?.map(w=><Notice key={w.section} error>{w.section}: {w.message}</Notice>)}{value&&<div className="aw-audience-grid">{[['age','Age range'],['gender','Google-reported gender'],['locations','Locations']].map(([key,title])=><section key={key}><h3>{title}</h3><div className="aw-scroll"><table><thead><tr><th>{title}</th><th>Clicks</th><th>Cost</th><th>Conv.</th></tr></thead><tbody>{groups(value[key]).map((r,i)=><tr key={i}><td>{r.label||'Unknown / not available'}{r.locationType&&<small>{r.locationType==='LOCATION_OF_PRESENCE'?'Location of presence':r.locationType==='AREA_OF_INTEREST'?'Area of interest, not necessarily physical location':'Location type unknown'}</small>}</td><td>{r.clicks}</td><td>{money(r.cost)}</td><td>{r.conversions}</td></tr>)}{!value[key]?.length&&<tr><td colSpan="4">No data returned for this scope.</td></tr>}</tbody></table></div></section>)}</div>}<small>These are separate breakdowns; do not add their totals together. Privacy and coverage can differ from overall totals.</small></>}</details>
}
