import React,{useState} from 'react'
export default function ColumnFilter({column,rows,value,onChange}) {
 const [operator,setOperator]=useState(value?.operator||(column.type==='numeric'?'>':column.type==='date'?'after':'contains'))
 const [input,setInput]=useState(value?.value==null?'':String(column.format==='percent'?value.value*100:value.value)),[max,setMax]=useState(value?.max==null?'':String(column.format==='percent'?value.max*100:value.max)),[error,setError]=useState('')
 const ops=column.type==='numeric'?['>','>=','<','<=','=','between','nonzero','blank']:column.type==='date'?['before','after','between']:['contains','equals','does not contain']
 const values=[...new Set(rows.map(r=>r[column.key]).filter(v=>v!=null&&v!==''))].sort()
 function apply(e){e.preventDefault();setError('');try{const rule={column:column.key,type:column.type,operator};if(!['nonzero','blank'].includes(operator)){if(!input.trim())throw Error('Enter a filter value.');rule.value=column.type==='numeric'?Number(input)/(column.format==='percent'?100:1):input;if(column.type==='numeric'&&!Number.isFinite(rule.value))throw Error('Enter a number.');if(operator==='between'){if(!max.trim())throw Error('Enter both bounds.');rule.max=column.type==='numeric'?Number(max)/(column.format==='percent'?100:1):max;if(column.type==='numeric'&&!Number.isFinite(rule.max))throw Error('Enter a number.')}}onChange(rule)}catch(err){setError(err.message)}}
 return <details className="kl-filter"><summary aria-label={`Filter ${column.label}`}>Filter{value?' •':''}</summary><div className="kl-filter-panel">
 {column.type==='categorical'?<fieldset><legend>{column.label}</legend>{values.map(v=><label key={v}><input type="checkbox" checked={value?.values?.includes(v)||false} onChange={e=>{const next=e.target.checked?[...(value?.values||[]),v]:(value?.values||[]).filter(x=>x!==v);onChange(next.length?{column:column.key,type:'categorical',values:next}:null)}}/>{v}</label>)}</fieldset>:<form onSubmit={apply}><label>Operator<select aria-label={`${column.label} operator`} value={operator} onChange={e=>setOperator(e.target.value)}>{ops.map(op=><option key={op}>{op}</option>)}</select></label>{!['nonzero','blank'].includes(operator)&&<label>Value{column.format==='percent'?' (%)':''}<input aria-label={`${column.label} filter value`} type={column.type==='date'?'date':column.type==='numeric'?'number':'text'} step="any" value={input} onChange={e=>setInput(e.target.value)}/></label>}{operator==='between'&&<label>Upper bound<input aria-label={`${column.label} upper bound`} type={column.type==='date'?'date':'number'} step="any" value={max} onChange={e=>setMax(e.target.value)}/></label>}<button type="submit">Apply filter</button>{error&&<p role="alert">{error}</p>}</form>}
 <button type="button" onClick={()=>onChange(null)}>Clear {column.label} filter</button></div></details>
}
