import React,{useEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import {previewAssets} from '../../lib/ads/model.js'
export const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0)
export const percent=n=>`${((Number(n)||0)*100).toFixed(1)}%`
export function Notice({children,error=false}){return children?<div className={`aw-notice ${error?'aw-error':''}`} role={error?'alert':'status'}>{children}</div>:null}
export function Modal({title,children,onClose,busy=false}){
 const root=useRef(),latest=useRef({onClose,busy});latest.current={onClose,busy}
 useEffect(()=>{const old=document.activeElement;root.current?.focus();const key=e=>{if(e.key==='Escape'&&!latest.current.busy)latest.current.onClose();if(e.key==='Tab'){const a=[...root.current.querySelectorAll('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),select:not(:disabled),[tabindex="0"]')];if(e.shiftKey&&(document.activeElement===a[0]||document.activeElement===root.current)){e.preventDefault();a.at(-1)?.focus()}else if(!e.shiftKey&&document.activeElement===a.at(-1)){e.preventDefault();a[0]?.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);old?.focus?.()}},[])
 return createPortal(<div className="aw-overlay"><section className="mio-ads-dialog" role="dialog" aria-modal="true" aria-label={title} ref={root} tabIndex={-1}><header><h2>{title}</h2><button onClick={onClose} disabled={busy}>Close</button></header>{children}</section></div>,document.body)
}
export function AdPreview({ad,title='Example appearance'}){const[offset,setOffset]=useState(0);let host='Landing page';try{host=new URL(ad.finalUrls?.[0]).hostname}catch{}return<section className="aw-preview"><div className="aw-preview-label">{title}</div><small>Sponsored</small><div className="aw-preview-url">{host}{ad.path1?` / ${ad.path1}`:''}{ad.path2?` / ${ad.path2}`:''}</div><div className="aw-preview-headline">{previewAssets(ad.headlines,'HEADLINE',3,offset).join(' | ')||'No headline assets returned'}</div><p>{previewAssets(ad.descriptions,'DESCRIPTION',2,offset).join(' ')}</p><button onClick={()=>setOffset(x=>x+1)}>Another combination</button><small>Illustrative only. Google selects combinations and may show fewer assets.</small></section>}
export function AssetList({ad}){return<div><h4>Headlines</h4>{(ad.headlines||[]).map((a,i)=><p key={i}>{i+1}. {a.text}{a.pinnedField&&<small>Pinned: {a.pinnedField}</small>}</p>)}<h4>Descriptions</h4>{(ad.descriptions||[]).map((a,i)=><p key={i}>{i+1}. {a.text}{a.pinnedField&&<small>Pinned: {a.pinnedField}</small>}</p>)}<small>Final URLs: {(ad.finalUrls||[]).join(', ')}<br/>Paths: {ad.path1||'--'} / {ad.path2||'--'}</small></div>}
export function Results({result}){if(!result)return null;const rows=result.results||[];return<section aria-label="Approval results"><Notice>Verified: {rows.filter(r=>r.state==='verified').length} | Skipped: {rows.filter(r=>r.state==='skipped').length} | Failed: {rows.filter(r=>r.state==='failed').length} | Awaiting verification: {rows.filter(r=>r.state==='unverified').length}</Notice>{rows.map((r,i)=><div className="aw-result" key={i}><strong>{r.keyword||`Ad ${r.adId||''}`}</strong><span className={`aw-badge ${['verified','skipped'].includes(r.state)?'aw-good':''}`}>{r.state}</span><span>{r.campaignName||r.campaignId||''}</span><small>{r.message}</small></div>)}<Notice error>{result.historyWarning}</Notice></section>}
