import React,{useState} from 'react'
import KeywordTable from './KeywordTable.jsx'
import KeywordSearchTerms from './KeywordSearchTerms.jsx'
import {recommendKeyword} from '../../lib/ads/keyword-lab.js'
import {keywordKey,isLinked,matches,existingItem,textColumn,numericColumn,metricColumns,qualityColumns} from './keyword-ui.js'
function MatchControls({row,onQueue,canQueue}) {
 const [kind,setKind]=useState('change_match_type')
 return <div className="kl-actions"><select aria-label={`Match action ${row.keyword}`} value={kind} onChange={e=>setKind(e.target.value)}><option value="change_match_type">Replace match</option><option value="add_match_type">Add another match</option></select><select aria-label={`Match type ${row.keyword}`} value={row.matchType} disabled={!canQueue} onChange={e=>onQueue(existingItem(row,kind,e.target.value))}>{matches.map(m=><option key={m}>{m}</option>)}</select><small>Queues for review</small></div>
}
export default function CurrentKeywords({rows,terms,experiments=[],state,onState,expanded,onExpanded,onTerms,onKeyword,onQueue,onClassify,onDiscover,canQueue,currency}) {
 const [selection,setSelection]=useState([]),[bulkMatch,setBulkMatch]=useState('EXACT'),[bulkKind,setBulkKind]=useState('change_match_type')
 const enriched=rows.map(r=>{const experiment=experiments.find(e=>e.criterionResourceName===r.criterionResourceName),recommendation=recommendKeyword(r);return {...r,experimentState:experiment?.state||'core',experimentDate:experiment?.experimentStartedAt?.slice(0,10)||null,recommendation:recommendation.label,reasons:recommendation.reasons,sampleSize:`${r.impressions??'—'} impressions / ${r.clicks??'—'} clicks`}})
 const selected=enriched.filter(r=>selection.includes(keywordKey(r)))
 const columns=[{...textColumn('keyword','Keyword'),required:true,render:r=><button className="kl-link" aria-expanded={expanded===keywordKey(r)} onClick={()=>onExpanded(expanded===keywordKey(r)?null:keywordKey(r))}>{expanded===keywordKey(r)?'▾':'▸'} {r.keyword}</button>},textColumn('status','Status','categorical'),{...textColumn('matchType','Match type','categorical'),render:r=><MatchControls key={keywordKey(r)} row={r} {...{onQueue,canQueue}}/>},textColumn('campaignName','Campaign'),textColumn('adGroupName','Ad group'),...metricColumns,...['searchImpressionShare','searchRankLostImpressionShare','searchBudgetLostImpressionShare','topImpressionRate','absoluteTopImpressionRate'].map((key,i)=>({...numericColumn(key,['Search impression share','Lost share (rank)','Lost share (budget)','Top impression rate','Absolute top rate'][i],'percent'),hidden:true})),numericColumn('searchTermCount','Search-term count'),...qualityColumns.map(c=>({...c,hidden:true})),{...textColumn('experimentState','Experiment state','categorical'),hidden:true},{...textColumn('experimentDate','Experiment start','date'),hidden:true},{...textColumn('recommendation','Recommendation','categorical'),render:r=><span title={r.reasons.join('; ')}>{r.recommendation}<small>{r.reasons.join('; ')}</small></span>},textColumn('sampleSize','Sample size'),{key:'actions',label:'Actions',render:r=><button disabled={!canQueue} onClick={()=>onQueue(existingItem(r,r.status==='PAUSED'?'enable_keyword':'pause_keyword'))}>{r.status==='PAUSED'?'Queue enable':'Queue pause'}</button>}]
 const presets=[['Most opportunity','impressionsPerDay','desc'],['Most traffic','clicksPerDay','desc'],['Best CTR','ctr','desc'],['Lowest CPC','averageCpc','asc'],['Highest spend','cost','desc'],['Most waste','wasteRate','desc'],['Best conversion efficiency','costPerConversion','asc'],['Needs more data','impressions','asc'],['Experimental only','experimentDate','desc']]
 return <><div className="aw-toolbar"><label>Preset view<select aria-label="Keyword preset" defaultValue="" onChange={e=>{const p=presets.find(p=>p[0]===e.target.value);onState({...state,sort:{column:p[1],direction:p[2]},filters:p[0]==='Experimental only'?[{column:'experimentState',type:'categorical',values:['proposed','approved','active','paused']}]:[]})}}><option disabled value="">Choose view</option>{presets.map(p=><option key={p[0]}>{p[0]}</option>)}</select></label><label>Bulk action<select value={bulkKind} onChange={e=>setBulkKind(e.target.value)}><option value="change_match_type">Replace match</option><option value="add_match_type">Add another match</option></select></label><label>Bulk match<select value={bulkMatch} onChange={e=>setBulkMatch(e.target.value)}>{matches.map(m=><option key={m}>{m}</option>)}</select></label><button disabled={!canQueue||!selected.length} onClick={()=>{selected.filter(r=>r.matchType!==bulkMatch).forEach(r=>onQueue(existingItem(r,bulkKind,bulkMatch)));setSelection([])}}>Queue bulk match change</button><button disabled={!selected.length} onClick={()=>onDiscover(selected.map(r=>r.keyword),'keyword')}>Find from selected keywords</button></div><KeywordTable label="Current Keywords" rows={enriched} columns={columns} {...{state,onState,currency}} rowKey={keywordKey} selection={selection} onSelection={setSelection} renderExpanded={r=>expanded===keywordKey(r)&&<section className="kl-expanded"><h3>Search terms triggered by {r.keyword}</h3><button onClick={()=>onTerms(r)}>Open in Search Terms</button><KeywordSearchTerms rows={terms.filter(t=>isLinked(t,r))} compact {...{onQueue,onClassify,onKeyword,canQueue,currency}}/></section>}/></>
}
