import React,{useState,useRef} from 'react'
import KeywordTable from './KeywordTable.jsx'
import {matches,textColumn,numericColumn} from './keyword-ui.js'
import {coveringNegative} from '../../lib/ads/model.js'
export default function FindKeywords({seed,api,data,destinations,onQueue,canQueue,state,onState,currency}) {
 const [phrases,setPhrases]=useState(seed?.phrases?.join('\n')||''),[url,setUrl]=useState(''),[locations,setLocations]=useState(''),[language,setLanguage]=useState('1000'),[network,setNetwork]=useState('GOOGLE_SEARCH'),[candidates,setCandidates]=useState([]),[selection,setSelection]=useState([]),[match,setMatch]=useState('EXACT'),[experimental,setExperimental]=useState(true),[hypothesis,setHypothesis]=useState(''),[destination,setDestination]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const generation=useRef(0),source=seed?.source||'manual',manual=()=>phrases.split(/[\n,]+/).map(s=>s.trim()).filter(Boolean)
 async function discover(){const n=++generation.current;setBusy(true);setError('');try{const r=await api('keyword_candidates',{params:{phrases:manual().join("\n"),url,locationIds:locations,languageId:language,network,seedType:manual().length?source:"url"}});if(n!==generation.current)return;setCandidates(r.candidates||[]);setSelection([]);setNotice([r.planner?.available===false?'Keyword Planner unavailable. Manual candidates remain usable.':'Estimated market demand from Keyword Planner.',r.cache?.stale?'Cached estimates are stale.':'',...(r.warnings||[]).map(w=>w.message||String(w))].filter(Boolean).join(' '))}catch(e){if(n===generation.current)setError(e.message)}finally{if(n===generation.current)setBusy(false)}}
 const rows=candidates.map(c=>{const existing=(data.keywords||[]).filter(k=>k.keyword.toLowerCase()===c.phrase.toLowerCase()),dest=destinations.find(d=>`${d.campaignId}:${d.adGroupId}`===destination),negative=dest?coveringNegative({...dest,searchTerm:c.phrase},data.negativeKeywords||[]):null;return {...c,source:c.source||source,existingMatches:existing.map(k=>`${k.matchType} (${k.campaignName}/${k.adGroupName})`).join(', ')||'None',negativeConflict:dest?(negative?negative.keyword:'None'):'Select destination',relatedTerms:(data.searchTerms||[]).filter(t=>t.searchTerm.toLowerCase().includes(c.phrase.toLowerCase())||t.triggeringKeyword?.toLowerCase()===c.phrase.toLowerCase()).map(t=>t.searchTerm).filter((v,i,a)=>a.indexOf(v)===i).join(', ')||'None',trend:c.monthlyVolumes?.map(m=>`${m.year}-${m.month}: ${m.monthlySearches??m.searches??'—'}`).join('; ')||'—'}})
 function queue(){const dest=destinations.find(d=>`${d.campaignId}:${d.adGroupId}`===destination);if(!dest){setError('Choose a campaign and ad group.');return}rows.filter(r=>selection.includes(r.phrase)).forEach(r=>onQueue({kind:experimental?'add_experimental_keyword':'add_keyword',campaignId:dest.campaignId,adGroupId:dest.adGroupId,keyword:r.phrase,matchType:match,source:r.source==='planner'?'planner':source==='search_term'?'search_term':'manual',hypothesis}));setSelection([])}
 return <section><h3>Find Keywords</h3><p>Estimated market demand is not actual account impressions. Omitted volume does not mean zero searches.</p><div className="kl-find"><label>Seed phrases<textarea aria-label="Seed phrases" value={phrases} onChange={e=>setPhrases(e.target.value)} placeholder="One phrase per line"/></label><label>Landing-page URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)}/></label><label>Geo target IDs (comma-separated)<input value={locations} onChange={e=>setLocations(e.target.value)}/></label><label>Language ID<input value={language} onChange={e=>setLanguage(e.target.value)}/></label><label>Network<select value={network} onChange={e=>setNetwork(e.target.value)}><option>GOOGLE_SEARCH</option><option>GOOGLE_SEARCH_AND_PARTNERS</option></select></label></div><div className="aw-toolbar"><button disabled={!manual().length} onClick={()=>{generation.current++;setBusy(false);setCandidates(manual().map(phrase=>({phrase,source,avgMonthlySearches:null})));setSelection([]);setNotice('Manual candidates; market estimates unavailable until a Planner lookup.')}}>Use manual candidates</button><button disabled={busy||(!manual().length&&!url)} onClick={discover}>{busy?'Finding…':'Find with Keyword Planner'}</button></div>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <div className="aw-toolbar"><label>Destination<select aria-label="Candidate destination" value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Choose campaign / ad group</option>{destinations.map(d=><option key={`${d.campaignId}:${d.adGroupId}`} value={`${d.campaignId}:${d.adGroupId}`}>{d.campaignName} / {d.adGroupName}</option>)}</select></label><label>Proposed match<select value={match} onChange={e=>setMatch(e.target.value)}>{matches.map(m=><option key={m}>{m}</option>)}</select></label><label><input type="checkbox" checked={experimental} onChange={e=>setExperimental(e.target.checked)}/>Experimental keyword</label><label>Hypothesis<input value={hypothesis} onChange={e=>setHypothesis(e.target.value)} maxLength={2000}/></label><button disabled={!canQueue||!selection.length||!destination} onClick={queue}>Queue selected candidates</button></div>
 <KeywordTable label="Keyword candidates" rows={rows} columns={[{...textColumn('phrase','Candidate phrase'),required:true},textColumn('source','Source','categorical'),numericColumn('avgMonthlySearches','Estimated monthly searches'),textColumn('trend','Monthly search history'),textColumn('competition','Competition','categorical'),numericColumn('competitionIndex','Competition index'),numericColumn('lowBid','Low top-of-page bid','money'),numericColumn('highBid','High top-of-page bid','money'),textColumn('existingMatches','Existing match types'),textColumn('negativeConflict','Negative conflict'),textColumn('relatedTerms','Related actual search terms')]} rowKey={r=>r.phrase} {...{state,onState,selection,currency}} onSelection={setSelection}/></section>
}
