import React,{Fragment} from 'react'
import {applyColumnFilter,sortRows} from '../../lib/ads/keyword-lab.js'
import ColumnFilter from './ColumnFilter.jsx'
import {display} from './keyword-ui.js'
export default function KeywordTable({label,rows,columns,state={},onState=()=>{},rowKey,selection=[],onSelection,renderExpanded,currency}) {
 const filters=state.filters||[],visible=state.columns?columns.filter(c=>c.required||state.columns.includes(c.key)):columns.filter(c=>!c.hidden)
 let filtered,error;try{filtered=sortRows(applyColumnFilter(rows,filters),state.sort||{})}catch(e){filtered=rows;error=e.message}
 const ids=filtered.map(rowKey),setFilter=(key,value)=>onState({...state,filters:[...filters.filter(f=>f.column!==key),...(value?[value]:[])]})
 return <section aria-label={label}><div className="aw-toolbar"><span>{filtered.length} of {rows.length} rows</span><details><summary>Columns</summary><div className="kl-columns">{columns.map(c=><label key={c.key}><input type="checkbox" disabled={c.required} checked={visible.some(x=>x.key===c.key)} onChange={e=>onState({...state,columns:e.target.checked?[...visible.map(x=>x.key),c.key]:visible.filter(x=>x.key!==c.key).map(x=>x.key)})}/>Show {c.label}</label>)}</div></details><button disabled={!filters.length} onClick={()=>onState({...state,filters:[]})}>Clear all filters</button></div>
 <div className="kl-chips">{filters.map(f=>{const c=columns.find(x=>x.key===f.column)||{label:f.column};return <button key={f.column} onClick={()=>setFilter(f.column,null)}>{c.label} {f.values?.join(', ')||`${f.operator} ${['blank','nonzero'].includes(f.operator)?'':display(f.value,c)}${f.operator==='between'?` and ${display(f.max,c)}`:''}`} ×</button>})}</div>{error&&<p role="alert">{error}</p>}
 <div className="aw-scroll"><table><thead><tr>{onSelection&&<th><input type="checkbox" aria-label={`Select all ${label}`} checked={ids.length>0&&ids.every(id=>selection.includes(id))} onChange={e=>onSelection(e.target.checked?ids:[])}/></th>}{visible.map(c=><th key={c.key} aria-sort={state.sort?.column===c.key?(state.sort.direction==='desc'?'descending':'ascending'):'none'}><button className="kl-sort" onClick={()=>onState({...state,sort:{column:c.key,direction:state.sort?.column===c.key&&state.sort.direction==='asc'?'desc':'asc'}})}>{c.label}{state.sort?.column===c.key?(state.sort.direction==='desc'?' ↓':' ↑'):''}</button>{c.type&&<ColumnFilter key={`${c.key}:${JSON.stringify(filters.find(f=>f.column===c.key)||null)}`} column={c} rows={rows} value={filters.find(f=>f.column===c.key)} onChange={v=>setFilter(c.key,v)}/>}</th>)}</tr></thead><tbody>{filtered.map(r=>{const id=rowKey(r);return <Fragment key={id}><tr data-keyword-lab-row="true">{onSelection&&<td><input type="checkbox" aria-label={`Select ${r.keyword||r.searchTerm||r.phrase}`} checked={selection.includes(id)} onChange={e=>onSelection(e.target.checked?[...selection,id]:selection.filter(x=>x!==id))}/></td>}{visible.map(c=><td key={c.key}>{c.render?c.render(r):display(r[c.key],c,currency)}</td>)}</tr>{renderExpanded?.(r)&&<tr><td colSpan={visible.length+(onSelection?1:0)}>{renderExpanded(r)}</td></tr>}</Fragment>})}{!filtered.length&&<tr><td colSpan={visible.length+1}>No rows in this scope.</td></tr>}</tbody></table></div></section>
}
