import React,{useCallback,useEffect,useRef,useState} from 'react'
import {keywordLabPreferences,workspaceApi} from './client.js'
import {normalizeDateRange} from '../../lib/ads/keyword-lab.js'
import CurrentKeywords from './CurrentKeywords.jsx'
import KeywordSearchTerms from './KeywordSearchTerms.jsx'
import FindKeywords from './FindKeywords.jsx'
import Experiments from './Experiments.jsx'
import ReviewBasket from './ReviewBasket.jsx'
import KeywordHistory from './KeywordHistory.jsx'
import {keywordKey,isLinked} from './keyword-ui.js'
import './workspace.css'
const tabs=['Current Keywords','Search Terms','Find Keywords','Experiments']
export default function KeywordLab({api=workspaceApi,writeMode,preferences=keywordLabPreferences,report}) {
 const [tab,setTab]=useState(tabs[0]),[scope,setScope]=useState({dateRange:'LAST_30_DAYS',campaignId:'',adGroupId:''}),[custom,setCustom]=useState({startDate:'',endDate:''}),[data,setData]=useState(null),[experiments,setExperiments]=useState([]),[catalog,setCatalog]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[experimentError,setExperimentError]=useState(''),[settings,setSettings]=useState({}),[preferencesReady,setPreferencesReady]=useState(false),[basket,setBasket]=useState([]),[basketOpen,setBasketOpen]=useState(false),[locked,setLocked]=useState(false),[expanded,setExpanded]=useState(null),[termScope,setTermScope]=useState(null),[keywordScope,setKeywordScope]=useState(null),[seed,setSeed]=useState(null)
 const ref=useRef({api,preferences});ref.current={api,preferences};const seq=useRef(0),saves=useRef(Promise.resolve())
 useEffect(()=>{let active=true;ref.current.preferences.load().then(v=>{if(active){setSettings(v||{});setPreferencesReady(true)}}).catch(e=>{if(active)setError(`Column preferences unavailable: ${e.message}`)});return()=>{active=false}},[])
 const load=useCallback(async()=>{const n=++seq.current;if(scope.dateRange==='CUSTOM'&&(!scope.startDate||!scope.endDate)){setLoading(false);return}setLoading(true);setError('');const values=await Promise.allSettled([ref.current.api('keyword_lab_snapshot',{params:scope}),ref.current.api('keyword_experiments',{params:scope})]);if(n!==seq.current)return;const [snapshot,experiment]=values;if(snapshot.status==='fulfilled'){setData(snapshot.value);setCatalog(old=>[...new Map([...old,...(snapshot.value.keywords||[]),...(report?.adGroups||[]).map(g=>({campaignId:String(g.campaignId),campaignName:g.campaignName||g.campaignId,adGroupId:String(g.adGroupId||g.id),adGroupName:g.adGroupName||g.name||g.id}))].map(r=>[`${r.campaignId}:${r.adGroupId}`,r])).values()])}else{setData(null);setError(snapshot.reason.message)}if(experiment.status==='fulfilled'){setExperiments(experiment.value.experiments||[]);setExperimentError((experiment.value.warnings||[]).map(w=>w.message).join(' '))}else{setExperiments([]);setExperimentError(experiment.reason.message)}setLoading(false)},[scope,report?.adGroups])
 useEffect(()=>{load();return()=>{seq.current++}},[load])
 function tableState(next){const value={...settings,[tab]:next};setSettings(value);if(preferencesReady)saves.current=saves.current.catch(()=>{}).then(()=>ref.current.preferences.save(value)).catch(e=>setError(`Could not save column preferences: ${e.message}`));}
 const canQueue=!!data?.liveActionsEnabled&&!loading&&!locked&&(scope.dateRange!=='CUSTOM'||!!(scope.startDate&&scope.endDate)),canApply=canQueue&&!!(data?.writeMode||writeMode)?.ready
 function queue(item){if(!canQueue)return;setBasket(old=>{const duplicate=old.some(r=>r.kind===item.kind&&r.campaignId===item.campaignId&&r.adGroupId===item.adGroupId&&r.keyword===item.keyword&&r.matchType===item.matchType);return duplicate?old:[...old,{...item,id:crypto.randomUUID()}]})}
 async function classify(row,classification){try{await api('keyword_classify_term',{method:'POST',body:{campaignId:row.campaignId,adGroupId:row.adGroupId,searchTerm:row.searchTerm,classification}});await load()}catch(e){setError(e.message)}}
 function openKeyword(term){setTab(tabs[0]);setTermScope(null);const row=(data?.keywords||[]).find(k=>isLinked(term,k));if(row){setKeywordScope(null);setExpanded(keywordKey(row));setSettings(s=>({...s,[tabs[0]]:{...s[tabs[0]],filters:[]}}))}else{setExpanded(null);setKeywordScope({campaignId:term.campaignId,adGroupId:term.adGroupId,keyword:term.triggeringKeyword,matchType:term.triggeringKeywordMatchType})}}
 function discover(phrases,source){setSeed({phrases,source,id:crypto.randomUUID()});setTab(tabs[2])}
 const keywords=(data?.keywords||[]).filter(k=>!keywordScope||(k.campaignId===keywordScope.campaignId&&k.adGroupId===keywordScope.adGroupId&&k.keyword===keywordScope.keyword&&k.matchType===keywordScope.matchType)),terms=(data?.searchTerms||[]).filter(t=>!termScope||isLinked(t,termScope)),currency=data?.account?.currencyCode||'USD'
 const shared={state:settings[tab]||{},onState:tableState,onQueue:queue,canQueue,currency}
 return <div className="mio-ads-workspace keyword-lab"><header className="aw-heading"><div><h2>Keyword Lab</h2><p>Audit relevant traffic, discover candidates, and review every live change.</p></div><button className="kl-primary" onClick={()=>setBasketOpen(true)}>Review Basket ({basket.length})</button></header><div className="aw-toolbar"><label>Campaign<select aria-label="Keyword Lab campaign" value={scope.campaignId} onChange={e=>{setScope(s=>({...s,campaignId:e.target.value,adGroupId:''}));setExpanded(null);setTermScope(null);setKeywordScope(null)}}><option value="">All campaigns</option>{[...new Map(catalog.map(r=>[r.campaignId,r.campaignName])).entries()].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Ad group<select aria-label="Keyword Lab ad group" value={scope.adGroupId} onChange={e=>{setScope(s=>({...s,adGroupId:e.target.value}));setTermScope(null);setKeywordScope(null)}}><option value="">All ad groups</option>{catalog.filter(r=>!scope.campaignId||r.campaignId===scope.campaignId).map(r=><option key={`${r.campaignId}:${r.adGroupId}`} value={r.adGroupId}>{r.adGroupName}</option>)}</select></label><label>Date range<select aria-label="Keyword Lab date range" value={scope.dateRange||'CUSTOM'} onChange={e=>{if(e.target.value==='CUSTOM')setScope(s=>({...s,dateRange:'CUSTOM'}));else setScope(s=>({dateRange:e.target.value,campaignId:s.campaignId,adGroupId:s.adGroupId}))}}>{[7,14,30,90].map(n=><option key={n} value={`LAST_${n}_DAYS`}>Last {n} days</option>)}<option value="CUSTOM">Custom</option></select></label>{scope.dateRange==='CUSTOM'&&<><label>Start<input type="date" value={custom.startDate} onChange={e=>setCustom(c=>({...c,startDate:e.target.value}))}/></label><label>End<input type="date" value={custom.endDate} onChange={e=>setCustom(c=>({...c,endDate:e.target.value}))}/></label><button onClick={()=>{try{const range=normalizeDateRange(custom);setCustom(range);setScope(s=>({...s,...range}))}catch(e){setError(e.message)}}}>Apply dates</button></>}<button disabled={loading} onClick={load}>Refresh Keyword Lab</button></div>{data?.range&&<small>{data.range.startDate} through {data.range.endDate} · {data.range.days} calendar days · {data.range.timeZone}</small>}{loading&&<p role="status">Loading Keyword Lab…</p>}{error&&<p role="alert">{error}</p>}{data?.warnings?.map((w,i)=><p role="status" key={i}>{w.section}: {w.message}</p>)}{!canQueue&&<p className="aw-notice">{locked?'An attempted basket is retained. Reconcile it before another live change.':'Live actions require complete current inventory.'}</p>}
 <nav className="kl-tabs" aria-label="Keyword Lab tabs">{tabs.map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>{(termScope||keywordScope)&&<p>Filtered by triggering keyword. {keywordScope&&'Google omitted criterion identity; showing text/match candidates without inferring a link.'}<button onClick={()=>{setTermScope(null);setKeywordScope(null)}}>Clear keyword link filter</button></p>}
 {data&&tab===tabs[0]&&<CurrentKeywords rows={keywords} terms={data.searchTerms||[]} {...shared} {...{experiments,expanded}} onExpanded={setExpanded} onTerms={r=>{setTermScope(r);setTab(tabs[1]);setSettings(s=>({...s,[tabs[1]]:{...s[tabs[1]],filters:[]}}))}} onKeyword={openKeyword} onClassify={classify} onDiscover={discover}/>}
 {data&&tab===tabs[1]&&<KeywordSearchTerms rows={terms} {...shared} onKeyword={openKeyword} onClassify={classify} onDiscover={discover}/>}
 {data&&tab===tabs[2]&&<FindKeywords key={seed?.id||'manual'} {...shared} {...{seed,api,data}} destinations={catalog}/>}
 {tab===tabs[3]&&<>{experimentError&&<p role="alert">{experimentError}</p>}<Experiments rows={experiments} keywords={data?.keywords||[]} {...shared} {...{api}} onRefresh={load} onInspect={key=>{setExpanded(key);setKeywordScope(null);setTab(tabs[0])}}/></>}
 <KeywordHistory api={api}/><ReviewBasket open={basketOpen} items={basket} onItems={setBasket} {...{api,canApply}} onClose={()=>setBasketOpen(false)} onApplied={load} onLock={setLocked}/></div>
}
