import React,{useState} from 'react'
import KeywordTable from './KeywordTable.jsx'
import {metricColumns,textColumn,termKey,termItem} from './keyword-ui.js'
export function TermActions({row,onQueue,onClassify,canQueue}) {
 return <div className="kl-actions"><select aria-label={`Classify ${row.searchTerm}`} value={row.classification||''} onChange={e=>onClassify(row,e.target.value)}><option value="" disabled>Unclassified</option>{['relevant','irrelevant','observe','promoted'].map(v=><option key={v}>{v}</option>)}</select>{['EXACT','PHRASE'].map(match=><React.Fragment key={match}><button disabled={!canQueue} onClick={()=>onQueue(termItem(row,'add_keyword',match))}>Add {match.toLowerCase()}</button><button disabled={!canQueue} onClick={()=>onQueue(termItem(row,'add_ad_group_negative',match))}>Negative {match.toLowerCase()}</button></React.Fragment>)}</div>
}
export default function KeywordSearchTerms({rows,state,onState,onKeyword,onQueue,onClassify,canQueue,onDiscover,compact=false,currency}) {
 const [localState,setLocalState]=useState({})
 const [selection,setSelection]=useState([]),[match,setMatch]=useState('EXACT'),[negativeScope,setNegativeScope]=useState('add_ad_group_negative')
 const selected=rows.filter(r=>selection.includes(termKey(r)))
 const queue=kind=>{selected.forEach(r=>onQueue(termItem(r,kind,match)));setSelection([])}
 const columns=[{...textColumn('searchTerm','Search term'),required:true}, {...textColumn('triggeringKeyword','Triggering keyword'),render:r=>r.triggeringKeyword?<button className="kl-link" onClick={()=>onKeyword(r)}>{r.triggeringKeyword}</button>:'—'},textColumn('triggeringKeywordMatchType','Keyword match','categorical'),textColumn('matchType','Search-term match','categorical'),{...textColumn('campaignName','Campaign'),hidden:compact},{...textColumn('adGroupName','Ad group'),hidden:compact},textColumn('device','Device','categorical'),...metricColumns.map(c=>({...c,hidden:compact&&['impressionsPerDay','clicksPerDay','costPerDay','conversionRate','costPerConversion'].includes(c.key)})),textColumn('classification','Classification','categorical'),{...textColumn('keywordStatus','Already a keyword','categorical')},{...textColumn('negativeStatus','Negative coverage','categorical')},{key:'actions',label:'Actions',render:r=><TermActions row={r} {...{onQueue,onClassify,canQueue}}/>}]
 const enriched=rows.map(r=>({...r,keywordStatus:r.keywordCoverage?'Yes':'No',negativeStatus:r.negativeCoverage?`${r.negativeCoverage.scope||'Covered'}: ${r.negativeCoverage.keyword||''}`:'Not covered'}))
 return <><p>Google-reported triggering attribution. Privacy-withheld searches are not included; this is not a complete visitor log.</p><div className="aw-toolbar"><span>{selected.length} selected</span>{onDiscover&&<button disabled={!selected.length} onClick={()=>onDiscover(selected.map(r=>r.searchTerm),"search_term")}>Find from selected terms</button>}<label>Promotion / negative match<select value={match} onChange={e=>setMatch(e.target.value)}><option>EXACT</option><option>PHRASE</option></select></label><button disabled={!canQueue||!selected.length} onClick={()=>queue('add_keyword')}>Queue selected keywords</button><label>Negative destination<select value={negativeScope} onChange={e=>setNegativeScope(e.target.value)}><option value="add_ad_group_negative">Ad group</option><option value="add_campaign_negative">Campaign</option></select></label><button disabled={!canQueue||!selected.length} onClick={()=>queue(negativeScope)}>Queue selected negatives</button></div><KeywordTable label={compact?'Triggered search terms':'Search Terms'} rows={enriched} columns={columns} state={state||localState} onState={onState||setLocalState} currency={currency} rowKey={termKey} selection={selection} onSelection={setSelection}/></>
}
