import React,{useState} from 'react'
import {Modal,Notice} from './Common.jsx'
import {matches} from './keyword-ui.js'
export default function ReviewBasket({open,items,onItems,api,canApply,onClose,onApplied,onLock}) {
 const [review,setReview]=useState(null),[authorized,setAuthorized]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null),[attempted,setAttempted]=useState(false)
 const edit=next=>{onItems(next);setReview(null);setAuthorized(false);setError('')}
 async function run(action){setBusy(true);setError('');try{if(action==='review'){const next=await api('keyword_review',{method:'POST',body:{requestId:crypto.randomUUID(),items}});setReview({...next,basketVersion:JSON.stringify(items)});setAuthorized(false)}else if(action==='apply'){setAttempted(true);onLock(true);setAuthorized(false);const r=await api('keyword_apply',{method:'POST',body:{requestId:review.requestId,reviewId:review.reviewId,fingerprint:review.fingerprint,items:review.items,confirmation:'APPLY'}});setResult(r);await onApplied()}else{const r=await api('keyword_verify',{method:'POST',body:{eventId:result.eventId}});setResult(r);await onApplied()}}catch(e){setError(`${e.message}${action==='apply'?' Do not retry this approval. Reconcile from change history.':''}`);if(action==='apply'){try{const history=await api('workspace_history');const event=history.entries?.find(x=>x.kind==='keyword_lab'&&x.before_snapshot?.phase==='apply'&&x.result?.requestId===review.requestId);if(event)setResult({...event.result,eventId:event.id})}catch{/* Original error remains visible; no write is retried. */}}}finally{setBusy(false)}}
 if(!open)return null
 const currentReview=review?.basketVersion===JSON.stringify(items)
 const shown=currentReview?review.items:items
 return <Modal title="Review Basket" onClose={onClose} busy={busy}><Notice>Nothing changes in Google Ads until you review and explicitly authorize these exact items.</Notice>{shown.map((item,i)=><section className="kl-basket-item" key={item.id}><strong>{item.kind.replaceAll('_',' ')} — {item.keyword}</strong><p>{item.campaignName||item.campaignId} / {item.adGroupName||item.adGroupId||'Campaign level'}</p><p>Before: {item.original?`${item.original.matchType} / ${item.original.status}`:'New criterion'} → Proposed: {item.matchType}{item.kind==='pause_keyword'?' / PAUSED':item.kind==='enable_keyword'?' / ENABLED':''}</p><small>Experimental: {item.kind==='add_experimental_keyword'?'Yes':'No'} · Source: {item.source||'manual'} · {item.hypothesis||'No hypothesis'}</small><div className="kl-actions"><label>Proposed match<select aria-label={`Basket match ${i+1}`} disabled={busy||attempted||['pause_keyword','enable_keyword'].includes(item.kind)} value={item.matchType} onChange={e=>edit(items.map(x=>x.id===item.id?{...x,matchType:e.target.value}:x))}>{matches.map(m=><option key={m}>{m}</option>)}</select></label><button disabled={busy||attempted} onClick={()=>edit(items.filter(x=>x.id!==item.id))}>Remove item</button></div></section>)}
 <Notice error>{error}</Notice>{result&&<section aria-label="Keyword apply results"><strong>Outcome: {result.status||'unverified'}</strong><Notice error>{result.historyWarning}</Notice>{result.results?.map(r=><div key={r.id}><p>{r.item?.keyword}: {r.state} — {r.message}</p>{['create','pause','status','experiment'].map(k=>r[k]&&<small key={k}>{k}: {r[k].state} {r[k].message} {r[k].resourceName||''} {r[k].requestId?`Google request ${r[k].requestId}`:''} {r[k].observedStatus?`Observed: ${r[k].observedStatus}`:''}</small>)}</div>)}</section>}
 {!attempted&&<><button disabled={busy||!items.length} onClick={()=>run('review')}>Review exact changes</button>{currentReview&&<><label className="kl-authorize"><input type="checkbox" checked={authorized} disabled={busy||!canApply} onChange={e=>setAuthorized(e.target.checked)}/>I authorize these exact Keyword Lab changes.</label><button disabled={busy||!authorized||!canApply} onClick={()=>run('apply')}>Authorize and apply</button></>}</>}
 {attempted&&<><Notice>This approval cannot be submitted again. Recheck uncertain outcomes before starting a new basket.</Notice>{result?.eventId&&<button disabled={busy} onClick={()=>run('verify')}>Recheck outcome (read-only)</button>}{result?.status==='verified'&&!result.historyWarning&&<button disabled={busy} onClick={()=>{onItems([]);setReview(null);setResult(null);setAttempted(false);onLock(false);onClose()}}>Clear verified basket</button>}</>}
 </Modal>
}
