import React,{useCallback,useEffect,useRef,useState} from 'react'
import {preferencesStore} from './client.js'
import {aggregateMetrics} from '../../lib/ads/model.js'
import {AdPreview,AssetList,Notice,money,percent,Results} from './Common.jsx'
import SearchTerms from './SearchTerms.jsx'
import AdEditor from './AdEditor.jsx'
import './workspace.css'
function Comparison({value}){if(!value)return null;if(!value.ready)return<Notice>{value.message}</Notice>;const terms=new Map();for(const key of['before','after'])for(const r of value[key].terms||[]){if(!terms.has(r.searchTerm))terms.set(r.searchTerm,{term:r.searchTerm,before:[],after:[]});terms.get(r.searchTerm)[key].push(r)}return<section><Notice>{value.warning}</Notice><p>Equal {value.days}-day windows, excluding the edit day and today.</p><div className="aw-compare">{['before','after'].map(k=><section key={k}><h4>{k}: {value[k].range.start} through {value[k].range.end}</h4><p>{value[k].metrics.clicks} clicks | {money(value[k].metrics.cost)} | CTR {percent(value[k].metrics.ctr)} | {value[k].metrics.conversions} conversions</p></section>)}</div><div className="aw-scroll"><table><thead><tr><th>Ad-group search term</th><th>Before clicks</th><th>After clicks</th><th>Before cost</th><th>After cost</th></tr></thead><tbody>{[...terms.values()].sort((a,b)=>aggregateMetrics(b.after).cost-aggregateMetrics(a.after).cost).slice(0,50).map(r=>{const b=aggregateMetrics(r.before),a=aggregateMetrics(r.after);return<tr key={r.term}><td>{r.term}</td><td>{b.clicks}</td><td>{a.clicks}</td><td>{money(b.cost)}</td><td>{money(a.cost)}</td></tr>})}</tbody></table></div></section>}
export function WorkspaceHistory({api}){
 const[open,setOpen]=useState(false),[entries,setEntries]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[comparisons,setComparisons]=useState({});const call=useRef(api);call.current=api
 const load=async()=>{setBusy(true);setError('');try{const r=await call.current('workspace_history');setEntries(r.entries||[])}catch(e){setError(e.message)}finally{setBusy(false)}}
 return<div className="mio-ads-workspace aw-history-wrap"><details className="aw-history" open={open} onToggle={e=>{if(e.target!==e.currentTarget)return;setOpen(e.currentTarget.open);if(e.currentTarget.open)load()}}><summary>Ad workspace change history</summary>{open&&<><p>Latest 100 workspace approvals saved in Supabase. Earlier single-action history remains in the original log.</p><button disabled={busy} onClick={load}>{busy?'Loading history...':'Refresh history'}</button><Notice error>{error}</Notice>{entries.map(e=><details className="aw-history-entry" key={e.id}><summary>{new Date(e.created_at).toLocaleString()} - {e.kind==='rsa_update'?`Ad ${e.before_snapshot?.adId} revision`:`${e.before_snapshot?.items?.length||0} campaign negatives`} - {e.status}</summary><small>Approver: {e.actor_email}. Google request: {e.result?.requestId||'not available'}.</small>{e.kind==='rsa_update'?<><div className="aw-compare"><section><AdPreview ad={e.before_snapshot.ad} title="Before revision"/><AssetList ad={e.before_snapshot.ad}/></section><section><AdPreview ad={e.after_snapshot} title="Approved revision"/><AssetList ad={e.after_snapshot}/></section></div><button disabled={e.status!=='verified'} onClick={async()=>{try{const v=await call.current('workspace_compare',{params:{eventId:e.id}});setComparisons(c=>({...c,[e.id]:v}))}catch(err){setError(err.message)}}}>Compare before / after performance</button><Comparison value={comparisons[e.id]}/></>:<Results result={e.result||{results:(e.after_snapshot?.items||[]).map(i=>({...i,state:e.status}))}}/>}{['prepared','unverified'].includes(e.status)&&<><Notice>This outcome is not yet confirmed. Check current state before submitting another change.</Notice><button onClick={async()=>{try{await call.current('workspace_verify',{method:'POST',body:{eventId:e.id}});await load()}catch(err){setError(err.message)}}}>Recheck outcome (read-only)</button></>}</details>)}{!busy&&!entries.length&&<p>No workspace approvals recorded yet.</p>}</>}</details></div>
}
export default function MioAdsWorkspace({mode,report,api,onRefresh,writeMode,queueMutation,classify,preferences=preferencesStore}){
 const[data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState(''),[campaign,setCampaign]=useState('');const ref=useRef({api,onRefresh});ref.current={api,onRefresh};const seq=useRef(0),days=report?.range?.days||30
 const load=useCallback(async()=>{const n=++seq.current;setLoading(true);setError('');try{const v=await ref.current.api('workspace_snapshot',{params:{days}});if(n===seq.current)setData(v);return v}catch(e){if(n===seq.current)setError(e.message);return null}finally{if(n===seq.current)setLoading(false)}},[days])
 useEffect(()=>{load();return()=>{seq.current++}},[load,report?.fetchedAt])
 const applied=async()=>{await load();await ref.current.onRefresh?.()}
 const ads=(data?.ads||[]).filter(a=>!campaign||a.campaignId===campaign),ad=ads.find(a=>`${a.adGroupId}:${a.id}`===selected)||ads[0]
 return<div className="mio-ads-workspace"><div className="aw-toolbar"><small>{loading?'Refreshing from Google...':data?.fetchedAt?`Account data read ${new Date(data.fetchedAt).toLocaleTimeString()}`:''}</small><button disabled={loading} onClick={load}>Refresh workspace</button></div><Notice error>{error}</Notice>{data?.warnings?.map((w,i)=><Notice key={i} error>{w.section}: {w.message}</Notice>)}{!data&&!loading&&<p>Workspace data is unavailable. Retry Refresh workspace.</p>}{data&&(mode==='search_terms'?<SearchTerms data={data} api={api} onApplied={applied} queueMutation={queueMutation} writeMode={writeMode} classify={classify} preferences={preferences}/>:<section><header className="aw-heading"><div><h2>Ad workspace</h2><p>Actual Google ad assets, drafts, and same-ad-group search terms.</p></div><span className="aw-release">Ad workspace V317</span></header><div className="aw-toolbar"><label>Campaign<select value={campaign} onChange={e=>{setCampaign(e.target.value);setSelected('')}}><option value="">All campaigns</option>{[...new Map(data.ads.map(a=>[a.campaignId,a.campaignName])).entries()].map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><label>Ad<select value={ad?`${ad.adGroupId}:${ad.id}`:''} onChange={e=>setSelected(e.target.value)}>{ads.map(a=><option key={`${a.adGroupId}:${a.id}`} value={`${a.adGroupId}:${a.id}`}>{a.campaignName} / {a.headlines?.[0]?.text||a.name||a.id} ({a.status})</option>)}</select></label></div>{ad?<AdEditor key={`${ad.adGroupId}:${ad.id}`} ad={ad} data={data} api={api} onApplied={applied} writeMode={writeMode} queueMutation={queueMutation}/>:<Notice>No ads were returned. Check campaign selection and query warnings.</Notice>}</section>)}<WorkspaceHistory api={api}/></div>
}
