import crypto from 'node:crypto'
import { Buffer } from 'node:buffer'

function env(name,fallback=''){return String(process.env[name]||fallback||'').trim()}
function boolEnv(name){return /^(1|true|yes|on)$/i.test(env(name))}
function json(res,status,payload){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(payload))}
function action(req){if(req.query?.action)return String(req.query.action);try{return new URL(req.url||'/','https://mio.local').searchParams.get('action')||''}catch{return''}}
function query(req,key){if(req.query?.[key]!=null)return String(req.query[key]);try{return new URL(req.url||'/','https://mio.local').searchParams.get(key)||''}catch{return''}}
function body(req){if(!req.body)return{};if(typeof req.body==='object'&&!Buffer.isBuffer(req.body))return req.body;const raw=Buffer.isBuffer(req.body)?req.body.toString('utf8'):String(req.body);if(!raw.trim())return{};try{return JSON.parse(raw)}catch{const p=new URLSearchParams(raw);if(p.has('json'))return JSON.parse(p.get('json'));return Object.fromEntries(p)}}
function supabaseConfig(){return{url:env('SUPABASE_URL')||env('VITE_SUPABASE_URL')||env('NEXT_PUBLIC_SUPABASE_URL'),key:env('SUPABASE_PUBLISHABLE_KEY')||env('SUPABASE_ANON_KEY')||env('VITE_SUPABASE_ANON_KEY')||env('NEXT_PUBLIC_SUPABASE_ANON_KEY')}}
async function verifyUser(req){const authorization=String(req.headers?.authorization||'');if(!/^Bearer\s+\S+/i.test(authorization)){const e=new Error('Sign in to Mio before using Dropbox Sign.');e.status=401;throw e}const{url,key}=supabaseConfig();if(!url||!key){const e=new Error('The server is missing Supabase authentication configuration.');e.status=503;throw e}const r=await fetch(`${url.replace(/\/$/,'')}/auth/v1/user`,{headers:{apikey:key,Authorization:authorization}}),u=await r.json().catch(()=>({}));if(!r.ok||!u?.id){const e=new Error('Your Mio session could not be verified. Sign in again.');e.status=401;throw e}const email=String(u.email||'').toLowerCase(),domain=env('MIO_DROPBOX_SIGN_ALLOWED_DOMAIN','beveridgelawfirm.com').toLowerCase();if(!email||domain&&!email.endsWith('@'+domain)){const e=new Error('This Mio account is not authorized to use Dropbox Sign.');e.status=403;throw e}return{id:u.id,email}}
function apiKey(){return env('DROPBOX_SIGN_API_KEY')||env('HELLOSIGN_API_KEY')}
function basic(){const key=apiKey();if(!key){const e=new Error('DROPBOX_SIGN_API_KEY is not configured on the server.');e.status=503;throw e}return'Basic '+Buffer.from(key+':').toString('base64')}
async function ds(path,options={}){const r=await fetch('https://api.hellosign.com/v3'+path,{...options,headers:{Authorization:basic(),Accept:'application/json',...(options.headers||{})}});const text=await r.text(),payload=text?(()=>{try{return JSON.parse(text)}catch{return{text}}})():{};if(!r.ok){const e=new Error(payload?.error?.error_msg||payload?.error?.error_name||payload?.message||`Dropbox Sign returned HTTP ${r.status}.`);e.status=r.status;e.payload=payload;throw e}return payload}
function allowedFileUrl(raw){let u;try{u=new URL(String(raw||''))}catch{throw Object.assign(new Error('A document URL is invalid.'),{status:400})}if(u.protocol!=='https:')throw Object.assign(new Error('Document URLs must use HTTPS.'),{status:400});const{url}=supabaseConfig();let host='';try{host=new URL(url).hostname.toLowerCase()}catch{}const ref=host.endsWith('.supabase.co')?host.slice(0,-'.supabase.co'.length):'',allowed=new Set([host,ref?`${ref}.storage.supabase.co`:''].filter(Boolean));if(!allowed.has(u.hostname.toLowerCase())||!/\/storage\/v1\/object\//.test(u.pathname))throw Object.assign(new Error('Dropbox Sign may only fetch temporary Mio Supabase Storage URLs.'),{status:400});return u.toString()}
function cleanSigners(values){if(!Array.isArray(values)||!values.length)throw Object.assign(new Error('Choose at least one signer.'),{status:400});return values.map((s,i)=>{const email=String(s?.email_address||s?.email||'').trim().toLowerCase(),name=String(s?.name||s?.label||'').trim();if(!/^\S+@\S+\.\S+$/.test(email)||!name)throw Object.assign(new Error(`Signer ${i+1} needs a name and valid email.`),{status:400});return{email_address:email,name,order:Number.isFinite(Number(s?.order))?Number(s.order):i}})}
async function sendRequest(req,res,user){if(!boolEnv('MIO_DROPBOX_SIGN_WRITES_ENABLED'))return json(res,403,{error:'Dropbox Sign sending is locked. Set MIO_DROPBOX_SIGN_WRITES_ENABLED=true after test-mode review.'});const b=body(req);if(b.confirm_send!==true)return json(res,400,{error:'Final Dropbox Sign send authorization was not received.'});const files=(b.file_urls||[]).map(allowedFileUrl);if(!files.length)return json(res,400,{error:'Choose at least one reviewed PDF.'});if(files.length>10)return json(res,400,{error:'Send at most 10 files in one signature request.'});const signers=cleanSigners(b.signers),testMode=env('MIO_DROPBOX_SIGN_MODE','test').toLowerCase()!=='live';if(!testMode&&!boolEnv('MIO_DROPBOX_SIGN_LIVE_ENABLED'))return json(res,403,{error:'Live Dropbox Sign is locked. Set MIO_DROPBOX_SIGN_LIVE_ENABLED=true only when ready for legally binding requests.'});const payload={file_urls:files,signers,title:String(b.title||'Signature request').slice(0,255),subject:String(b.subject||b.title||'Signature request').slice(0,255),message:String(b.message||'Please review and sign the attached document.').slice(0,5000),test_mode:testMode,metadata:{mio_user_id:user.id,mio_matter_id:String(b.matter_id||'').slice(0,100),mio_step_id:String(b.step_id||'').slice(0,100)}};const clientId=env('DROPBOX_SIGN_CLIENT_ID');if(clientId)payload.client_id=clientId;const data=await ds('/signature_request/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});console.info('Mio Dropbox Sign request sent',{user:user.email,testMode,requestId:data?.signature_request?.signature_request_id||'',matterId:b.matter_id||'',stepId:b.step_id||''});json(res,200,{provider:'dropbox_sign',mode:testMode?'test':'live',signature_request:data.signature_request||data})}
function callbackPayload(req){const b=body(req);return b&&b.event?b:(b?.json?JSON.parse(b.json):b)}
function verifyCallback(payload){const event=payload?.event||{},expected=crypto.createHmac('sha256',apiKey()).update(String(event.event_time||'')+String(event.event_type||'')).digest('hex'),actual=String(event.event_hash||'');return actual.length===expected.length&&crypto.timingSafeEqual(Buffer.from(actual),Buffer.from(expected))}
export default async function handler(req,res){if(req.method==='OPTIONS'){res.statusCode=204;return res.end()}try{const a=action(req);if(a==='callback'&&req.method==='POST'){const p=callbackPayload(req);if(!verifyCallback(p)){res.statusCode=401;return res.end('Invalid Dropbox Sign callback')}console.info('Mio Dropbox Sign callback',{event:p.event?.event_type||'',requestId:p.signature_request?.signature_request_id||'',metadata:p.signature_request?.metadata||{}});res.statusCode=200;res.setHeader('Content-Type','text/plain; charset=utf-8');return res.end('Hello API Event Received')}
 const user=await verifyUser(req);if(a==='status'&&req.method==='GET')return json(res,200,{provider:'dropbox_sign',configured:Boolean(apiKey()),mode:env('MIO_DROPBOX_SIGN_MODE','test').toLowerCase()==='live'?'live':'test',writesEnabled:boolEnv('MIO_DROPBOX_SIGN_WRITES_ENABLED'),liveEnabled:boolEnv('MIO_DROPBOX_SIGN_LIVE_ENABLED'),clientIdConfigured:Boolean(env('DROPBOX_SIGN_CLIENT_ID'))});if(a==='send'&&req.method==='POST')return sendRequest(req,res,user);if(a==='get'&&req.method==='GET'){const id=query(req,'signature_request_id');if(!/^[A-Za-z0-9_-]{8,200}$/.test(id))return json(res,400,{error:'A valid signature request ID is required.'});const data=await ds('/signature_request/'+encodeURIComponent(id));return json(res,200,data)}if(a==='files'&&req.method==='GET'){const id=query(req,'signature_request_id');if(!/^[A-Za-z0-9_-]{8,200}$/.test(id))return json(res,400,{error:'A valid signature request ID is required.'});const data=await ds('/signature_request/files_as_data_uri/'+encodeURIComponent(id));return json(res,200,data)}return json(res,404,{error:'Unknown Dropbox Sign action.'})}catch(error){const status=Number(error?.status||500);console.error('Mio Dropbox Sign API error',{status,message:error?.message||String(error)});return json(res,status>=400&&status<=599?status:500,{error:error?.message||'Dropbox Sign request failed.'})}}
